src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <inlineHelpText>Type in the name of Agency. If you deal directly with the Brand type in Brand Direct</inlineHelpText>
        <label>Agency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                    <default>true</default>
                    <label>NA</label>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>APAC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Ad Placements</relationshipLabel>
        <relationshipName>AdPlacements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ad Placement</label>
    <nameField>
        <label>Ad Placement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BillingCondition__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Condition</label>
    <nameField>
        <label>Billing Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Conditions</pluralLabel>
    <recordTypes>
        <fullName>Normal</fullName>
        <active>true</active>
        <label>Normal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rebate</fullName>
        <active>true</active>
        <label>Rebate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <formula>Account.Agency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Condition</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>BillingCondition__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BillingCondition__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_End__c</fullName>
        <inlineHelpText>The date that the campaign will finish.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Start__c</fullName>
        <inlineHelpText>The date that the campaign will start.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IO__c</fullName>
        <label>IO #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MeetingDate__c</fullName>
        <label>Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adwords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Reddit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                    <isActive>false</isActive>
                    <label>Instagram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>text(Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Platform_Selected__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>13-17</fullName>
                </value>
                <value>
                    <fullName>18-20</fullName>
                </value>
                <value>
                    <fullName>18-24</fullName>
                </value>
                <value>
                    <fullName>21-24</fullName>
                </value>
                <value>
                    <fullName>25-34</fullName>
                </value>
                <value>
                    <fullName>35+</fullName>
                </value>
                <value>
                    <fullName>35-44</fullName>
                </value>
                <value>
                    <fullName>35-54</fullName>
                </value>
                <value>
                    <fullName>45-54</fullName>
                </value>
                <value>
                    <fullName>55+</fullName>
                </value>
                <value>
                    <fullName>55-64</fullName>
                </value>
                <value>
                    <fullName>65+</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facebook_page__c</fullName>
        <label>Facebook Page</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NoCostStructure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Cost Structure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Objectives__c</fullName>
        <label>Objectives</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Platform_Selected__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>App Installs</fullName>
                </value>
                <value>
                    <fullName>Awareness</fullName>
                </value>
                <value>
                    <fullName>Boost Engagement</fullName>
                </value>
                <value>
                    <fullName>Brand Awareness</fullName>
                </value>
                <value>
                    <fullName>Conversions</fullName>
                </value>
                <value>
                    <fullName>Drive Installs of My App</fullName>
                </value>
                <value>
                    <fullName>Drive Traffic to App</fullName>
                </value>
                <value>
                    <fullName>Drive Traffic to My Website</fullName>
                </value>
                <value>
                    <fullName>Engagement</fullName>
                </value>
                <value>
                    <fullName>Event Responses</fullName>
                </value>
                <value>
                    <fullName>Get People to View My Content</fullName>
                </value>
                <value>
                    <fullName>Grow Awareness</fullName>
                </value>
                <value>
                    <fullName>Lead Generation</fullName>
                </value>
                <value>
                    <fullName>Local Awareness</fullName>
                </value>
                <value>
                    <fullName>Offer Claims</fullName>
                </value>
                <value>
                    <fullName>Page Likes</fullName>
                </value>
                <value>
                    <fullName>Post Engagements</fullName>
                </value>
                <value>
                    <fullName>Product Catalogue Sales</fullName>
                </value>
                <value>
                    <fullName>Reach</fullName>
                </value>
                <value>
                    <fullName>Store Visits</fullName>
                </value>
                <value>
                    <fullName>Traffic</fullName>
                </value>
                <value>
                    <fullName>Tweet Engagements</fullName>
                </value>
                <value>
                    <fullName>Video Views</fullName>
                </value>
                <value>
                    <fullName>Website Conversions</fullName>
                </value>
                <value>
                    <fullName>Website Traffic</fullName>
                </value>
                <value>
                    <fullName>Website Visits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Platform__c.object
<CustomObject>
    <fields>
        <fullName>CostStructures__c</fullName>
        <label>Cost Structure</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPA</fullName>
                </value>
                <value>
                    <fullName>CPAC</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPE</fullName>
                </value>
                <value>
                    <fullName>CPER</fullName>
                </value>
                <value>
                    <fullName>CPF</fullName>
                </value>
                <value>
                    <fullName>CPI</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>CPLC</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPPL</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CPSU</fullName>
                </value>
                <value>
                    <fullName>CPV</fullName>
                </value>
                <value>
                    <fullName>CPLP</fullName>
                </value>
                <value>
                    <fullName>CPCO</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>CPDPV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prefix__c</fullName>
        <label>Prefix</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PostSandboxRefresh.cls
/*
The class is a script used to create test data for a refreshed sandbox
*/

public class PostSandboxRefresh {
    public static Map<String, Platform__c> platformsMap = new Map<String, Platform__c>();
    private static List <Platform__c> platforms;

    public static Map <String, Object []> createObjectsForOpportunity () {
        Map <String, Object []> objects = new Map <String, Object []> ();

        Account acc0 = new Account();
        acc0.Name  		   	= 'testAcc0';
        acc0.Agency__c	   	= 'testAgency0';
        acc0.Region__c		= 'NA';
        acc0.Website		= 'www.test0.com';
        acc0.BillingCountry = 'USA';
        acc0.BillingCity	= 'Chicago';
        acc0.BillingState   = 'IL';

        Account acc1 = new Account();
        acc1.Name  		   	= 'testAcc1';
        acc1.Agency__c	   	= 'testAgency1';
        acc1.Region__c		= 'NA';
        acc1.Website		= 'www.test1.com';
        acc1.BillingCountry = 'France';
        acc1.BillingCity	= 'Paris';
        acc1.BillingState   = 'SomeState1';

        Account [] accounts = new Account [] {acc0, acc1};
        Database.insert (accounts, false);

        Brand__c brand0 = new Brand__c ();
        brand0.Name = 'BR0';

        Brand__c brand1 = new Brand__c ();
        brand1.Name = 'BR2';

        Brand__c [] brands = new Brand__c [] {brand0, brand1};
        Database.insert(brands, false);

        BillingCondition__c bc0 = TestHelper.createBillingCondition('Normal', false);
        bc0.Active__c = true;

        BillingCondition__c bc1 = TestHelper.createBillingCondition('Rebate 10% / 30%', false);
        bc1.Active__c = true;

        List<BillingCondition__c> billingConditions = new List<BillingCondition__c>{bc0, bc1};
        Database.insert(billingConditions, false);

        Platform__c platformFB = createPlatform('Facebook', 'FB'),
                    platformIG = createPlatform('Instagram', 'IG'),
                    platformTV = createPlatform('TrueView', 'TV'),
                    platformTW = createPlatform('Twitter', 'TW'),
                    platformLN = createPlatform('LinkedIn', 'LN');

        platformFB.CostStructures__c = 'CPC;CPAC';
        platformIG.CostStructures__c = 'CPC;CPE';
        platformLN.CostStructures__c = 'CPC;CPAC';
        platformTV.CostStructures__c = 'CPE';
        platformTW.CostStructures__c = 'CPE;CPAC';

        Platform__c [] platforms = new Platform__c [] {platformFB, platformIG, platformTV, platformTW, platformLN};
        for (Platform__c existingPlatform : PlatformRepository.getAvailablePlatforms()) {
            for (Integer i = 0; i < platforms.size(); i++)
            {
                if (existingPlatform.Name.equals (platforms [i].Name)) platforms.remove(i);
            }
        }
        insert platforms;

        AdPlacement__c adPlacement = createAdPlacement([SELECT Id, Name FROM Platform__c WHERE Name LIKE 'Facebook'] [0].Id, 'testAdPlacement');
        if ([SELECT Name FROM AdPlacement__c WHERE Name = 'testAdPlacement'].size() < 2) {
            insert adPlacement;
        }
        User usr = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];

        objects.put ('Users', new User [] {usr});
        objects.put ('Accounts', [SELECT Id, Name FROM Account WHERE Name LIKE 'testAcc%']);
        objects.put ('Brands', [SELECT Id, Name FROM Brand__c WHERE Name LIKE 'BR%']);
        objects.put ('BillingConditions', [SELECT Id, Name FROM BillingCondition__c WHERE Name LIKE 'Rebate%']);
        objects.put ('Platforms', [SELECT Id, Name FROM Platform__c ORDER BY Name]);

        return objects;
    }

    public static void createOpportunityPreMeeting (String name) {
        platforms = PlatformRepository.getAvailablePlatforms();
        for (Platform__c pl : platforms) {
            platformsMap.put (pl.Prefix__c, pl);
        }

        Map <String, Object []> objectsForOpportunity = createObjectsForOpportunity ();
        Opportunity opp = new Opportunity ();
        opp.Name = name;
        opp.Brand__c = ((Brand__c []) objectsForOpportunity.get ('Brands')) [0].Id;
        opp.AccountId = ((Account []) objectsForOpportunity.get ('Accounts')) [0].Id;
        opp.BillingCondition__c = ((BillingCondition__c []) objectsForOpportunity.get ('BillingConditions')) [0].Id;
        opp.OwnerId = ((User []) objectsForOpportunity.get ('Users')) [0].Id;
        opp.Flight_Start__c = Date.newInstance(System.today().year() + 1, 1, 1);
        opp.Flight_End__c = Date.newInstance(System.today().year() + 1, 3, 31);
        opp.CloseDate = Date.newInstance(System.today().year() + 1, 3, 31);
        opp.MeetingDate__c = System.today();
        opp.StageName = 'Qualification';
        opp.Amount = 1000000;
        opp.CurrencyIsoCode = 'USD';
        opp.IO__c = '5';
        insert opp;

        OpportunityPlatform__c oppPlatformFB = new OpportunityPlatform__c ();
        oppPlatformFB.Opportunity__c = opp.Id;
        oppPlatformFB.Platform__c = platformsMap.get ('FB').Id; // ((Platform__c) objectsForOpportunity.get ('Platforms') [3]).Id;
        oppPlatformFB.NoCostStructure__c = true;
        oppPlatformFB.Facebook_page__c = 'FB fb page';
        oppPlatformFB.Objectives__c = 'Offer Claims;Brand Awareness';
        oppPlatformFB.Companion_Banner__c = 'Yes';
        oppPlatformFB.Pixel_Tracking__c = 'Yes';
        oppPlatformFB.CTA_Overlay_Text__c = 'CTA FB';
        oppPlatformFB.PlatformAccount__c = '12345';
        oppPlatformFB.Account_Entity__c = 'US';
        oppPlatformFB.Gender__c = 'Male;Female';
        oppPlatformFB.Age_min__c = 28;
        oppPlatformFB.Age_max__c = 33;
        oppPlatformFB.KPI__c = 'FB KPI';
        insert oppPlatformFB;

        OpportunityPlatform__c oppPlatformIG = new OpportunityPlatform__c ();
        oppPlatformIG.Opportunity__c = opp.Id;
        oppPlatformIG.Platform__c = platformsMap.get ('IG').Id; // ((Platform__c) objectsForOpportunity.get ('Platforms') [5]).Id;
        oppPlatformIG.NoCostStructure__c = true;
        oppPlatformIG.Objectives__c = 'Video Views;Post Engagements;App Installs';
        oppPlatformIG.Companion_Banner__c = 'Yes';
        oppPlatformIG.Pixel_Tracking__c = 'Yes';
        oppPlatformIG.CTA_Overlay_Text__c = 'CTA IG';
        oppPlatformIG.Facebook_page__c = 'IG fb page';
        oppPlatformIG.PlatformAccount__c = '12345';
        oppPlatformIG.Account_Entity__c = 'US';
        oppPlatformIG.Gender__c = 'Female';
        oppPlatformIG.Age_min__c = 18;
        oppPlatformIG.Age_max__c = 23;
        oppPlatformIG.KPI__c = 'IG KPI';
        insert oppPlatformIG;

        OpportunityPlatform__c oppPlatformTV = new OpportunityPlatform__c ();
        oppPlatformTV.Opportunity__c = opp.Id;
        oppPlatformTV.Platform__c = platformsMap.get ('TV').Id; //((Platform__c) objectsForOpportunity.get ('Platforms') [9]).Id;
        oppPlatformTV.NoCostStructure__c = true;
        oppPlatformTV.Objectives__c = 'Conversions;Reach';
        oppPlatformTV.Companion_Banner__c = 'Yes';
        oppPlatformTV.Pixel_Tracking__c = 'Yes';
        oppPlatformTV.CTA_Overlay_Text__c = 'CTA TV';
        oppPlatformTV.PlatformAccount__c = '111-222-3333';
        oppPlatformTV.Facebook_page__c = 'TV fb page';
        oppPlatformTV.Gender__c = 'Male';
        oppPlatformTV.KPI__c = 'TV KPI';
        oppPlatformTV.Age__c = '25-34';
        insert oppPlatformTV;
    }

    public static Platform__c createPlatform(String platformName, String prefix) {
        if (!platformsMap.containsKey(prefix)) {
            Platform__c platform = new Platform__c();
            platform.Name = platformName;
            platform.Prefix__c = prefix;

            if (platformName == 'TrueView' || platformName == 'AdWords')
            platform.Provider__c = 'AdWords';

            else platform.Provider__c = 'DBM';

            if (platformName != 'TrueView') platform.Type__c = 'Social';
            else platform.Type__c = 'YT';
            platformsMap.put(prefix, platform);
        }
        System.debug ('');
        return platformsMap.get(prefix);
    }

    public static AdPlacement__c createAdPlacement(Id platformId, String adPlacementName) {
        AdPlacement__c adPlacement = new AdPlacement__c();
        adPlacement.Name = adPlacementName;
        adPlacement.Platform__c = platformId;

        return adPlacement;
    }
}