src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote Sent</fullName>
                </value>
                <value>
                    <fullName>Active Client</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Media_Process_Type__c</fullName>
        <label>Media Process Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Managed Service YouTube</fullName>
                </value>
                <value>
                    <fullName>Managed Service Social</fullName>
                </value>
                <value>
                    <fullName>Self Serve DBM YouTube</fullName>
                </value>
                <value>
                    <fullName>Self Serve Adwords YouTube</fullName>
                </value>
                <value>
                    <fullName>Self Serve Social</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outreach_Stage__c</fullName>
        <label>Contact Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Client</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Approaching</fullName>
                </value>
                <value>
                    <fullName>Bad Contact Info</fullName>
                </value>
                <value>
                    <fullName>Cold / Not Started</fullName>
                </value>
                <value>
                    <fullName>Discovery Meeting</fullName>
                </value>
                <value>
                    <fullName>Do Not Contact</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
                <value>
                    <fullName>Inactive Client</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>No Longer At Company</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                </value>
                <value>
                    <fullName>Nurture</fullName>
                </value>
                <value>
                    <fullName>Referral Source</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Validating Benefits</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Wrong Timing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Pre-Meeting</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>In-House/Self-Serve</fullName>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contact_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Contact_Opportunities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Evaluator</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Negative Influencer</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                    <isActive>false</isActive>
                    <label>Business User</label>
                </value>
                <value>
                    <fullName>Economic Buyer</fullName>
                    <isActive>false</isActive>
                    <label>Economic Buyer</label>
                </value>
                <value>
                    <fullName>Economic Decision Maker</fullName>
                    <isActive>false</isActive>
                    <label>Economic Decision Maker</label>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                    <isActive>false</isActive>
                    <label>Executive Sponsor</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Technical Buyer</fullName>
                    <isActive>false</isActive>
                    <label>Technical Buyer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <label>Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Opportunity Contact</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Contact Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Media_Process_Type__c</fullName>
        <label>Media Process Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Managed Service YouTube</fullName>
                </value>
                <value>
                    <fullName>Managed Service Social</fullName>
                </value>
                <value>
                    <fullName>Self Serve DBM YouTube</fullName>
                </value>
                <value>
                    <fullName>Self Serve Social</fullName>
                </value>
                <value>
                    <fullName>Self Serve Adwords YouTube</fullName>
                    <isActive>false</isActive>
                    <label>Self Serve Adwords YouTube</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MeetingStatus__c</fullName>
        <label>Meeting Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Short-Term Follow Up</fullName>
                </value>
                <value>
                    <fullName>Long-Term Follow Up</fullName>
                </value>
                <value>
                    <fullName>In-House/Self-Serve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContactOpportunityHandler.cls
public class ContactOpportunityHandler {

    public static final String CLOSED_WON = 'Closed Won';
    @TestVisible private static final String VALIDATING_BENEFITS = 'Validating Benefits';
    @TestVisible private static final String EVALUATION = 'Evaluation';
    @TestVisible private static final String DISCOVERY_CALL = 'Discovery Call';
    @TestVisible private static final String DISCOVERY_MEETING = 'Discovery Meeting';
    @TestVisible private static final String ACTIVE_CLIENT = 'Active Client';

    public static void setUniqueID(List<Contact_Opportunity__c> cos) {
        for (Contact_Opportunity__c co: cos) {
            co.Unique_ID__c = co.Contact__c+'#'+co.Opportunity__c;
        }
    }

    public static void replicateOpportunityStatus(Map<Id,Opportunity> opportunities) {
        // 1) the following below happens to all type of Opps
        Map<Id, Contact_Opportunity__c> contactOpps = new Map<Id, Contact_Opportunity__c>([
            SELECT Id, Opportunity__c, Contact__c, Opportunity__r.AccountId, Opportunity__r.RecordTypeId
            FROM Contact_Opportunity__c
            WHERE Opportunity__c IN :opportunities.keySet()
        ]);

        Map<Id, Contact> contactsByContactOpportunity = new Map<Id,Contact>([
            SELECT Id, Outreach_Stage__c, Status__c, AccountId
            FROM Contact
            WHERE Id IN (SELECT Contact__c FROM Contact_Opportunity__c WHERE Id IN :contactOpps.keySet())
        ]);

        Map<Id, Opportunity> opportunitiesMap = new Map<Id, Opportunity>(opportunities);
        for (Contact_Opportunity__c contactOpp :contactOpps.values()) {
            Contact relatedContact = contactsByContactOpportunity.get(contactOpp.Contact__c);
            if (relatedContact == null) {
                continue;
            }

            // Update Media_Process_Type__c field on Contact record
            String mediaProcess = opportunitiesMap.get(contactOpp.Opportunity__c).Media_Process_Type__c;
            if (mediaProcess != null) {
                relatedContact.Media_Process_Type__c = mediaProcess;
            }

            // Update Outreach_Stage__c field on Contact record
            String oppStage = opportunitiesMap.get(contactOpp.Opportunity__c).StageName;
            if (String.isNotBlank(oppStage)) {
                if (oppStage == DISCOVERY_CALL && relatedContact.Outreach_Stage__c != ACTIVE_CLIENT) {
                    relatedContact.Outreach_Stage__c = DISCOVERY_MEETING;
                } else if (oppStage == EVALUATION && relatedContact.Outreach_Stage__c != ACTIVE_CLIENT) {
                    relatedContact.Outreach_Stage__c = EVALUATION;
                } else if (oppStage == VALIDATING_BENEFITS && relatedContact.Outreach_Stage__c != ACTIVE_CLIENT) {
                    relatedContact.Outreach_Stage__c = VALIDATING_BENEFITS;
                } else if (oppStage == CLOSED_WON) {
                    relatedContact.Outreach_Stage__c = ACTIVE_CLIENT;
                }
            }
        }
        // add changed contacts
        Map<Id,Contact> contactsToUpdateMap = new Map<Id, Contact>(contactsByContactOpportunity);

        // 2) the following below happens to CLOSED_WON type of Opp
        Set<Id> accountIdsByClosedWonOpp = new Set<Id>();
        for (Opportunity opp :opportunities.values()) {
            if (opp.StageName == CLOSED_WON) {
                accountIdsByClosedWonOpp.add(opp.AccountId);
            }
        }
        for (Account accByOpp :[SELECT Id, (SELECT Id, Outreach_Stage__c FROM Contacts) FROM Account WHERE Id IN: accountIdsByClosedWonOpp AND RecordTypeId = :AccountHandler.RT_ID_BRAND_DIRECT]) {
            for (Contact relatedContact :accByOpp.Contacts) {
                // if Account related to Closed Won has more than one Contact, then
                // all Contacts are being updated
                relatedContact.Outreach_Stage__c = ACTIVE_CLIENT;
                contactsToUpdateMap.put(relatedContact.Id, relatedContact);
            }
        }

        // update Contact for 1,2 cases
        update contactsToUpdateMap.values();
    }

    public static void setContactStatus(List<Contact_Opportunity__c> cos) {
        Set<Id> oppIds = getOppIds(cos);
        replicateOpportunityStatus(new Map<Id, Opportunity>([
            SELECT Id, StageName, MeetingStatus__c, Media_Process_Type__c, AccountId
            FROM Opportunity
            WHERE Id IN :oppIds
        ]));
    }

    public static void createOpportunityContactRoles(List<Contact_Opportunity__c> cos) {
        Set<Id> oppIds = getOppIds(cos);
        delete [SELECT Id FROM OpportunityContactRole WHERE OpportunityId IN :oppIds];

        List<OpportunityContactRole> roles = new List<OpportunityContactRole>();
        List<Opportunity> opportunities = [
            SELECT Id, (SELECT Id, OpportunityId, ContactId, Role FROM OpportunityContactRoles),
                (SELECT Id, Unique_ID__c, Role__c, Contact__c, Opportunity__c FROM Contact_Opportunities__r)
            FROM Opportunity
            WHERE Id IN :oppIds
        ];

        for (Opportunity opp :opportunities) {
            for (Contact_Opportunity__c co :opp.Contact_Opportunities__r) {
                roles.add(new OpportunityContactRole(
                    OpportunityId = co.Opportunity__c,
                    ContactId = co.Contact__c,
                    Role = co.Role__c
                ));
            }
        }
        insert roles;
    }

    public static void deleteOpportunityContactRoles(List<Contact_Opportunity__c> cos) {
        Set<Id> oppIds = getOppIds(cos);
        List<OpportunityContactRole> rolesToDelete = new List<OpportunityContactRole>();
        for(OpportunityContactRole role :[SELECT OpportunityId, ContactId FROM OpportunityContactRole WHERE OpportunityId IN :oppIds]) {
            for (Contact_Opportunity__c co: cos){
                if (co.Opportunity__c == role.OpportunityId && co.Contact__c==role.ContactId) {
                    rolesToDelete.add(role);
                }
            }
        }
        delete rolesToDelete;
    }

    private static Set<Id> getOppIds(List<Contact_Opportunity__c> cos) {
        Set<Id> oppIds = new Set<Id>();
        for (Contact_Opportunity__c co :cos) {
            oppIds.add(co.Opportunity__c);
        }
        return oppIds;
    }

}