src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote Sent</fullName>
                </value>
                <value>
                    <fullName>Active Client</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CreditNote__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>XeroStatus__c</fullName>
        <label>Xero Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreditNotesNotificationCtrlTest.cls
@isTest
private class CreditNotesNotificationCtrlTest {

    static testMethod void willDisplayPendingCreditNotes() 
    {
        Account acc = TestHelper.createAccount();
        Project__c contract = TestHelper.createContract(acc.Id);
        
        Sub_Project__c payment = [SELECT Id FROM Sub_Project__c WHERE Project__c = :contract.Id LIMIT 1];
        payment.XeroStatus__c = SubProject.XERO_STATUS_SUBMITTED;
        update payment;
        
        CreditNote__c creditNotePending = TestHelper.createCreditNoteNoInsert(payment.Id);         
        CreditNote__c creditNoteApproved = TestHelper.createCreditNoteNoInsert(payment.Id);
        creditNotePending.Status__c = CreditNote.STATUS_SUBMITTED;
        creditNoteApproved.Status__c = CreditNote.STATUS_AUTHORISED;
        
        insert new List<CreditNote__c> { creditNotePending, creditNoteApproved };
        
        test.startTest();
        
            CreditNotesNotificationCtrl ctrl = new CreditNotesNotificationCtrl();
        
        test.stopTest();
        
        System.assertEquals(1, ctrl.creditNotes.size());
        System.assertEquals(1, ctrl.payments.size());
    }
}