src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ContractsClientSpend__c</fullName>
        <label>Contracts Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Natural_Name__c</fullName>
        <label>Natural Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Brand_Direct</fullName>
        <active>true</active>
        <label>Brand Direct</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand_Account__c.object
<CustomObject>
    <description>junction between brand and account</description>
    <fields>
        <fullName>Accounts__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brand_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Brand_Account__c</fullName>
        <formula>Brand__r.Name  &amp;&quot; / &quot;&amp;   Accounts__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand/Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Brand_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>ClientSince__c</fullName>
        <inlineHelpText>Start Date of customer&apos;s first campaign</inlineHelpText>
        <label>Client Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContractsClientSpend__c</fullName>
        <label>Contracts Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LastContractEndDate__c</fullName>
        <label>Last Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NoOfContracts__c</fullName>
        <label>No of Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpenOpportunities__c</fullName>
        <label>Open Opportunities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Brand/Account</label>
    <nameField>
        <label>Brand/Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand/Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BrandRelationshipHistoryCtrl.cls
public with sharing class BrandRelationshipHistoryCtrl {
    public Account acc { get;set; }
    public List<Brand_Account__c> brandAccounts { get {
        if (brandAccounts == null) brandAccounts = new List<Brand_Account__c>();
        return brandAccounts;
    } set; }
    public String retUrl { get; private set;}
    private ApexPages.StandardController stdController;

    @testVisible private static Id brandDirectRTId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Brand_Direct'].Id;

    public BrandRelationshipHistoryCtrl (ApexPages.StandardController stdController) {
        this.acc = [SELECT Natural_Name__c, Name, Id, RecordTypeId FROM Account WHERE Id = :stdController.getId()];
        this.stdController = stdController;

        retUrl = stdController.view().getUrl();

        if (this.acc.RecordTypeId == brandDirectRTId) {
            List<Brand_Account__c> relatedBrandAccounts = [SELECT Brand__c, Accounts__c FROM Brand_Account__c WHERE Brand__r.Name = :this.acc.Natural_Name__c];
            // could be more than one record
            Set<Id> brandIds = new Set<Id>();
            for (Brand_Account__c ba :relatedBrandAccounts) {
                brandIds.add(ba.Brand__c);
            }

            brandAccounts = [
                SELECT OpenOpportunities__c, NoOfContracts__c, ContractsClientSpend__c, ClientSince__c, LastContractEndDate__c, Name, Accounts__r.Name, Accounts__r.Natural_Name__c, Accounts__c
                FROM Brand_Account__c
                WHERE Brand__c IN :brandIds
            ];
        }

    }
}