src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote Sent</fullName>
                </value>
                <value>
                    <fullName>Active Client</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Pre-Meeting</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>In-House/Self-Serve</fullName>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contact_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Contact_Opportunities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Evaluator</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Negative Influencer</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                    <isActive>false</isActive>
                    <label>Business User</label>
                </value>
                <value>
                    <fullName>Economic Buyer</fullName>
                    <isActive>false</isActive>
                    <label>Economic Buyer</label>
                </value>
                <value>
                    <fullName>Economic Decision Maker</fullName>
                    <isActive>false</isActive>
                    <label>Economic Decision Maker</label>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                    <isActive>false</isActive>
                    <label>Executive Sponsor</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Technical Buyer</fullName>
                    <isActive>false</isActive>
                    <label>Technical Buyer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Opportunity Contact</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Contact Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewContactOpportunityController_Test.cls
@isTest
private class NewContactOpportunityController_Test {

    testmethod static void addNewContactRole_increaseContactRolesListSize() {
        Account acc = TestHelper.createAccount();
        User usr = TestHelper.createUser();
        Opportunity opp = TestHelper.createOpportunity(usr, acc);
        insert opp;
        Test.setCurrentPage(Page.NewContactOpportunity);
        System.currentPageReference().getParameters().put('id', opp.Id);
        NewContactOpportunityController controller = new
                NewContactOpportunityController(new ApexPages.StandardSetController(new List<Contact_Opportunity__c>()));
        System.assertEquals(1, controller.contactRoles.size());

        Test.startTest();
        controller.addNewContactRole();
        Test.stopTest();

        System.assertEquals(2, controller.contactRoles.size());
    }

    testmethod static void deleteContactRole_decreaseContactRolesListSize() {
        Account acc = TestHelper.createAccount();
        User usr = TestHelper.createUser();
        Opportunity opp = TestHelper.createOpportunity(usr, acc);
        insert opp;
        Test.setCurrentPage(Page.NewContactOpportunity);
        System.currentPageReference().getParameters().put('id', opp.Id);
        NewContactOpportunityController controller = new
                NewContactOpportunityController(new ApexPages.StandardSetController(new List<Contact_Opportunity__c>()));
        controller.contactRoleRow = 0;

        Test.startTest();
        controller.deleteContactRole();
        Test.stopTest();

        System.assertEquals(0, controller.contactRoles.size());
    }

    testmethod static void save_insertContactRole() {
        Account acc = TestHelper.createAccount();
        User usr = TestHelper.createUser();
        Opportunity opp = TestHelper.createOpportunity(usr, acc);
        insert opp;
        Test.setCurrentPage(Page.NewContactOpportunity);
        System.currentPageReference().getParameters().put('id', opp.Id);
        NewContactOpportunityController controller = new
                NewContactOpportunityController(new ApexPages.StandardSetController(new List<Contact_Opportunity__c>()));
        Contact con = new Contact(LastName = 'TestCon', Status__c = 'Open', MailingCity = 'Test', MailingState = 'Test', MailingCountry = 'Test');
        insert con;

        Test.startTest();
        controller.contactRoles[0].Contact__c = con.Id;
        controller.contactRoles[0].Role__c = 'Decision Maker';
        controller.save();
        Test.stopTest();

        System.assertEquals(1, [
                SELECT count()
                FROM Contact_Opportunity__c
                WHERE Contact__c = :con.Id AND
                Opportunity__c = :opp.Id AND Role__c = 'Decision Maker'
        ]);
    }

    testmethod static void save_returnToOpportunity() {
        Account acc = TestHelper.createAccount();
        User usr = TestHelper.createUser();
        Opportunity opp = TestHelper.createOpportunity(usr, acc);
        insert opp;
        Test.setCurrentPage(Page.NewContactOpportunity);
        System.currentPageReference().getParameters().put('id', opp.Id);
        NewContactOpportunityController controller = new
                NewContactOpportunityController(new ApexPages.StandardSetController(new List<Contact_Opportunity__c>()));
        Contact con = new Contact(LastName = 'TestCon', Status__c = 'Open', MailingCity = 'Test', MailingState = 'Test', MailingCountry = 'Test');
        insert con;

        Test.startTest();
        PageReference result = controller.save();
        Test.stopTest();

        PageReference expected = new PageReference('/' + opp.Id);
        System.assertEquals(expected.getUrl(), result.getUrl());
    }
}