src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <description>Store Contact Id from Xero</description>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Technical Issues</fullName>
                </value>
                <value>
                    <fullName>No response</fullName>
                </value>
                <value>
                    <fullName>Not a fit</fullName>
                </value>
                <value>
                    <fullName>Not interested</fullName>
                </value>
                <value>
                    <fullName>Using competitor</fullName>
                </value>
                <value>
                    <fullName>Using Google</fullName>
                </value>
                <value>
                    <fullName>Contact left</fullName>
                </value>
                <value>
                    <fullName>Wrong Contact/Team</fullName>
                </value>
                <value>
                    <fullName>Lost to Competitor</fullName>
                </value>
                <value>
                    <fullName>Lost to Google</fullName>
                </value>
                <value>
                    <fullName>Campaign Cancelled</fullName>
                </value>
                <value>
                    <fullName>No Approval</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <label>Xero ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <externalId>true</externalId>
        <label>Xero ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PodDashboardCtrlTest.cls
@isTest
private class PodDashboardCtrlTest {
    
    static testMethod void willDisplayLiveContracts() {
        User clientServicesUser = TestHelper.createClientServiceUser();
        
        Account acc = TestHelper.createAccount();
        
        Project__c runningContract = TestHelper.createContractNoInsert(acc.Id, 'testRunningContract', NULL);
        runningContract.Start_Date__c = System.today().addMonths(-1);
        runningContract.End_Date__c = System.today().addMonths(1);
        runningContract.ClientServicesRep__c = clientServicesUser.Id;
        
        Project__c pastContract = TestHelper.createContractNoInsert(acc.Id, 'testPastContract', NULL);
        pastContract.Start_Date__c = System.today().addMonths(-2);
        pastContract.End_Date__c = System.today().addMonths(-1);
        pastContract.ClientServicesRep__c = clientServicesUser.Id;
        insert new List<Project__c>{runningContract, pastContract};

        Test.startTest();
        System.runAs(clientServicesUser) {
            List<PodDashboardCtrl.ClientWrapper> clients = PodDashboardCtrl.getClients(10, 0, '');
            PodDashboardCtrl.ClientWrapper contracts = PodDashboardCtrl.readContracts(clients[0].client.Id);
            
            List<Project__c> myContracts = PodDashboardCtrl.readMyContracts(10, 0, '');
            System.assertEquals(1, clients.size());
            System.assertEquals(true, clients[0].isActive);
            // System.assertEquals(1, contracts.contracts.size()); // TODO: findout why the result is incorrect
            System.assertEquals(1, myContracts.size());
        }
        Test.stopTest();
    }
    
    static testMethod void willDisplayMyOpportunities()
    {
        User clientServicesUser = TestHelper.createClientServiceUser();
        
        Account acc = TestHelper.createAccount();
        
        Opportunity openOpportunity = TestHelper.createOpportunity(clientServicesUser, acc);
        openOpportunity.ClientServicesRep__c = clientServicesUser.Id;
        
        Opportunity lostOpportunity = TestHelper.createOpportunity(clientServicesUser, acc);
        lostOpportunity.ClientServicesRep__c = clientServicesUser.Id;
        lostOpportunity.StageName = 'Closed Lost';
        lostOpportunity.Closed_Lost_Reason__c = 'Lost to Competitor';
        
        insert new List<Opportunity> { openOpportunity, lostOpportunity };
        
        system.runAs(clientServicesUser)  
        { 
            test.startTest();
            
            List<Opportunity> MyOpportunities = PodDashboardCtrl.readMyOpportunities(10, 0, '');
            
            test.stopTest();
            
            System.assertEquals(1, MyOpportunities.size());
        }  
    }
    
    static testMethod void willDisplayAwaitingPayments()
    {
        User clientServicesUser = TestHelper.createClientServiceUser();
        
        Account acc = TestHelper.createAccount();
        
        Project__c contract = TestHelper.createContractNoInsert(acc.Id, 'testContract', NULL);
        contract.Start_Date__c = System.today().addMonths(-3);
        contract.End_Date__c = System.today().addMonths(1);
        contract.ClientServicesRep__c = clientServicesUser.Id;
        insert contract;
        
        List<Sub_Project__c> payments = [SELECT Id FROM Sub_Project__c WHERE Project__c = :contract.Id ORDER BY End_Date__c];
        
        System.assertEquals(5, payments.size());
        
        payments[0].Xero_Id__c = 'testXeroId';
        update payments;
        
        system.runAs(clientServicesUser)  
        { 
            test.startTest();
            
            Map<Id, Sub_Project__c> awaitingPayments = new Map<Id, Sub_Project__c>(PodDashboardCtrl.readAwaitingPayments(10, 0, ''));
            
            test.stopTest();
           
            System.assert(!awaitingPayments.isEmpty());
            System.assert(awaitingPayments.size() <= 2);
            System.assert(!awaitingPayments.containsKey(payments[0].Id));
            System.assert(awaitingPayments.containsKey(payments[1].Id));
        }  
    }
}