src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <description>Store Contact Id from Xero</description>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Entity</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <externalId>true</externalId>
        <label>Xero Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>TEXT(Project__r.Account_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Profile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdWordsSpend__c</fullName>
        <label>Media Spend</label>
        <summarizedField>Project_Media_Spend__c.Amount__c</summarizedField>
        <summaryForeignKey>Project_Media_Spend__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Margin_Type__c</fullName>
        <label>Margin Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Budget</fullName>
                    <default>true</default>
                    <label>% of Budget</label>
                </value>
                <value>
                    <fullName>% of Media</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <formula>IF(ISPICKVAL(Margin_Type__c,&apos;% of Media&apos;),
   Client_Spend__c / (1+Margin__c),
   Client_Spend__c * (1-Margin__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentType__c</fullName>
        <formula>TEXT(Project__r.Payment_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <formula>IF(ISBLANK(OpportunityPlatform__c), Payment__r.Project__r.Project_ID__c, OpportunityPlatform__r.Platform__r.Prefix__c + Payment__r.Project__r.Project_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Billing Profile</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strike</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AddXeroTax__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add VAT/GST Tax</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_IO__c</fullName>
        <label>IO #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Margin__c</fullName>
        <formula>IF(AND(Client_Spend__c != 0, Invoices_for_Processing__c = 0), 
ActualGrossProfit__c / Client_Spend__c, 
NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Margin_Type__c</fullName>
        <label>Margin Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Budget</fullName>
                    <default>true</default>
                    <label>% of Budget</label>
                </value>
                <value>
                    <fullName>% of Media</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <formula>IF(ISPICKVAL(Margin_Type__c,&apos;% of Media&apos;),
Client_Spend__c / (1+Margin__c),
Client_Spend__c * (1-Margin__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <label>Xero ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Billing Profile</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Maker</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Strike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sub_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdWordsSpend__c</fullName>
        <label>Media Spend</label>
        <summarizedField>Payment__c.AdWordsSpend__c</summarizedField>
        <summaryForeignKey>Payment__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Margin__c</fullName>
        <formula>if(and(Client_Spend__c &lt;&gt; 0, 
       or(Checked__c, Synced_with_Xero__c, !ispickval(XeroStatus__c,&quot;&quot;)
          )
        ), 
Gross_Profit_Report__c / Client_Spend__c, 
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Margin_Type__c</fullName>
        <label>Margin Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Budget</fullName>
                    <default>true</default>
                    <label>% of Budget</label>
                </value>
                <value>
                    <fullName>% of Media</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <formula>IF(ISPICKVAL(Margin_Type__c,&apos;% of Media&apos;),
   Client_Spend__c / (1+Margin__c),
   Client_Spend__c * (1-Margin__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <formula>Project__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <externalId>true</externalId>
        <label>Xero ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubProjectRepository.cls
public class SubProjectRepository {

    public static final String API_NAME = Schema.Sub_Project__c.SObjectType.getDescribe().getName();

    public static List<Sub_Project__c> getPaymentsByContractId(Id contractId) {
        return [
            SELECT Id, Project__c, End_Date__c, Start_Date__c, Client_Spend__c
            FROM Sub_Project__c
            WHERE Project__c = :contractId
        ];
    }

    public static List<Sub_Project__c> getInvoiceForXeroSubmission(String invoiceId) {
        return [
            SELECT Id, Name, Account__c, Account__r.Name, Account__r.Xero_Id__c, Account_Type__c, Account__r.Xero_Entity__c,
                AdWordsSpend__c, CurrencyIsoCode, Final_Margin__c, Invoice__c, Project__r.Margin__c, Margin_Type__c, Media_Order__c,
                Project__c, Project__r.AddXeroTax__c, Project__r.Name, Project__r.Xero_Id__c, Xero_Id__c, RecordType.DeveloperName,
                End_Date__c, Project__r.Account_Type__c, ProjectId__c, Project__r.Client_IO__c, Project__r.Start_Date__c,
                Project__r.End_Date__c, Project__r.PO__c, Start_Date__c, Invoice_Amount__c, PaymentType__c, Project__r.Xero_Entity__c,
                Project__r.Account__r.InvoiceLayout__c, Project__r.Custom_Xero_Campaign_Name__c
            FROM Sub_Project__c
            WHERE Id = :invoiceId
        ];
    }

    public static List<Sub_Project__c> getUnpaidPaymentsByXeroIds(Set<String> xeroIds) {
        return [SELECT Id, Xero_Id__c, XeroStatus__c FROM Sub_Project__c WHERE Xero_Id__c IN :xeroIds AND Paid__c = FALSE];
    }

    public static List<Sub_Project__c> getPaymentsWithProjects(List<Sub_Project__c> payments) {
        Set<Id> paymentIds = (new Map<Id,Sub_Project__c>(payments)).keySet();
        return getPaymentsByIDsWithProjects(paymentIds);
    }

    public static List<Sub_Project__c> getPaymentsByIDsWithProjects(Set<Id> Ids) {
        return [
            SELECT Id, Client_Spend__c, End_Date__c, Start_Date__c, Project__r.Gaps_Exist_Between_Projects__c,
                (SELECT Id, Client_Spend__c, Start_Date__c, End_Date__c, CostStructure__c, StrikeId__c, OpportunityPlatform__r.Platform__r.Name FROM Projects__r)
            FROM Sub_Project__c
            WHERE Id IN :Ids
        ];
    }

    public static Map<Id, List<Sub_Project__c>> getPaymentsForNotification(Set<Id> clientServiceIds) {
        Map<Id, List<Sub_Project__c>> paymentsForCSRep = new Map<Id, List<Sub_Project__c>>();
        List<Sub_Project__c> payments = [
            SELECT Id, Name, Project__c, Project__r.Name, Project__r.ClientServicesRep__c, Project__r.ClientServicesRep__r.Name
            FROM Sub_Project__c
            WHERE MediaSpendAssigned__c = true
                AND InvoiceNotificationSent__c = false
                AND InvoicingLocked__c = false AND Xero_Id__c = NULL
                AND Project__r.ClientServicesRep__c IN :clientServiceIds
            ORDER BY Project__r.Name
        ];

        for (Sub_Project__c payment :payments) {
            String key = payment.Project__r.ClientServicesRep__c;
            if (!paymentsForCSRep.containsKey(key)) {
                paymentsForCSRep.put(payment.Project__r.ClientServicesRep__c, new List<Sub_Project__c>());
            }
            paymentsForCSRep.get(payment.Project__r.ClientServicesRep__c).add(payment);
        }

        return paymentsForCSRep;
    }

    public static List<Sub_Project__c> getPaymentsSubmittedToXero() {
        return [
            SELECT Id, Name, Invoice__c, Xero_ID__c, Xero_Invoice__c, Project__r.Name
            FROM Sub_Project__c
            WHERE XeroStatus__c = :SubProject.XERO_STATUS_SUBMITTED
            ORDER BY Name
        ];
    }

    public static List<Sub_Project__c> getSubProjectsByIDs(Set<Id> subProjectIDs) {
        return [
            SELECT Name, Start_Date__c, End_Date__c, Client_Spend__c, AdWordsSpend__c, Delivered__c, Margin__c, Invoice_Amount__c, ActualGrossProfitCopy__c,
                    Actual_Gross_Profit_Social_Rollup__c, Actual_Gross_Profit_YT_Rollup__c, Gross_Profit_Report__c
            FROM Sub_Project__c
            WHERE Id IN :subProjectIDs
        ];
    }

}