src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote Sent</fullName>
                </value>
                <value>
                    <fullName>Active Client</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <description>Store Contact Id from Xero</description>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CreditNote__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Revised Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>XeroId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Xero Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <label>Xero ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <externalId>true</externalId>
        <label>Xero ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XeroSettings__c.object
<CustomObject>
    <label>Xero Settings</label>
    <nameField>
        <label>XeroSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreditNoteEditCtrlTest.cls
@IsTest
public class CreditNoteEditCtrlTest {

    @IsTest static void testSendCreditNote() {
        xeroSettings__c xs = TestHelper.createXeroEntity();
        Project__c contract = TestHelper.createContract(TestHelper.createAccount().Id); 
        contract.Xero_Entity__c = xs.Id;
        
        Sub_Project__c payment = [SELECT Id, Project__c FROM Sub_Project__c LIMIT 1];
        payment.Xero_Id__c ='TESTXEROID1234';
        update payment;
        update contract;

        CreditNote__c creditNoteObj = TestHelper.createCreditNoteNoInsert(payment.Id);
        creditNoteObj.XeroId__c = '';
        creditNoteObj.Status__c = '';
        insert creditNoteObj;
        
        Test.startTest();
        XeroWrappers.XeroCreditNote xeroCreditNote = XeroTestHelper.createXeroCreditNote(CreditNoteRepository.getCreditNoteById(creditNoteObj.Id));
        xeroCreditNote.CreditNoteId = 'testCreditNoteXeroId';
        xeroCreditNote.Status = XeroWrappers.XeroCreditNoteStatus.SUBMITTED;

        XeroTestHelper.xeroCreditNotes.add(xeroCreditNote);

        Test.setMock(HttpCalloutMock.class, new XeroMockUpResponseGenerator());

        ApexPages.StandardController stdController = new ApexPages.StandardController(creditNoteObj);
        CreditNoteEditCtrl controller = new CreditNoteEditCtrl(stdController);
        controller.sendCreditNote();
        Test.stopTest();
        
        creditNoteObj = [SELECT Status__c, XeroId__c FROM CreditNote__c WHERE Id = :creditNoteObj.Id];
        System.assertEquals(xeroCreditNote.CreditNoteId, creditNoteObj.XeroId__c);
        System.assertEquals(CreditNote.STATUS_SUBMITTED, creditNoteObj.Status__c);
    }

    @IsTest static void testSaveCreditNote() {
        Account acc = TestHelper.createAccount();
        Project__c contract = TestHelper.createContract(acc.Id);
        
        Sub_Project__c payment = [SELECT Id FROM Sub_Project__c LIMIT 1];
        
        Test.startTest();
        System.assertEquals(0, [SELECT Id FROM CreditNote__c].size());
        PageReference pageRef = Page.CreditNoteEdit;
        ApexPages.currentPage().getParameters().put('paymentId', payment.Id);
        CreditNote__c creditNoteObj = new CreditNote__c();

        CreditNoteEditCtrl controller = new CreditNoteEditCtrl(new ApexPages.StandardController(creditNoteObj));
        controller.creditNote.Description__c = 'Description';
        controller.creditNote.Amount__c = 100;
        controller.saveCreditNote();
		Test.stopTest();
        
        System.assertEquals(100, [SELECT Amount__c FROM CreditNote__c LIMIT 1].Amount__c);
    }
}