src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Stage__c</fullName>
        <label>Account Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Do Not Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SCH_BATCH_AccountStageSetter.cls
public class SCH_BATCH_AccountStageSetter implements Database.Batchable <sObject>, Database.stateful, Schedulable {

    private static final String STATUS_OPEN = 'Open';
    private static final String STATUS_WORKING = 'Working';
    private static final String STATUS_MEETING = 'Meeting';
    private static final String STATUS_CLIENT = 'Client';
    private static final String STATUS_DO_NOT_CONTACT = 'Do Not Contact';
    
    public void execute(SchedulableContext ctx) 
    {        
        Database.executeBatch(new SCH_BATCH_AccountStageSetter(), 200);
    }   
    
    public Database.Querylocator start(Database.BatchableContext bc)
    {      
        return Database.getQuerylocator([SELECT Id, Account_Stage__c, LastActivityDate,
            (SELECT Id, ActivityDate FROM Tasks WHERE ActivityDate!=null ORDER BY ActivityDate DESC LIMIT 1), 
            (SELECT Id, ActivityDateTime FROM Events WHERE ActivityDateTime!=null ORDER BY ActivityDateTime DESC LIMIT 1), 
            (SELECT id, end_Date__c from projects__r order by end_date__c desc LIMIT 1),                             
            (SELECT ID, CloseDate From Opportunities WHERE isClosed=false ORDER BY CloseDate DESC LIMIT 1) 
            FROM Account WHERE Account_Stage__c!=:STATUS_DO_NOT_CONTACT]);
    } 
    
    public void execute(Database.BatchableContext bc, List<Account> scope)
    {
        for(Account acc: scope) {
            if(acc.projects__r.size()>0 && acc.projects__r[0].End_Date__c>= Date.today().addDays(-365)) acc.Account_Stage__c=STATUS_CLIENT;
			else if(acc.Opportunities.size()>0 || (acc.Events.size()>0 && acc.Events[0].ActivityDateTime > Date.today().addDays(-120))) acc.Account_Stage__c=STATUS_MEETING;
            else if((acc.Tasks.size()>0 && acc.Tasks[0].ActivityDate >= Date.today().addDays(-60))
                    || (acc.LastActivityDate!=null && acc.LastActivityDate>= Date.today().addDays(-60))) acc.Account_Stage__c=STATUS_WORKING;
            else acc.Account_Stage__c=STATUS_OPEN;
        }
        database.update(scope,false);
    }    
    
    public void finish(Database.BatchableContext bc)
    {
    }         
}