src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote Sent</fullName>
                </value>
                <value>
                    <fullName>Active Client</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <description>Store Contact Id from Xero</description>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CreditNote__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Revised Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Credit Notes</relationshipLabel>
        <relationshipName>CreditNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>XeroAmount__c</fullName>
        <label>Xero Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>XeroCreditNote__c</fullName>
        <formula>IF(!ISBLANK(XeroId__c), 
   HYPERLINK(&quot;https://go.xero.com/AccountsReceivable/EditCreditNote.aspx?creditNoteID=&quot; &amp; XeroId__c, 
   IF(!ISBLANK(XeroNumber__c), XeroNumber__c, &quot;View&quot;)), 
&quot;Not Available&quot;)</formula>
        <label>Xero Credit Note</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XeroEntity__c</fullName>
        <formula>IF(ISBLANK(Payment__r.Project__r.Xero_Entity__c), Payment__r.Account__r.Xero_Entity__c, Payment__r.Project__r.Xero_Entity__c)</formula>
        <label>Xero Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XeroId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Xero Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>XeroNumber__c</fullName>
        <label>Xero Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <label>Xero ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sub_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <externalId>true</externalId>
        <label>Xero ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XeroEntity__c.object
<CustomObject>
    <fields>
        <fullName>XeroId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Xero Entity</label>
    <nameField>
        <displayFormat>XE-{0000}</displayFormat>
        <label>Xero Entity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XeroSettings__c.object
<CustomObject>
    <fields>
        <fullName>AccountCode__c</fullName>
        <label>Account Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Xero Settings</label>
    <nameField>
        <label>XeroSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreditNoteRepository.cls
public class CreditNoteRepository {
    
    public static CreditNote__c getCreditNoteById(String creditNoteId) {
        List<CreditNote__c> creditNotes = getCreditNotesById(new Set<Id>{creditNoteId});
        return (!creditNotes.isEmpty()) ?  creditNotes[0] : new CreditNote__c();
    }
    
    public static List<CreditNote__c> getCreditNotesById(Set<Id> creditNoteIds) {
        return [SELECT Amount__c, Description__c, Name, XeroEntity__c, Payment__c, Payment__r.Xero_Id__c, XeroId__c, Payment__r.CurrencyIsoCode, 
                       Payment__r.Invoice_Amount__c,
                       Payment__r.Project__r.Xero_Id__c, Payment__r.Project__r.Xero_Entity__c, XeroCreditNote__c,
                       Payment__r.Account__r.Xero_Id__c, Payment__r.Account__r.Xero_Entity__c, XeroAmount__c,
                       Payment__r.Project__r.Xero_Entity__r.AccountCode__c
                FROM CreditNote__c 
                WHERE Id IN :creditNoteIds];        
    }

    public static List<CreditNote__c> getUnpaidCreditNotes(Set<String> xeroIds) {
        return [SELECT XeroId__c, Status__c
            FROM CreditNote__c
            WHERE XeroId__c IN :xeroIds AND Status__c != :CreditNote.STATUS_PAID
        ];
    }
    
    public static List<CreditNote__c> getPendingCreditNotes(Integer offset, Integer pageSize, String orderBy, String orderDirection) {
        return getCreditNotes(CreditNote.STATUS_SUBMITTED, offset, pageSize, orderBy, orderDirection);         
    }
    
    private static List<CreditNote__c> getCreditNotes(String status, Integer offset, Integer pageSize, String orderBy, String orderDirection) {
        String query = 'SELECT Id, Amount__c, Description__c, Name, Payment__c, Payment__r.Name, Payment__r.Project__c, Payment__r.Project__r.Name, Status__c , CreatedBy.Name, XeroCreditNote__c, XeroId__c, XeroNumber__c ';
            query += 'FROM CreditNote__c WHERE Status__c = :status ';
        
        if (String.isNotBlank(orderBy)) {
            query += ' ORDER BY ' + orderBy;          
        }
        if (String.isNotBlank(orderDirection)) {
            query += ' ' + orderDirection;            
        }
        if (pageSize != null) {
            query += ' LIMIT :pageSize ';            
        }
        if (offset != null) {
            query += ' OFFSET :offset ';            
        }
        return Database.query(query);        
    }
}