src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote Sent</fullName>
                </value>
                <value>
                    <fullName>Active Client</fullName>
                </value>
                <value>
                    <fullName>In-House</fullName>
                </value>
                <value>
                    <fullName>Agency</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <description>Store Contact Id from Xero</description>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Pre-Meeting</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>In-House/Self-Serve</fullName>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CreditNote__c.object
<CustomObject>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Credit Notes</relationshipLabel>
        <relationshipName>CreditNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventLog__c.object
<CustomObject>
    <description>Record errors, events</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Event Logs</relationshipLabel>
        <relationshipName>Event_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Event Logs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Log</label>
    <nameField>
        <displayFormat>EventLog-{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Entity</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <externalId>true</externalId>
        <label>Xero Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <label>Xero ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sub_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>XeroStatus__c</fullName>
        <label>Xero Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <externalId>true</externalId>
        <label>Xero ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XeroEntity__c.object
<CustomObject>
    <fields>
        <fullName>ObjectType__c</fullName>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>XeroSettings__c</fullName>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Xero Entities</relationshipLabel>
        <relationshipName>XeroEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Xero Entity</label>
    <nameField>
        <displayFormat>XE-{0000}</displayFormat>
        <label>Xero Entity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XeroSettings__c.object
<CustomObject>
    <fields>
        <fullName>AccountCode__c</fullName>
        <label>Account Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerKey__c</fullName>
        <label>ConsumerKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerSecret__c</fullName>
        <label>ConsumerSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrivateKey__c</fullName>
        <label>PrivateKey</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Xero Settings</label>
    <nameField>
        <label>XeroSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/XeroSync__c.object
<CustomObject>
    <description>Store information about last synchronization of xero entities.</description>
    <fields>
        <fullName>SyncDate__c</fullName>
        <label>Sync Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>XeroSettings__c</fullName>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Xero Syncs</relationshipLabel>
        <relationshipName>XeroSyncs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Xero Sync</label>
    <nameField>
        <displayFormat>XS-{0000}</displayFormat>
        <label>Xero Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Syncs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/XeroSync.cls
global class XeroSync {
    public static final Integer MONTH_COUNT_DIFF = 2;
    public static String XERO_TYPE_CONTACT = 'Contact';
    public static String STATUS_SUCCESS = 'Success';
    public static String STATUS_FAILED = 'Failed';

    public static Boolean performSync = false;


    private static List<XeroSettings__c> xeroSettings { get {
        if (xeroSettings == null) {
            xeroSettings = [SELECT Name, ConsumerKey__c, ConsumerSecret__c, PrivateKey__c, Id, AccountCode__c FROM XeroSettings__c LIMIT 10];
        }
        return xeroSettings;
    } set; }

    public static List<XeroSettings__c> getXeroSettingsByIds(Set<Id> ids) {
        List<XeroSettings__c> xeroSetts = new List<XeroSettings__c>();
        for (XeroSettings__c xeroSett :xeroSettings) {
            if (ids.contains(xeroSett.Id)) {
                xeroSetts.add(xeroSett);
            }
        }
        return xeroSetts;
    }

    public static List<InvoiceWrapper> sendInvoice(String invoiceId) {
        List<Sub_Project__c> payments = SubProjectRepository.getInvoiceForXeroSubmission(invoiceId);

        Map<Id, List<XeroWrappers.XeroInvoice>> xeroToInvoicesMap = new Map<Id, List<XeroWrappers.XeroInvoice>>();
        List<InvoiceWrapper> response = new List<InvoiceWrapper>();
        String contactId;
        Id xeroId;
        try {
            for (Sub_Project__c payment :payments) {
                if (String.isNotBlank(payment.Project__r.Xero_Id__c) && String.isNotBlank(payment.Project__r.Xero_Entity__c)) {
                    contactId = payment.Project__r.Xero_Id__c;
                    xeroId = payment.Project__r.Xero_Entity__c;
                } else {
                    contactId = payment.Account__r.Xero_Id__c;
                    xeroId = payment.Account__r.Xero_Entity__c;
                }
                if (xeroId == null) throw new XeroAPI.XeroException('Xero Id is not defined');

                if (!xeroToInvoicesMap.containsKey(xeroId)) {
                    xeroToInvoicesMap.put(xeroId, new List<XeroWrappers.XeroInvoice>());
                }
                xeroToInvoicesMap.get(xeroId).add(Utility.mapPaymentToInvoice(payment, contactId, xeroId));
            }

            Map<Id, XeroSettings__c> settingsMap = new Map<Id, XeroSettings__c>(getXeroSettingsByIds(xeroToInvoicesMap.keySet()));
            XeroWrappers.XeroInvoiceResponse xir;
            List<XeroWrappers.XeroInvoice> submittedInvoices = new List<XeroWrappers.XeroInvoice>();
            if (!Test.isRunningTest()) {
                for (Id key : xeroToInvoicesMap.keySet()) {
                    xir = XeroAPI.postInvoices(xeroToInvoicesMap.get(key), settingsMap.get(key));
                    if (xir.StatusCode == 200 || xir.StatusCode == 201) {
                        for (XeroWrappers.XeroObject xo : xir.xeroObjects) {
                            submittedInvoices.add((XeroWrappers.XeroInvoice)xo);
                        }
                    } else {
                        System.debug('Error while posting payments: ' + xir);
                    }
                }
            }

            List<Sub_Project__c> paymentsToUpdate = new List<Sub_Project__c>();
            List<EventLog__c> eventLogs = new List<EventLog__c>();
            for (XeroWrappers.XeroInvoice xi: submittedInvoices) {
                if (xi.HasErrors == false) {
                    paymentsToUpdate.add(new Sub_Project__c(
                        Id = invoiceId,
                        Xero_Id__c = xi.InvoiceID,
                        Invoice__c = xi.InvoiceNumber,
                        XeroStatus__c = SubProject.XERO_STATUS_SUBMITTED
                    ));
                    response.add(new InvoiceWrapper(invoiceId, STATUS_SUCCESS, 'Invoice successfully created in Xero'));

                    EventLog__c log = EventLog.createEventLog('Invoice Submitted In Xero', EventLog.STATUS_INFO, EventLog.TYPE_XERO_SYNC);
                    log.Payment__c = invoiceId;
                    eventLogs.add(log);
                } else {
                    response.add(new InvoiceWrapper(invoiceId, STATUS_FAILED, String.join(xi.ValidationErrors, ' ')));
                }
            }

            update paymentsToUpdate;
            insert eventLogs;
        } catch (Exception ex) {
            response = new List<InvoiceWrapper>();
            response.add(new InvoiceWrapper(invoiceId, 'Failed', ex.getMessage()));
            System.debug('### XeroSync.sendInvoice ERROR: ' + ex.getStackTraceString() + '\n');
        }

        return response;
    }

    public static List<InvoiceWrapper> sendCreditNotes(List<Id> creditNoteIds) {
        List<XeroSync.InvoiceWrapper> retVal = new List<XeroSync.InvoiceWrapper>();
        try {
            Map<Id, XeroWrappers.XeroCreditNote> creditNoteResponse = CreditNote.sendCreditNotes(new Set<Id> (creditNoteIds));
            for (Id creditNoteId :creditNoteResponse.keySet()) {
                XeroWrappers.XeroCreditNote creditNote = creditNoteResponse.get(creditNoteId);
                if (!creditNote.ValidationErrors.isEmpty()) {
                     retVal.add(new XeroSync.InvoiceWrapper(creditNoteId, 'Failed', String.join(creditNote.ValidationErrors, ' ')));
                } else {
                     retVal.add(new XeroSync.InvoiceWrapper(creditNoteId, 'Success', 'Credit Note successfully created in Xero'));
                }
            }
        } catch (Exception ex) {
            retVal = new List<XeroSync.InvoiceWrapper>();
            for (Id creditNoteId : creditNoteIds) {
                retVal.add(new XeroSync.InvoiceWrapper(creditNoteId, 'Failed', ex.getMessage()));
            }
        }
        return retVal;
    }

    public static void syncXeroObjects(XeroSettings__c xeroSettings, String objectType) {
        List<XeroSync__c> xeroSync = [
            SELECT SyncDate__c
            FROM XeroSync__c
            WHERE XeroSettings__c = :xeroSettings.Id AND ObjectType__c = :objectType
        ];

        XeroSync__c syncLog;
        if (!xeroSync.isEmpty()) {
            syncLog = xeroSync[0];
            XeroAPI.lastModifiedDate = syncLog.SyncDate__c;
        } else {
            syncLog = new XeroSync__c(ObjectType__c = objectType, XeroSettings__c = xeroSettings.Id);
        }

        XeroWrappers.XeroContactResponse response = XeroAPI.getAllContacts(xeroSettings);
        List<XeroEntity__c> xeroEntities = new List<XeroEntity__c>();
        if (response.StatusCode == 200) {
            for (XeroWrappers.XeroObject obj :response.xeroObjects) {
                XeroWrappers.XeroContact contact = (XeroWrappers.XeroContact) obj;

                xeroEntities.add(new XeroEntity__c(
                    ObjectType__c = objectType,
                    XeroId__c = String.valueOf(contact.ContactID),
                    XeroName__c = String.valueOf(contact.Name),
                    XeroSettings__c = xeroSettings.Id
                ));
            }
            upsert xeroEntities XeroId__c;

            syncLog.SyncDate__c = System.now().addHours(-1);
            upsert syncLog;
        }
    }

    // Invoices
    @Future (Callout=true)
    public static void updateInvoiceFromXero() {
        XeroAPI.lastModifiedDate = System.today();

        Date greaterThanDate = Date.newInstance(
            System.today().addMonths(-1 * MONTH_COUNT_DIFF).year(),
            System.today().addMonths(-1 * MONTH_COUNT_DIFF).month(),
            01
        );

        Map<String, XeroWrappers.XeroInvoice> invoiceFromXero = new Map<String,XeroWrappers.XeroInvoice>();
        List<EventLog__c> logs = new List<EventLog__c>();
        for (XeroSettings__c xeroSetting :xeroSettings) {
            System.debug('### xeroSetting: ' + xeroSetting.Name);

            XeroWrappers.XeroInvoiceResponse response = XeroAPI.getInvoicesGreaterThanDate(xeroSetting, greaterThanDate);
            System.debug('### response: ' + response.statusCode + '   ' + response.xeroObjects.size());
            if (response.statusCode == 200) {
                for (XeroWrappers.XeroObject xo :response.xeroObjects) {
                    System.debug('### xo: ' + xo);
                    XeroWrappers.XeroInvoice invoice = (XeroWrappers.XeroInvoice) xo;
                    invoiceFromXero.put(invoice.invoiceID, invoice);
                }
            } else {
                logs.add(EventLog.createEventLog('Callout Failed', EventLog.STATUS_ERROR, EventLog.TYPE_XERO_SYNC));
            }
        }

        Map<String, Invoice__c> xeroIdToInvoice = new Map<String,Invoice__c>();
        for (Invoice__c invoice :[SELECT Id, Xero_Invoice_Id__c, Status__c FROM Invoice__c WHERE Status__c != 'Paid' AND Xero_Invoice_Id__c != NULL]) {
            xeroIdToInvoice.put(invoice.Xero_Invoice_Id__c, invoice);
        }

        System.debug('### xeroIdToInvoice: ' + xeroIdToInvoice);
        System.debug('### invoiceFromXero: ' + invoiceFromXero);
        List<Invoice__c> invoicesToUpdate = new List<Invoice__c>();
        for (String xeroId :invoiceFromXero.keySet()) {
            XeroWrappers.XeroInvoice xeroInvoice = invoiceFromXero.get(xeroId);
            Invoice__c invoice = xeroIdToInvoice.containsKey(xeroId) ? xeroIdToInvoice.get(xeroId) : null;
            if (invoice == null) {
                continue;
            }

            if (xeroInvoice.Status == XeroWrappers.XeroInvoiceStatus.AUTHORISED) {
                invoice.Status__c = XeroWrappers.XeroInvoiceStatus.AUTHORISED.name();
                invoicesToUpdate.add(invoice);
            }
            if (xeroInvoice.Status == XeroWrappers.XeroInvoiceStatus.PAID) {
                //invoice.Payment_Date__c = xeroInvoice.FullyPaidOnDate
                invoice.Status__c = XeroWrappers.XeroInvoiceStatus.PAID.name();
                invoicesToUpdate.add(invoice);
            }
        }

        System.debug('### invoicesToUpdate: ' + invoicesToUpdate);
        try {
            update invoicesToUpdate;
            insert logs;
        } catch (Exception ex) {
            insert EventLog.createEventLog('Payment Sync failed', EventLog.STATUS_ERROR, EventLog.TYPE_XERO_SYNC, ex.getMessage());
        }
    }

    // Payments
    public static Map<String, XeroWrappers.XeroInvoice> getUpdatedInvoices(XeroSettings__c service) {
        XeroAPI.lastModifiedDate = System.today().addDays(-3);
        Map<String, XeroWrappers.XeroInvoice> invoiceForPayment = new Map<String, XeroWrappers.XeroInvoice>();
        XeroWrappers.XeroInvoiceResponse response = XeroAPI.getAllInvoices(service);
        if (response.StatusCode == 200) {
            for (XeroWrappers.XeroObject obj :response.xeroObjects) {
                XeroWrappers.XeroInvoice invoice = (XeroWrappers.XeroInvoice) obj;
                invoiceForPayment.put(invoice.InvoiceID, invoice);
            }
        } else {
            insert EventLog.createEventLog('Callout failed', EventLog.STATUS_ERROR, EventLog.TYPE_XERO_SYNC);
        }
        return invoiceForPayment;
    }

    public static Map<String, XeroWrappers.XeroInvoice> getUpdatedInvoices() {
        Map<String, XeroWrappers.XeroInvoice> invoiceForPayment = new Map<String, XeroWrappers.XeroInvoice>();
        for (XeroSettings__c xeroSetting :xeroSettings) {
            invoiceForPayment.putAll(getUpdatedInvoices(xeroSetting));
        }
        return invoiceForPayment;
    }

    @Future (Callout=true)
    public static void handleInvoicesFromXero() {
        try {
            Map<String, XeroWrappers.XeroInvoice> invoiceForPayment = getUpdatedInvoices();
            Map<String, Sub_Project__c> xeroIdToPayment = new Map<String, Sub_Project__c>();
            for (Sub_Project__c payment :SubProjectRepository.getUnpaidPaymentsByXeroIds(invoiceForPayment.keySet())) {
                xeroIdToPayment.put(payment.Xero_ID__c, payment);
            }

            List<Sub_Project__c> paymentsToUpdate = new List<Sub_Project__c>();
            List<EventLog__c> logs = new List<EventLog__c>();
            for (String xeroId :invoiceForPayment.keySet()) {
                XeroWrappers.XeroInvoice xeroInvoice = invoiceForPayment.get(xeroId);

                if (xeroInvoice.Status == XeroWrappers.XeroInvoiceStatus.AUTHORISED) {
                    if (xeroIdToPayment.containsKey(xeroId) && xeroIdToPayment.get(xeroId).XeroStatus__c != SubProject.XERO_STATUS_AUTHORISED) {
                        Sub_Project__c payment = xeroIdToPayment.get(xeroId);
                        payment.XeroStatus__c = SubProject.XERO_STATUS_AUTHORISED;
                        paymentsToUpdate.add(payment);

                        logs.add(EventLog.createEventLog('Invoice Approved in Xero', EventLog.STATUS_INFO, EventLog.TYPE_XERO_SYNC, payment.Id));
                    }
                }

                if (xeroInvoice.Status == XeroWrappers.XeroInvoiceStatus.PAID) {
                    if (xeroIdToPayment.containsKey(xeroId) && xeroIdToPayment.get(xeroId).XeroStatus__c != SubProject.XERO_STATUS_PAID) {
                        Sub_Project__c payment = xeroIdToPayment.get(xeroId);
                        payment.Paid__c = true;
                        payment.Payment_Date__c = xeroInvoice.FullyPaidOnDate;
                        payment.XeroStatus__c = SubProject.XERO_STATUS_PAID;
                        paymentsToUpdate.add(payment);

                        logs.add(EventLog.createEventLog('Invoice Paid', EventLog.STATUS_INFO, EventLog.TYPE_XERO_SYNC, payment.Id));
                    }
                }
            }
            update paymentsToUpdate;
            insert logs;
        } catch (Exception ex) {
            insert EventLog.createEventLog('Payment Sync failed', EventLog.STATUS_ERROR, EventLog.TYPE_XERO_SYNC, ex.getMessage());
        }
    }

    // Credit Notes
    @Future (Callout=true)
    public static void updateCreditNotesFromXero() {
        Map<String, XeroWrappers.XeroCreditNote> creditNoteForSalesforceCreditNote = getUpdatedCreditNotes();
        try {
            List<CreditNote__c> creditNotes = CreditNoteRepository.getUnpaidCreditNotes(creditNoteForSalesforceCreditNote.keySet());
            List<EventLog__c> logs = new List<EventLog__c>();
            List<CreditNote__c> creditNotesToUpdate = new List<CreditNote__c>();
            for (CreditNote__c cNote :creditNotes) {
                XeroWrappers.XeroCreditNote xeroCreditNote = creditNoteForSalesforceCreditNote.get(cNote.XeroId__c);

                if (xeroCreditNote.Status == XeroWrappers.XeroCreditNoteStatus.AUTHORISED && cNote.Status__c != CreditNote.STATUS_AUTHORISED) {
                    cNote.Status__c = CreditNote.STATUS_AUTHORISED;
                    logs.add(EventLog.createEventLog('Credit Note Approved in Xero', EventLog.STATUS_INFO, EventLog.TYPE_XERO_SYNC, cNote.Id));
                }

                if (xeroCreditNote.Status == XeroWrappers.XeroCreditNoteStatus.PAID && cNote.Status__c != CreditNote.STATUS_PAID) {
                    cNote.Status__c = CreditNote.STATUS_PAID;
                    if (!xeroCreditNote.LineItems.isEmpty()) {
                        cNote.XeroAmount__c = xeroCreditNote.LineItems[0].LineAmount;
                    }
                    logs.add(EventLog.createEventLog('Credit Note Paid', EventLog.STATUS_INFO, EventLog.TYPE_XERO_SYNC, cNote.Id));
                }
                creditNotesToUpdate.add(cNote);
            }
            update creditNotesToUpdate;
            insert logs;
        } catch (Exception ex) {
            insert EventLog.createEventLog('Credit Note Sync failed', EventLog.STATUS_ERROR, EventLog.TYPE_XERO_SYNC, ex.getMessage());
        }
    }

    public static Map<String, XeroWrappers.XeroCreditNote> getUpdatedCreditNotes() {
        Map<String, XeroWrappers.XeroCreditNote> creditNoteForSalesforceCreditNote = new Map<String, XeroWrappers.XeroCreditNote>();
        for (XeroSettings__c xeroSetting :xeroSettings) {
            creditNoteForSalesforceCreditNote.putAll(getUpdatedCreditNotes(xeroSetting));
        }
        return creditNoteForSalesforceCreditNote;
    }

    public static Map<String, XeroWrappers.XeroCreditNote> getUpdatedCreditNotes(XeroSettings__c service) {
        Map<String, XeroWrappers.XeroCreditNote> creditNoteForSalesforceCreditNote = new Map<String, XeroWrappers.XeroCreditNote>();
        XeroAPI.lastModifiedDate = System.today().addDays(-3);
        XeroWrappers.XeroCreditNoteResponse response = XeroAPI.getAllCreditNotes(service);
        if (response.StatusCode == 200) {
            for (XeroWrappers.XeroCreditNote creditNote : response.xeroCreditNotes) {
                creditNoteForSalesforceCreditNote.put(creditNote.CreditNoteId, creditNote);
            }
        } else {
            insert EventLog.createEventLog('Callout failed', EventLog.STATUS_ERROR, EventLog.TYPE_XERO_SYNC);
        }
        return creditNoteForSalesforceCreditNote;
    }

    global class InvoiceWrapper {
        @AuraEnabled public String Id;
        @AuraEnabled public String status;
        @AuraEnabled public String message;

        public InvoiceWrapper(String Id, String status, String message) {
            this.Id = Id;
            this.status = status;
            this.message = message;
        }
    }
}