src/objects/AdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Ad Placements</relationshipLabel>
        <relationshipName>AdPlacements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ad Placement</label>
    <nameField>
        <label>Ad Placement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cost_Structure_Metric__mdt.object
<CustomObject>
    <fields>
        <fullName>Cost_Structure__c</fullName>
        <label>Cost Structure</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPA</fullName>
                    <default>true</default>
                    <label>CPA</label>
                </value>
                <value>
                    <fullName>CPAC</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPE</fullName>
                </value>
                <value>
                    <fullName>CPER</fullName>
                </value>
                <value>
                    <fullName>CPF</fullName>
                </value>
                <value>
                    <fullName>CPI</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>CPLC</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPPL</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CPSU</fullName>
                </value>
                <value>
                    <fullName>CPV</fullName>
                </value>
                <value>
                    <fullName>CPLP</fullName>
                </value>
                <value>
                    <fullName>CPCO</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>CPDPV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cost Structure Metric</label>
    <pluralLabel>Cost Structure Metrics</pluralLabel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>CostStructure__c</fullName>
        <label>Cost Structure</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPA</fullName>
                </value>
                <value>
                    <fullName>CPAC</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPE</fullName>
                </value>
                <value>
                    <fullName>CPER</fullName>
                </value>
                <value>
                    <fullName>CPF</fullName>
                </value>
                <value>
                    <fullName>CPI</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>CPLC</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPPL</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CPSU</fullName>
                </value>
                <value>
                    <fullName>CPV</fullName>
                </value>
                <value>
                    <fullName>CPLP</fullName>
                </value>
                <value>
                    <fullName>CPCO</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>CPDPV</fullName>
                </value>
                <value>
                    <fullName>CPCV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost_Structure_Metrics__c</fullName>
        <description>Selected Metrics for Cost Structures</description>
        <label>Cost Structure Metrics</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform_Selected__c</fullName>
        <label>Platform Selected</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AdWords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Display Network</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>TikTok</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Platform__c.object
<CustomObject>
    <fields>
        <fullName>CostStructures__c</fullName>
        <label>Cost Structure</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CPA</fullName>
                </value>
                <value>
                    <fullName>CPAC</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPE</fullName>
                </value>
                <value>
                    <fullName>CPER</fullName>
                </value>
                <value>
                    <fullName>CPF</fullName>
                </value>
                <value>
                    <fullName>CPI</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>CPLC</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPPL</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CPSU</fullName>
                </value>
                <value>
                    <fullName>CPV</fullName>
                </value>
                <value>
                    <fullName>CPLP</fullName>
                </value>
                <value>
                    <fullName>CPCO</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>CPDPV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlatformWrapper.cls
public class PlatformWrapper {
    public static final String CC_METRIC_SEPARATOR = ';';

    public Boolean isSelectedInitialValue { get; set; }
    public Boolean isSelected { get; set; }
    public Map<Id, AdPlacementWrapper> adPlacementsMap { get; set; }
    public OpportunityPlatform__c oppPlatform { get; set; }
    
    public String selectedCostStructures { get; set; }
    public Map<String,String> selectedMetrics { get; set; }
    public List<CostStructureWrapper> availableCostStructures { get; set; }

    private static List<Cost_Structure_Metric__mdt> metricsMDT = Platform.METRICS_MDT;

    public PlatformWrapper(Platform__c platform) {
        Set<String> initialCostStructures = new Set<String>();
        adPlacementsMap = new Map<Id, AdPlacementWrapper>();
        availableCostStructures = new List<CostStructureWrapper>();
        
        if (!platform.OpportunityPlatforms__r.isEmpty()) {
            oppPlatform = platform.OpportunityPlatforms__r[0];
            oppPlatform.Platform_Selected__c = platform.Name;
        } else {
            oppPlatform = new OpportunityPlatform__c(Platform__r = platform, Platform__c = platform.Id);
            oppPlatform.Platform_Selected__c = platform.Name;
        }
        
        if (String.isNotBlank(oppPlatform.CostStructure__c)) {
            initialCostStructures = new Set<String>(oppPlatform.CostStructure__c.split(';'));
        }
        
        for (AdPlacement__c adPlacement : platform.AdPlacements__r) {
            adPlacementsMap.put(adPlacement.Id, new AdPlacementWrapper(adPlacement));
        }
        
        if (String.isNotBlank(platform.CostStructures__c)) {
            for (String costStructure : platform.CostStructures__c.split(';')) {
                availableCostStructures.add(new CostStructureWrapper(costStructure, initialCostStructures.contains(costStructure) ? true : false));
            }
        }

        isSelected = false;
        isSelectedInitialValue = false;
        this.oppPlatform = oppPlatform;
        selectedCostStructures = '';

        selectedMetrics = new Map<String,String>();
        for (Schema.PicklistEntry costStructure :OpportunityPlatform__c.CostStructure__c.getDescribe().getPicklistValues()) {
            selectedMetrics.put(costStructure.getLabel(), '');
        }
        if (String.isNotBlank(oppPlatform.Cost_Structure_Metrics__c)) {
            Set<String> metrics = new Set<String>(oppPlatform.Cost_Structure_Metrics__c.split(CC_METRIC_SEPARATOR));
            for (Cost_Structure_Metric__mdt metric :metricsMDT) {
                if (selectedMetrics.containsKey(metric.Cost_Structure__c) && metrics.contains(metric.Label)) {
                    selectedMetrics.put(metric.Cost_Structure__c, metric.Label);
                }
            }
        }
    }
    
    public List<AdPlacementWrapper> getAdPlacements() {
        return adPlacementsMap.values();
    }

    public class CostStructureWrapper {
        public Boolean isSelected { get; set; }
        public String name {get; set;}
        
        public CostStructureWrapper(String name, Boolean isSelected) {
            this.name = name;
            this.isSelected = isSelected;
        }
    }
}