src/objects/AdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Ad Placements</relationshipLabel>
        <relationshipName>AdPlacements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ad Placement</label>
    <nameField>
        <label>Ad Placement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adwords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Reddit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                    <isActive>false</isActive>
                    <label>Instagram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityAdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>ContractAdPlacements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityPlatform__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Opportunity Platform</label>
        <referenceTo>OpportunityPlatform__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Ad Placement</label>
    <nameField>
        <displayFormat>OAP-{0000}</displayFormat>
        <label>Opportunity Ad Placement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>ContractPlatforms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PlatformAccount__c</fullName>
        <label>Platform Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OpportunityPlatform__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Platform</label>
        <referenceTo>OpportunityPlatform__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend_Defined_on_IO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Spend Defined on IO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gaps_Exist_Between_Projects__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gaps Exist Between Projects</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SpendRefreshDate__c</fullName>
        <label>Spend Refresh Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend_Defined_on_IO__c</fullName>
        <formula>Project__r.Client_Spend_Defined_on_IO__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Spend Defined on IO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <formula>HYPERLINK( &apos;https://strike.my.salesforce.com/&apos;&amp;Project__r.Id , Project__r.Name  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VideoUrl__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Video</fullName>
                    <default>true</default>
                    <label>Video</label>
                </value>
                <value>
                    <fullName>Carousel</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Page Post</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsPlaceholder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Placeholder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AdWords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Display Network</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Creative</label>
    <nameField>
        <label>Creative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractCtrlTest.cls
@IsTest
private class ContractCtrlTest {

    @IsTest static void testEditReady() {
        TestHelper.prepareData(false);

        Project__c contract = TestHelper.contractRecord;
        PageReference p = Page.ContractEdit;
        p.getParameters().put('id', contract.Id);
        Test.setCurrentPage(p);

        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(contract);
        ContractCtrl controller = new ContractCtrl(stdCtrl);

        Test.startTest();
        controller.onEditReady();
        Test.stopTest();
        System.assertEquals(false, controller.saveAndNew);
    }

    @IsTest static void testSaveRecord() {
        TestHelper.prepareData(false);

        Project__c contract = TestHelper.contractRecord;
        PageReference p = Page.ContractEdit;
        p.getParameters().put('id', contract.Id);
        Test.setCurrentPage(p);

        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(contract);
        ContractCtrl controller = new ContractCtrl(stdCtrl);
        controller.onEditReady();

        Test.startTest();
        controller.contract.Client_Spend_Defined_on_IO__c = true;
        controller.save();
        Test.stopTest();
        System.assertEquals(false, controller.saveAndNew);
    }

    @IsTest static void testChangedClientSpend() {
        TestHelper.prepareData(false);

        Project__c contract = TestHelper.contractRecord;
        contract.Gaps_Exist_Between_Projects__c = true;
        update contract;

        Sub_Project__c payment = [SELECT Id FROM Sub_Project__c WHERE Project__c = :contract.Id LIMIT 1];
        delete [SELECT Id FROM Sub_Project__c WHERE Id != :payment.Id];

        PageReference p = Page.ContractEdit;
        p.getParameters().put('id', contract.Id);
        Test.setCurrentPage(p);

        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(contract);
        ContractCtrl controller = new ContractCtrl(stdCtrl);
        controller.onEditReady();

        Test.startTest();
        controller.contract.Client_Spend_Defined_on_IO__c = true;
        controller.contract.Client_Spend__c = 20000;
        controller.save();
        System.assertEquals(false, controller.saveAndNew);

        controller.save();
        Test.stopTest();

        System.assertEquals(false, controller.saveAndNew);
        Project__c contractAfter = [SELECT Id, Client_Spend__c, Client_Spend_Defined_on_IO__c FROM Project__c WHERE Id =: contract.Id LIMIT 1];
        System.assertEquals(true, contractAfter.Client_Spend_Defined_on_IO__c);
        System.assertEquals(20000, contractAfter.Client_Spend__c);
    }

    @IsTest  static void testPageRedirect() {
        TestHelper.prepareData(false);

        Project__c contract = TestHelper.contractRecord;
        contract.Gaps_Exist_Between_Projects__c = true;
        update contract;

        Sub_Project__c payment = [SELECT Id FROM Sub_Project__c WHERE Project__c = :contract.Id LIMIT 1];
        delete [SELECT Id FROM Sub_Project__c WHERE Id != :payment.Id];

        PageReference p = Page.ContractEdit;
        p.getParameters().put('id', contract.Id);
        Test.setCurrentPage(p);

        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(contract);
        ContractCtrl controller = new ContractCtrl(stdCtrl);
        controller.onEditReady();

        Test.startTest();
        controller.saveAndNew  = true;
        controller.contract.Client_Spend__c = 20000;
        PageReference result = controller.save();
        System.assert(result.getUrl().contains(contract.Id) == false);

        controller.contract.Client_Spend__c = 23000;
        controller.contract.Client_Spend_Defined_on_IO__c = true;
        controller.save();
        System.assert(result.getUrl().contains(contract.Id) == false);

        controller.saveAndNew = false;
        controller.contract.Client_Spend__c = 30000;
        controller.contract.Client_Spend_Defined_on_IO__c = false;
        result = controller.save();
        System.assert(result.getUrl().contains(contract.Id) == true);
        Test.stopTest();
    }

    @IsTest private static void willCreateNewBrand() {
        PageReference contractPage = Page.ContractEdit;
        Test.setCurrentPage(contractPage);

        Account acc = TestHelper.createAccount();
        User usr = TestHelper.createUser();
        Opportunity opp = TestHelper.createOpportunity(usr, acc);
        Project__c contract = TestHelper.createContractNoInsert(acc.Id, 'testContract', opp.Id);
        contract.Brand__c = null;

        Test.startTest();
        ContractCtrl contractController = new ContractCtrl(new ApexPages.StandardController(contract));
        contractController.onEditReady();
        contractController.createBrand();
        contractController.cancelCreateBrand();
        contractController.brandUpdated();
        contractController.createBrand();
        contractController.brand.Name = 'testBrand';
        contractController.save();
        Test.stopTest();

        System.assertEquals(contractController.brand.Name, [SELECT Brand__r.Name FROM Project__c WHERE Id = :contractController.contract.Id].Brand__r.Name);
    }

    @IsTest private static void willCreateVideoUrl() {
        PageReference contractPage = Page.OpportunityEdit;
        Test.setCurrentPage(contractPage);

        Project__c contract = TestHelper.createContract('Test Contract', null, null, true);

        VideoUrl__c videoUrl = TestHelper.createVideoUrl();
        videoUrl.Contract__c = contract.Id;
        videoUrl.Platform__c = 'TrueView';
        videoUrl.Format__c = 'Video';
        videoUrl.StartDate__c = contract.Start_Date__c;
        videoUrl.EndDate__c = contract.End_Date__c;
        insert videoUrl;

        Test.startTest();
        ContractCtrl controller = new ContractCtrl(new ApexPages.StandardController(contract));
        controller.onEditReady();
        System.assertEquals(1, controller.videoURLs.size());

        controller.videoUrlRow = 0;
        controller.deleteVideoUrl();
        System.assertEquals(0, controller.videoURLs.size());

        controller.addNewVideoUrl();
        System.assertEquals(1, controller.videoURLs.size());

        controller.videoURLs[0].Name = 'Placeholder';
        controller.videoURLs[0].IsPlaceholder__c = true;
        controller.videoURLs[0].Platform__c = 'TrueView';
        controller.videoURLs[0].Format__c = 'Video';
        controller.videoURLs[0].StartDate__c = contract.Start_Date__c;
        controller.videoURLs[0].EndDate__c = contract.End_Date__c;
        controller.save();
        Test.stopTest();

        List<VideoUrl__c> insertedUrl = [SELECT IsPlaceholder__c FROM VideoUrl__c WHERE Contract__c = :contract.Id];

        System.assertEquals(1, insertedUrl.size());
        System.assertEquals(true, insertedUrl[0].IsPlaceholder__c);
    }

    @IsTest public static void contractHistoryWrapper_constructor() {
        TestHelper.createContract('Test Contract', null, null, true);

        Project__History history = new Project__History();
        history.Field = 'Owner';
        ContractCtrl.ContractHistoryWrapper historyWrapper = new ContractCtrl.ContractHistoryWrapper (history);

        System.assertEquals(history, historyWrapper.history);
        System.assertEquals(true, historyWrapper.action.startsWith('Changed'));
    }

    @IsTest public static void getRecordHistory() {
        Project__c contract = TestHelper.createContract('Test Contract', null, null, true);
        ContractCtrl ctrl = new ContractCtrl (new ApexPages.StandardController (contract));
        Project__History history1 = new Project__History(), history2 = new Project__History();
        ctrl.getRecordHistory(new List <Project__History> {history1,history2});
    }

    @IsTest
    public static void getPlatforms() {
        Project__c contract = TestHelper.createContract('Test Contract', null, null, true);
        ContractCtrl ctrl = new ContractCtrl (new ApexPages.StandardController (contract));

        List<PlatformWrapper> platforms = ctrl.getPlatforms();
        System.assertEquals('TrueView', platforms [0].oppPlatform.Platform__r.Name);
    }

    @IsTest
    public static void savePlatforms() {
        TestHelper.prepare1MonthOpportunityWith4Platforms(Utility.BILLING_PROFILES.Strike, ContactOpportunityHandler.CLOSED_WON, null);

        Test.startTest();
        ContractCtrl ctrl = new ContractCtrl(new ApexPages.StandardController([SELECT Id FROM Project__c LIMIT 1]));
        ctrl.savePlatforms();
        System.assertEquals(true, ApexPages.getMessages()[0].getSummary().contains('successfully'));
        Test.stopTest();
    }

    @IsTest
    public static void savePlatformsError() {
        TestHelper.prepare1MonthOpportunityWith4Platforms(Utility.BILLING_PROFILES.Strike, ContactOpportunityHandler.CLOSED_WON, null);

        Test.startTest();
        ContractCtrl ctrl = new ContractCtrl(new ApexPages.StandardController([SELECT Id FROM Project__c][0]));
        ctrl.platformsMap = null;
        ctrl.savePlatforms();
        System.assertEquals(true, ApexPages.hasMessages(ApexPages.Severity.ERROR));
        Test.stopTest();
    }

    @IsTest static void showClientSpendDifferenceMessageTest() {
        String initialCurrencyCode = 'USD', newCurrencyCode = 'EUR';

        Date sDate = Date.valueOf(Date.today().year() + '-' + Date.today().addMonths(-1).month() + '-01'),
                eDate = sDate.addDays(70);

        Platform__c adWordsPlatform = TestHelper.createTrueViewPlatform();
        insert adWordsPlatform;

        TestHelper.createOpportunity(sDate, eDate, adWordsPlatform, Utility.BILLING_PROFILES.Strike, false);
        insert TestHelper.opportunityRecord;

        OpportunityPlatform__c opPlatform = TestHelper.createOpportunityPlatform(TestHelper.opportunityRecord.Id, adWordsPlatform);
        opPlatform.PlatformAccount__c = StrikeDataAPIMock.accountId;
        insert opPlatform;

        Project__c contract = TestHelper.createContract('Test Contract', sDate, eDate, false);
        contract.SpendRefreshDate__c = null;
        contract.ClientServicesRep__c = [SELECT Id FROM User WHERE Client_Services_Rep__c = TRUE LIMIT 1].Id;
        contract.CurrencyIsoCode = initialCurrencyCode;
        insert contract;

        Test.startTest();
        ContractCtrl contractDetailsCtrl = new ContractCtrl(new ApexPages.StandardController(contract));
        System.assertEquals(false, contractDetailsCtrl.showPaymentClientSpendDifferenceMsg);
        System.assertEquals(false, contractDetailsCtrl.showProjectClientSpendDifferenceMsg);
        // by changing CurrencyISOCode I expect that Project/Payment client spend will be different after currency recalculation
        contract.CurrencyIsoCode = newCurrencyCode;
        update contract;
        Test.stopTest();

        contractDetailsCtrl = new ContractCtrl(new ApexPages.StandardController(contract));
        System.assertEquals(true, contractDetailsCtrl.showPaymentClientSpendDifferenceMsg);
        // projects Client Spend are recalculated by changes on payments in CurrencyISOCode field
        System.assertEquals(false, contractDetailsCtrl.showProjectClientSpendDifferenceMsg);
    }

    @IsTest static void getAllSpendsTest() {
        TestHelper.createAppSettings();

        Date sDate = Date.valueOf(Date.today().year() + '-' + Date.today().addMonths(-1).month() + '-01'),
                eDate = sDate.addDays(70);

        Platform__c adWordsPlatform = TestHelper.createTrueViewPlatform();
        insert adWordsPlatform;

        TestHelper.createOpportunity(sDate, eDate, adWordsPlatform, Utility.BILLING_PROFILES.Strike, false);
        insert TestHelper.opportunityRecord;

        OpportunityPlatform__c opPlatform = TestHelper.createOpportunityPlatform(TestHelper.opportunityRecord.Id, adWordsPlatform);
        opPlatform.PlatformAccount__c = StrikeDataAPIMock.accountId;
        insert opPlatform;

        Project__c contract = TestHelper.createContract('Test Contract', sDate, eDate, false);
        contract.SpendRefreshDate__c = null;
        contract.ClientServicesRep__c = [SELECT Id FROM User WHERE Client_Services_Rep__c = TRUE LIMIT 1].Id;
        insert contract;

        List<Payment__c> projects = [SELECT StrikeId__c, Start_Date__c, End_Date__c FROM Payment__c WHERE Project__c = :contract.Id];
        String projectName = '';
        for (Payment__c project :projects) {
            projectName = project.StrikeId__c;
        }
        System.assert(String.isNotBlank(projectName), 'At least one project should exist.');

        Test.startTest();
        ContractCtrl controller = new ContractCtrl(new ApexPages.StandardController(contract));

        StrikeDataAPIMock.setRandomMetrics = true;
        StrikeDataAPIMock.projectNames = new List<String>{projectName};
        StrikeDataAPIMock.accountIDs = new List<String>{StrikeDataAPIMock.accountId};

        Test.setMock(HttpCalloutMock.class, new StrikeDataAPIMock(projectName, StrikeDataAPI.PackageType.ADWORDS));
        controller.getAllSpends();
        Test.stopTest();
        System.debug('### TEST MESSAGES: ' + ApexPages.getMessages()[0].getDetail());
        System.assert(ApexPages.getMessages()[0].getDetail().contains('Spends imported successfully for: ' + projectName + '.'));
        System.assertEquals(ApexPages.getMessages()[0].getSeverity(), ApexPages.Severity.CONFIRM);
    }

    @IsTest static void getAllSpendsTest_ExpectingError() {
        TestHelper.createAppSettings();

        Date sDate = Date.valueOf(Date.today().year() + '-' + Date.today().addMonths(-1).month() + '-01'),
                eDate = sDate.addDays(70);

        Platform__c adWordsPlatform = TestHelper.createTrueViewPlatform();
        insert adWordsPlatform;

        TestHelper.createOpportunity(sDate, eDate, adWordsPlatform, Utility.BILLING_PROFILES.Strike, false);
        insert TestHelper.opportunityRecord;

        OpportunityPlatform__c opPlatform = TestHelper.createOpportunityPlatform(TestHelper.opportunityRecord.Id, adWordsPlatform);
        opPlatform.PlatformAccount__c = StrikeDataAPIMock.accountId;
        insert opPlatform;

        Project__c contract = TestHelper.createContract('Test Contract', sDate, eDate, false);
        contract.SpendRefreshDate__c = null;
        contract.ClientServicesRep__c = [SELECT Id FROM User WHERE Client_Services_Rep__c = TRUE LIMIT 1].Id;
        insert contract;

        List<Payment__c> projects = [SELECT StrikeId__c, Start_Date__c, End_Date__c FROM Payment__c WHERE Project__c = :contract.Id];
        String projectName = '';
        for (Payment__c project :projects) {
            projectName = project.StrikeId__c;
        }
        System.assert(String.isNotBlank(projectName), 'At least one project should exist.');

        Test.startTest();
        ContractCtrl controller = new ContractCtrl(new ApexPages.StandardController(contract));

        StrikeDataAPIMock.setEmptyMetrics = true;
        StrikeDataAPIMock.setRandomMetrics = true;
        Test.setMock(HttpCalloutMock.class, new StrikeDataAPIMock(projectName, StrikeDataAPI.PackageType.ADWORDS));
        controller.getAllSpends();
        Test.stopTest();
        System.debug('### TEST MESSAGES: ' + ApexPages.getMessages()[0].getDetail());
        System.assert(ApexPages.getMessages()[0].getDetail().contains('No data received for: ' + projectName));
        System.assertEquals(ApexPages.getMessages()[0].getSeverity(), ApexPages.Severity.ERROR);
    }

    @IsTest static void syncWithDataWarehouseTest() {
        TestHelper.createAppSettings();

        Date sDate = Date.valueOf(Date.today().year() + '-' + Date.today().addMonths(-1).month() + '-01'),
                eDate = sDate.addDays(70);

        Platform__c adWordsPlatform = TestHelper.createTrueViewPlatform();
        insert adWordsPlatform;

        TestHelper.createOpportunity(sDate, eDate, adWordsPlatform, Utility.BILLING_PROFILES.Strike, false);
        insert TestHelper.opportunityRecord;

        OpportunityPlatform__c opPlatform = TestHelper.createOpportunityPlatform(TestHelper.opportunityRecord.Id, adWordsPlatform);
        opPlatform.PlatformAccount__c = StrikeDataAPIMock.accountId;
        insert opPlatform;

        AdPlacement__c adPlacement = new AdPlacement__c(Platform__c = adWordsPlatform.Id, Name = 'TestAdPlacement');
        insert adPlacement;

        insert new OpportunityAdPlacement__c(OpportunityPlatform__c = opPlatform.Id, AdPlacement__c = adPlacement.Id, Opportunity__c = TestHelper.opportunityRecord.Id);

        Project__c contract = TestHelper.createContract('Test Contract', sDate, eDate, false);
        contract.SpendRefreshDate__c = null;
        contract.ClientServicesRep__c = [SELECT Id FROM User WHERE Client_Services_Rep__c = TRUE LIMIT 1].Id;
        insert contract;

        Test.startTest();

        Test.setCurrentPage(Page.ContractDetails);
        Test.setMock(HttpCalloutMock.class, new StrikeDataAPIMock.SyncContractCalloutMock());

        ContractCtrl controller = new ContractCtrl(new ApexPages.StandardController(contract));
        controller.syncWithDataWarehouse();

        System.debug('### ApexPages.getMessages(): ' + ApexPages.getMessages());
        System.assertEquals(0, ApexPages.getMessages().size(), 'No error appear');
        Test.stopTest();
    }

}