src/objects/AdPlacement__c.object
<CustomObject>
    <label>Ad Placement</label>
    <nameField>
        <label>Ad Placement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityAdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>AdPlacement__c</fullName>
        <label>Ad Placement</label>
        <referenceTo>AdPlacement__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Ad Placement</label>
    <nameField>
        <displayFormat>OAP-{0000}</displayFormat>
        <label>Opportunity Ad Placement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdPlacementWrapper.cls
public class AdPlacementWrapper 
{
    public OpportunityAdPlacement__c oppAdPlacement {get; set;}
    public Boolean isSelectedInitialValue {get; set;}
    public Boolean isSelected {get; set;}
    
    public AdPlacementWrapper(AdPlacement__c adPlacement)
    {
        this.oppAdPlacement = new OpportunityAdPlacement__c(AdPlacement__c = adPlacement.Id, AdPlacement__r = adPlacement);
        isSelected = false;
        isSelectedInitialValue = false;
    }
}