src/objects/AdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Ad Placements</relationshipLabel>
        <relationshipName>AdPlacements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ad Placement</label>
    <nameField>
        <label>Ad Placement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adwords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Reddit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                    <isActive>false</isActive>
                    <label>Instagram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityAdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>AdPlacement__c</fullName>
        <label>Ad Placement</label>
        <referenceTo>AdPlacement__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>OpportunityPlatform__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Opportunity Platform</label>
        <referenceTo>OpportunityPlatform__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Ad Placement</label>
    <nameField>
        <displayFormat>OAP-{0000}</displayFormat>
        <label>Opportunity Ad Placement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Platform__c.object
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlatformRepositoryTest.cls
@isTest
public class PlatformRepositoryTest {

    @isTest
    public static void getAvailablePlatformsTest()
    {
        Platform__c platformFB = TestHelper.createPlatform('Facebook', 'FB'),
            		platformIG = TestHelper.createPlatform('Instagram', 'IG');
        insert new Platform__c [] {platformFB, platformIG};
            
        System.assertEquals ('Facebook', PlatformRepository.getAvailablePlatforms() [0].Name);
    }
    
    @isTest
    public static void getAvailableOpportunityAdPlacements ()
    {
        Platform__c platformFB = TestHelper.createPlatform('Facebook', 'FB');
        insert platformFB;
        AdPlacement__c placement = TestHelper.createAdPlacement(platformFB.Id, 'adPlacement1');
        insert placement;
        Opportunity opp = TestHelper.createOpportunity(TestHelper.createUser(), TestHelper.createAccount()),
                    opp2 = TestHelper.createOpportunity(TestHelper.createUser('striketestuser@strike.com'), TestHelper.createAccount('accName'));
        
        insert new Opportunity [] {opp, opp2};
        OpportunityPlatform__c oppPlatform = TestHelper.createOpportunityPlatform(opp.Id, platformFB.Id);
        insert oppPlatform;
        OpportunityAdPlacement__c plac = TestHelper.createOpportunityAdPlacement(opp.Id, placement.Id);
        plac.OpportunityPlatform__c = oppPlatform.Id;
        insert plac;
        Set <Id> opps = new Set <Id> ();
        opps.add (opp.Id);
        opps.add(opp2.Id);
        Map<Id, List<OpportunityAdPlacement__c>> results = PlatformRepository.getOpportunityAdPlacementsForOpportunities(opps);
        System.assertEquals(plac.Opportunity__c, results.values() [0][0].Opportunity__c);
        System.assertEquals(plac.AdPlacement__c, results.values() [0][0].AdPlacement__c);
    }
    
    @isTest
    public static void getAvailableOpportunityAdPlacements_TwoAdPlacements ()
    {
        Platform__c platformFB = TestHelper.createPlatform('Facebook', 'FB');
        insert platformFB;
        AdPlacement__c placement1 = TestHelper.createAdPlacement(platformFB.Id, 'adPlacement1');
        AdPlacement__c placement2 = TestHelper.createAdPlacement(platformFB.Id, 'adPlacement2');
        insert new List <AdPlacement__c> {placement1, placement2};
        Opportunity opp = TestHelper.createOpportunity(TestHelper.createUser(), TestHelper.createAccount()),
                    opp2 = TestHelper.createOpportunity(TestHelper.createUser('striketestuser@strike.com'), TestHelper.createAccount('accName'));
        
        insert new Opportunity [] {opp, opp2};
        OpportunityPlatform__c oppPlatform = TestHelper.createOpportunityPlatform(opp.Id, platformFB.Id);
        insert oppPlatform;
        OpportunityAdPlacement__c plac1 = TestHelper.createOpportunityAdPlacement(opp.Id, placement1.Id),
            						plac2 = TestHelper.createOpportunityAdPlacement(opp.Id, placement2.Id);
        plac1.OpportunityPlatform__c = oppPlatform.Id;
        plac2.OpportunityPlatform__c = oppPlatform.Id;
        insert new OpportunityAdPlacement__c [] {plac1,plac2};
        Set <Id> opps = new Set <Id> ();
        opps.add (opp.Id);
        opps.add(opp2.Id);
        Map<Id, List<OpportunityAdPlacement__c>> results = PlatformRepository.getOpportunityAdPlacementsForOpportunities(opps);
        System.assertEquals(plac1.Opportunity__c, results.values() [0][0].Opportunity__c);
        System.assertEquals(plac1.AdPlacement__c, results.values() [0][0].AdPlacement__c);
    }    
 
}