src/objects/AdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Ad Placements</relationshipLabel>
        <relationshipName>AdPlacements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ad Placement</label>
    <nameField>
        <label>Ad Placement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cost_Structure_Metric__mdt.object
<CustomObject>
    <fields>
        <fullName>Cost_Structure__c</fullName>
        <label>Cost Structure</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPA</fullName>
                    <default>true</default>
                    <label>CPA</label>
                </value>
                <value>
                    <fullName>CPAC</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPE</fullName>
                </value>
                <value>
                    <fullName>CPER</fullName>
                </value>
                <value>
                    <fullName>CPF</fullName>
                </value>
                <value>
                    <fullName>CPI</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>CPLC</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPPL</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CPSU</fullName>
                </value>
                <value>
                    <fullName>CPV</fullName>
                </value>
                <value>
                    <fullName>CPLP</fullName>
                </value>
                <value>
                    <fullName>CPCO</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>CPDPV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cost Structure Metric</label>
    <pluralLabel>Cost Structure Metrics</pluralLabel>
</CustomObject>

src/objects/OpportunityAdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>AdPlacement__c</fullName>
        <label>Ad Placement</label>
        <referenceTo>AdPlacement__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>ContractAdPlacements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityPlatform__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Opportunity Platform</label>
        <referenceTo>OpportunityPlatform__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Ad Placement</label>
    <nameField>
        <displayFormat>OAP-{0000}</displayFormat>
        <label>Opportunity Ad Placement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>ContractPlatforms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_Structure_Metrics__c</fullName>
        <description>Selected Metrics for Cost Structures</description>
        <label>Cost Structure Metrics</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Platform__c.object
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Platform.cls
public with sharing class Platform {

    public static final List<Cost_Structure_Metric__mdt> METRICS_MDT = [SELECT Id, Label, Cost_Structure__c FROM Cost_Structure_Metric__mdt];

    public static Map<String, String> metricsToCCNames { get {
        if (metricsToCCNames == null) {
            metricsToCCNames = new Map<String,String>();
            for (Cost_Structure_Metric__mdt metric :Platform.METRICS_MDT) {
                metricsToCCNames.put(metric.Label, metric.Cost_Structure__c);
            }
        }
        return metricsToCCNames;
    } set; }

    public static String initPlatformsInfo(Map<Id, PlatformWrapper> platformsMap, List<OpportunityPlatform__c> oppPlatforms, List<OpportunityAdPlacement__c> oppAdPlacements, String platformString) {
        List<String> platformNames = new List<String>();
        for (OpportunityPlatform__c oppPlatform : oppPlatforms) {
            PlatformWrapper currentPlatform = platformsMap.get(oppPlatform.Platform__c);
            currentPlatform.isSelectedInitialValue = true;
            currentPlatform.isSelected = true;
            platformNames.add(oppPlatform.Platform__r.Name);
        }

        platformString = String.join(platformNames, ', ');
        for (OpportunityAdPlacement__c oppAdPlacement : oppAdPlacements) {
            AdPlacementWrapper currentAdPlacement = platformsMap.get(oppAdPlacement.AdPlacement__r.Platform__c).adPlacementsMap.get(oppAdPlacement.AdPlacement__c);
            currentAdPlacement.oppAdPlacement.Id = oppAdPlacement.Id;
            currentAdPlacement.isSelectedInitialValue = true;
            currentAdPlacement.isSelected = true;
        }
        return platformString;
    }

    public static void savePlatformInfo(Id oppId, Id contractId, Map<Id, PlatformWrapper> platformsMap) {
        List<OpportunityPlatform__c> opportunityPlatformsToUpsert = new List<OpportunityPlatform__c>();
        List<OpportunityPlatform__c> opportunityPlatformsToDelete = new List<OpportunityPlatform__c>();
        List<OpportunityAdPlacement__c> opportunityAdPlacementsToDelete = new List<OpportunityAdPlacement__c>();
        List<OpportunityAdPlacement__c> opportunityAdPlacementsToUpsert = new List<OpportunityAdPlacement__c>();

        for (PlatformWrapper platform :platformsMap.values()) {
            OpportunityPlatform__c oppPlatform = platform.oppPlatform;
            System.debug('### platform: ' + platform.oppPlatform);
            if (String.isBlank(oppPlatform.Opportunity__c)) {
                if (String.isNotBlank(oppId)) {
                    oppPlatform.Opportunity__c = oppId;
                }
                if (String.isNotBlank(contractId)) {
                    oppPlatform.Contract__c = contractId;
                }
            }

            // remove empty values
            List<String> metrics = platform.selectedMetrics.values();
            Integer j = 0;
            while (j < metrics.size()) {
                if (metrics.get(j) == null || metrics.get(j) == '') {
                    metrics.remove(j);
                } else {
                    j++;
                }
            }
            oppPlatform.Cost_Structure_Metrics__c = String.join(metrics, PlatformWrapper.CC_METRIC_SEPARATOR);

            if (platform.isSelected) {
                opportunityPlatformsToUpsert.add(oppPlatform);
            } else if (!platform.isSelected && platform.isSelectedInitialValue &&  oppPlatform.Id != null) {
                opportunityPlatformsToDelete.add(oppPlatform);
            }

            for (AdPlacementWrapper oppAdPlacement : platform.adPlacementsMap.values()) {
                OpportunityAdPlacement__c adPlacement = oppAdPlacement.oppAdPlacement;

                if (String.isBlank(adPlacement.Opportunity__c) && String.isNotBlank(oppId)) {
                    adPlacement.Opportunity__c = oppId;
                }
                if (String.isBlank(adPlacement.Contract__c) && String.isNotBlank(contractId)) {
                    adPlacement.Contract__c = contractId;
                }

                if (oppAdPlacement.isSelected && platform.isSelected) {
                    opportunityAdPlacementsToUpsert.add(adPlacement);
                } else if ((!oppAdPlacement.isSelected || !platform.isSelected) && oppAdPlacement.isSelectedInitialValue && adPlacement.Id != null) {
                    opportunityAdPlacementsToDelete.add(adPlacement);
                }
            }
        }
        upsert opportunityPlatformsToUpsert;

        for (OpportunityAdPlacement__c oppAdPlacement : opportunityAdPlacementsToUpsert) {
            if (String.isBlank(oppAdPlacement.OpportunityPlatform__c)) {
                oppAdPlacement.OpportunityPlatform__c = platformsMap.get(oppAdPlacement.AdPlacement__r.Platform__c).oppPlatform.Id;
            }
        }
        for (OpportunityPlatform__c oppPlatform : opportunityPlatformsToDelete) {
            platformsMap.get(oppPlatform.Platform__c).isSelectedInitialValue = false;
            platformsMap.get(oppPlatform.Platform__c).isSelected = false;
        }
        upsert opportunityAdPlacementsToUpsert;
        delete opportunityAdPlacementsToDelete;

        for (OpportunityAdPlacement__c oppAdPlacement : opportunityAdPlacementsToDelete) {
            Id platformId = oppAdPlacement.AdPlacement__r.Platform__c;
            platformsMap.get(platformId).adPlacementsMap.get(oppAdPlacement.AdPlacement__c).isSelectedInitialValue = false;
            platformsMap.get(platformId).adPlacementsMap.get(oppAdPlacement.AdPlacement__c).isSelected = false;
        }
        delete opportunityPlatformsToDelete;
    }
}