src/objects/AppSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>CreditNotesNotificationBcc__c</fullName>
        <label>Credit Notes Notification Bcc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreditNotesNotificationRecipients__c</fullName>
        <label>Credit Notes Notification Recipients</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvoiceNotificationCC__c</fullName>
        <label>Invoice Notification CC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Settings</label>
</CustomObject>

src/objects/CreditNote__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventLog__c.object
<CustomObject>
    <description>Record errors, events</description>
    <fields>
        <fullName>CreditNote__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Credit Note</label>
        <referenceTo>CreditNote__c</referenceTo>
        <relationshipLabel>Event Logs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Event Log</label>
    <nameField>
        <displayFormat>EventLog-{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>InvoiceNotificationSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Client_Services_Rep__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Services Rep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PodEmail__c</fullName>
        <label>Pod Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SubProjectNotification.cls
public class SubProjectNotification {

    private static AppSettings__c appSettings = AppSettings__c.getInstance('Default');
    
    private static AppSettings__c getAppSettings() {
        return appSettings;
    }
    
    public static List<NotificationUtil.NotificationResult> sendPaymentsNotification() {
        List<Contact> contacts = new List<Contact>();
        List<Messaging.SingleEmailMessage> messages = getPaymentNotifications(contacts);
        
        Map<Id, User> clientServices = new Map<Id, User>([SELECT Id, Email, PodEmail__c FROM User WHERE Client_Services_Rep__c = TRUE AND Email != NULL]);
        Map<Id, List<Sub_Project__c>> paymentsToApprove = SubProjectRepository.getPaymentsForNotification(clientServices.keySet());
        
        List<Sub_Project__c> paymentsToUpdate = new List<Sub_Project__c>();
        for (List<Sub_Project__c> payments : paymentsToApprove.values()) {
            paymentsToUpdate.addAll(payments);
        }
        
        for (Sub_Project__c payment :paymentsToUpdate) {
            payment.InvoiceNotificationSent__c = true;
        }
        
        List<NotificationUtil.NotificationResult> notificationResult = NotificationUtil.sendNotifications(messages, contacts);
        try {
            update paymentsToUpdate;
        } catch (Exception ex) {
            EventLog__c log = EventLog.createEventLog('Invoice approval notification. Error updating payments', EventLog.STATUS_ERROR, EventLog.TYPE_CONTRACT);
            log.Description__c = ex.getMessage();
            insert log;
        }
         
        return notificationResult;
    }
    
    public static void sendCreditNotesNotification() {
        getAppSettings();
        
        if (String.isNotBlank(appSettings.CreditNotesNotificationRecipients__c)) {
            List<String> recipients = appSettings.CreditNotesNotificationRecipients__c.split(',');
            if (!recipients.isEmpty()) {
                List<CreditNote__c> creditNotes = CreditNoteRepository.getPendingCreditNotes(null, null, 'CreatedDate', 'ASC');
                List<Sub_Project__c> payments = SubProjectRepository.getPaymentsSubmittedToXero();
                
                if (!creditNotes.isEmpty() || !payments.isEmpty()) {
                    Contact testContact = NotificationUtil.createContactForNotification(recipients.remove(0));
                    insert testContact;
                    
                    Messaging.SingleEmailMessage mail = NotificationUtil.prepareMessage(testContact.Id, recipients, new List<String>(), appSettings.CreditNotesNotificationBcc__c, 'CreditNotesNotification');
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
                    delete testContact;
                }
            }
        }
    }
 
    public static List<Messaging.SingleEmailMessage> getPaymentNotifications(List<Contact> contacts) {
        Map<Id, User> clientServices = new Map<Id, User>([SELECT Id, Email, PodEmail__c FROM User WHERE Client_Services_Rep__c = TRUE AND Email != NULL]);
        Map<Id, List<Sub_Project__c>> paymentsToApprove = SubProjectRepository.getPaymentsForNotification(clientServices.keySet());
        List<String> notificationCC = new List<String>();
        
        if (String.isNotBlank(getAppSettings().InvoiceNotificationCC__c)) {
            notificationCC.add(getAppSettings().InvoiceNotificationCC__c);
        }
        return NotificationUtil.getClientServiceNotifications(clientServices, paymentsToApprove.keySet(), notificationCC, contacts, 'InvoiceNotification', false);
    }  
}