src/objects/AppSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>CurrencyAPIAccountID__c</fullName>
        <label>CurrencyAPIAccountID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyAPIEndpoint__c</fullName>
        <label>CurrencyAPIEndpoint</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyAPIKey__c</fullName>
        <label>Currency API Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>App Settings</label>
</CustomObject>

src/objects/CurrencyHistory__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AllCurrencies__c</fullName>
        <label>All Currencies</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Currency History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Currency History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CurrencyHistory.cls
public class CurrencyHistory {

    @Future (Callout=true)
    public static void updateCurrencyRates(Date dt) {
        Map<String, Object> currencyRates = getCurrencyRates(String.valueOf (dt));
        
        CurrencyHistory__c currencyHistory = new CurrencyHistory__c();
        currencyHistory.Date__c = dt;
        currencyHistory.AUD__c = (Decimal) currencyRates.get('USDAUD');
        currencyHistory.CAD__c = (Decimal) currencyRates.get('USDCAD');
        currencyHistory.EUR__c = (Decimal) currencyRates.get('USDEUR');
        currencyHistory.GBP__c = (Decimal) currencyRates.get('USDGBP');
        currencyHistory.NZD__c = (Decimal) currencyRates.get('USDNZD');
        currencyHistory.PLN__c = (Decimal) currencyRates.get('USDPLN');
        currencyHistory.SGD__c = (Decimal) currencyRates.get('USDSGD');
        currencyHistory.IDR__c = (Decimal) currencyRates.get('USDIDR');
        currencyHistory.MXN__c = (Decimal) currencyRates.get('USDMXN');
        currencyHistory.MYR__c = (Decimal) currencyRates.get('USDMYR');
        currencyHistory.PHP__c = (Decimal) currencyRates.get('USDPHP');
        currencyHistory.HKD__c = (Decimal) currencyRates.get('USDHKD');
        currencyHistory.JPY__c = (Decimal) currencyRates.get('USDJPY');
        currencyHistory.KRW__c = (Decimal) currencyRates.get('USDKRW');
        currencyHistory.INR__c = (Decimal) currencyRates.get('USDINR');
        currencyHistory.THB__c = (Decimal) currencyRates.get('USDTHB');
        currencyHistory.RUB__c = (Decimal) currencyRates.get('USDRUB');
        currencyHistory.AllCurrencies__c = JSON.serializePretty(currencyRates);
        
        insert currencyHistory;        
    }
    
    public static Map<String, Object> getCurrencyRates(String dateParam) {
        AppSettings__c appSettings = AppSettings__c.getInstance('Default');
        
        String urlStart = appSettings.CurrencyAPIEndpoint__c;
        String fromParam = 'from=USD';
        String toParams = 'to=AUD,CAD,EUR,GBP,NZD,PLN,SGD,IDR,MXN,MYR,PHP,INR,HKD,JPY,KRW,THB,RUB';
        String amountParam = 'amount=1.00';
        String dateParamString = 'date=' + dateParam;

        HttpRequest req = new HttpRequest();
        req.setEndpoint(urlStart + fromParam + '&' + toParams + '&' + amountParam + '&' + dateParamString);
        req.setMethod('GET');
        Blob headerValue = Blob.valueOf(appSettings.CurrencyAPIAccountID__c + ':' + appSettings.CurrencyAPIKey__c);        
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(headerValue));
        
        HttpResponse res = new Http().send(req);
        if (res.getStatusCode() != 200) return null;

        Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        List<Object> resultsArray = (List<Object>) responseMap.get('to');

        Map<String, Object> currencyRatesMap = new Map<String, Decimal>();
        for (Object result :resultsArray) {
            Map<String, Object> resultsMap = (Map <String, Object>) result;
            String quoteCurrency = (String) resultsMap.get('quotecurrency');
            Object mid = resultsMap.get('mid');
            
            if (quoteCurrency != null &&  mid != null) {
                currencyRatesMap.put('USD' + quoteCurrency, mid);
            }
        }
        return currencyRatesMap;
    }
}