src/objects/AppSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>CurrencyUserLogin__c</fullName>
        <label>CurrencyUserLogin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrencyUserPassword__c</fullName>
        <label>CurrencyUserPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Settings</label>
</CustomObject>

src/objects/CurrencyHistory__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AllCurrencies__c</fullName>
        <label>All Currencies</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Currency History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Currency History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateCurrenciesBatch.cls
global class UpdateCurrenciesBatch implements Database.Batchable <SObject>, Database.AllowsCallouts {

    global UpdateCurrenciesBatch() {}
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT id, ISOCode, DecimalPlaces, ConversionRate FROM CurrencyType ORDER BY ISOCode ASC');
    } 
    
    global void execute(Database.BatchableContext bc, List<CurrencyType> scope) {
        AppSettings__c appSettings = AppSettings__c.getInstance('Default');

        PartnerSoapSforceCom.Soap partner = new PartnerSoapSforceCom.Soap();
        PartnerSoapSforceCom.LoginResult lr = partner.login(appSettings.CurrencyUserLogin__c, appSettings.CurrencyUserPassword__c);
        String sessionID = lr.sessionId;

        CurrencyHistory__c currencyHistoryRecord = [
            SELECT Id, AUD__c, CAD__c, EUR__c, GBP__c, IDR__c, INR__c, MXN__c, MYR__c, NZD__c, PHP__c, PLN__c, SGD__c, HKD__c, JPY__c,
                    KRW__c, THB__c, RUB__c, AllCurrencies__c, Date__c
            FROM CurrencyHistory__c
            ORDER BY Date__c DESC, CreatedDate DESC
            LIMIT 1
        ];

        for (CurrencyType cType :scope) {
            if (cType.IsoCode.equals ('USD')) return;

            Double currentConversionRate = (Double) currencyHistoryRecord.get(cType.IsoCode + '__c');
            HttpRequest req = new HttpRequest();
            req.setEndpoint(Url.getSalesforceBaseUrl().toExternalForm() + '/services/data/v28.0/sobjects/CurrencyType/');
            req.setMethod('POST');
            req.setBody('{ "IsoCode" : "'+cType.IsoCode+'", "DecimalPlaces" : '+cType.DecimalPlaces+', "ConversionRate" : '+currentConversionRate+', "IsActive" : "true" }');
            req.setHeader('Authorization', 'OAuth ' + sessionID);
            req.setHeader('Content-Type', 'application/json');
            new Http().send(req);
        }
    }
    
    global void finish(Database.BatchableContext bc) {}
}