src/objects/Average_Monthly_Currency_History__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Average Monthly Currency History</label>
    <nameField>
        <label>Average Monthly Currency History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Average Monthly Currency Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CurrencyHistory__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Currency History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Currency History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Monthly_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Currency_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Average Monthly Currency History</label>
        <referenceTo>Average_Monthly_Currency_History__c</referenceTo>
        <relationshipLabel>Monthly Distributions</relationshipLabel>
        <relationshipName>Monthly_Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Monthly Distributions</relationshipLabel>
        <relationshipName>Monthly_Distribution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Monthly Distribution</label>
    <nameField>
        <displayFormat>MD-{00000}</displayFormat>
        <label>MD Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CalcAverageMonthlyExchangeRatesTest.cls
@isTest
public class CalcAverageMonthlyExchangeRatesTest {
    
    @testSetup
    public static void setupTestData ()
    {
        
        CurrencyHistory__c ch1 = new CurrencyHistory__c ();
        ch1.Date__c = Date.newInstance(2018, 05, 01);
        ch1.AUD__c = 0.6;
        ch1.EUR__c = 2.8;
        ch1.CAD__c  = 0;
        ch1.GBP__c  = 0;
        ch1.NZD__c  = 0;
        ch1.PLN__c  = 0;
        ch1.SGD__c  = 0;
        ch1.IDR__c  = 0;
        ch1.MXN__c  = 0;
        ch1.MYR__c  = 0;
        ch1.PHP__c  = 0;
        ch1.HKD__c  = 0;
        ch1.JPY__c  = 0;
        ch1.KRW__c  = 0;
        ch1.INR__c  = 0;
        ch1.THB__c  = 0;
        ch1.RUB__c  = 0;
        
        CurrencyHistory__c ch2 = new CurrencyHistory__c ();
        ch2.Date__c = Date.newInstance(2018, 05, 31);
        ch2.AUD__c = 0.4;
        ch2.EUR__c = 2.2;
        ch2.CAD__c  = 0;
        ch2.GBP__c  = 0;
        ch2.NZD__c  = 0;
        ch2.PLN__c  = 0;
        ch2.SGD__c  = 0;
        ch2.IDR__c  = 0;
        ch2.MXN__c  = 0;
        ch2.MYR__c  = 0;
        ch2.PHP__c  = 0;
        ch2.HKD__c  = 0;
        ch2.JPY__c  = 0;
        ch2.KRW__c  = 0;
        ch2.INR__c  = 0;
        ch2.THB__c  = 0;
        ch2.RUB__c  = 0;
        
        insert new CurrencyHistory__c [] {ch1, ch2};    
    }
    
    @isTest
    public static void testAverages ()
    {
        Test.startTest();
        Database.executeBatch(new CalcAverageMonthlyExchangeRates(Date.newInstance(2018, 05, 31)));
        Test.stopTest();
        
        List <Average_Monthly_Currency_History__c> avgList = [SELECT AUD__c, EUR__c FROM Average_Monthly_Currency_History__c];
        
        
        System.assertEquals (0.5, avgList [0].AUD__c);
        System.assertEquals (2.5, avgList [0].EUR__c);
    }
    
    @isTest
    public static void testMonthlyDistributionUpdate ()
    {
        
        Monthly_Distribution__c md1 = new Monthly_Distribution__c ();
        md1.CurrencyIsoCode = 'EUR';
        md1.Client_Spend__c = 100;
        md1.Start_Date__c=Date.newInstance(2018,05,01);
        md1.End_Date__c=Date.newInstance(2018,05,31);
        
        
        Account acc = new Account (Name = 'TestAccX', BillingCountry = 'Czech Republic');
        insert acc;
        
        Project__c contract = TestHelper.createContractNoInsert (acc.Id, 'Test Contract', '');
        insert contract; 
        
        
        md1.Project__c = [SELECT ID FROM Payment__c LIMIT 1] [0].Id;
        insert md1;
        
        Test.startTest();
        Database.executeBatch(new CalcAverageMonthlyExchangeRates(Date.newInstance(2018,05,31)));
        Test.stopTest();
        
        List <Monthly_Distribution__c> mdList = [SELECT ID, Average_Monthly_Currency_History__c
                                                 FROM Monthly_Distribution__c WHERE ID = :md1.Id];
        
        System.assertNotEquals (null, mdList [0].Average_Monthly_Currency_History__c);
    }    
    
   @isTest
    public static void testMonthlyDistributionPopulateEmpty()
    {
        
        Monthly_Distribution__c md1 = new Monthly_Distribution__c ();
        md1.CurrencyIsoCode = 'EUR';
        md1.Client_Spend__c = 100;
        md1.Start_Date__c=Date.newInstance(2017,05,01);
        md1.End_Date__c=Date.newInstance(2017,05,31);
        
        
        Account acc = new Account (Name = 'TestAccX', BillingCountry = 'Czech Republic');
        insert acc;
        
        Project__c contract = TestHelper.createContractNoInsert (acc.Id, 'Test Contract', '');
        insert contract; 
        
        
        md1.Project__c = [SELECT ID FROM Payment__c LIMIT 1] [0].Id;
        insert md1;
        
        Test.startTest();
        Database.executeBatch(new CalcAverageMonthlyExchangeRates(Date.newInstance(2018,05,31)));
        Test.stopTest();
        
        List <Monthly_Distribution__c> mdList = [SELECT ID, Average_Monthly_Currency_History__c
                                                 FROM Monthly_Distribution__c WHERE ID = :md1.Id];
        
        System.assertNotEquals (null, mdList [0].Average_Monthly_Currency_History__c);
    }    
           
          
}