src/objects/Average_Monthly_Currency_History__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Average Monthly Currency History</label>
    <nameField>
        <label>Average Monthly Currency History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Average Monthly Currency Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MM_Spendings__c.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Currency_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Average Monthly Currency History</label>
        <referenceTo>Average_Monthly_Currency_History__c</referenceTo>
        <relationshipLabel>Media Manager Spendings</relationshipLabel>
        <relationshipName>Media_Manager_Spendings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BypassValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Media Manager Spendings</relationshipLabel>
        <relationshipName>Media_Manager_Spendings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivered__c</fullName>
        <label>Delivered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Media_Spend__c</fullName>
        <label>Media Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Strike_ID__c</fullName>
        <formula>Platform__r.Prefix__c + Contract__r.Project_ID__c</formula>
        <label>Strike ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>summarized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>summarized</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Manager Spendings</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Media Manager Spendings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Manager Spendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BypassValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Media_Spend_Counter__c</fullName>
        <label>Media Spend Counter</label>
        <summaryForeignKey>Project_Media_Spend__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>BypassValidationRule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BypassValidationRule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InvoicesPaid__c</fullName>
        <formula>NoOfIvoicesNotPaid__c = 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoices Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MM_Spendings_Counter__c</fullName>
        <label>MM Spendings Counter</label>
        <summaryForeignKey>MM_Spendings__c.Contract__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Strike_ID__c</fullName>
        <label>Strike ID text</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Media_Spend__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Media Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Currency_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Average Monthly Currency History</label>
        <referenceTo>Average_Monthly_Currency_History__c</referenceTo>
        <relationshipLabel>Contract Media Spend</relationshipLabel>
        <relationshipName>Contract_Media_Spend</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivered__c</fullName>
        <label>Delivered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMSpending__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Media Manager Spendings</label>
        <referenceTo>MM_Spendings__c</referenceTo>
        <relationshipLabel>Contract Media Spend</relationshipLabel>
        <relationshipName>ContractMediaSpend</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Contract Media Spend</relationshipLabel>
        <relationshipName>ContractMediaSpends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>summarized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>summarized</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract Media Spend</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Media Spend</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SCH_BATCH_MediaSpendSummarizer.cls
public class SCH_BATCH_MediaSpendSummarizer implements Database.Batchable <sObject>, Database.stateful, Schedulable {

    public static final string SUMMARIZE_PMS    = 'Summarize Project Media Spends';
    public static final string SUMMARIZE_MM_SPENDINGS    = 'Summarize MM Spendings';
    public static final string SET_PMS_LOOKUPS = 'Set Lookups between new PMS and MM Spendings';
    
    public static final List<string> steps = new List<string>{SUMMARIZE_PMS,SUMMARIZE_MM_SPENDINGS,SET_PMS_LOOKUPS};
        
    public string currentStep;
    private string query;    
    
    public void execute(SchedulableContext ctx) 
    {        
        Database.executeBatch(new SCH_BATCH_MediaSpendSummarizer(steps[0]), 1);
    }   
  
    public SCH_BATCH_MediaSpendSummarizer()
    {   
        this(steps[0]);
    }
    public SCH_BATCH_MediaSpendSummarizer(String step)
    {        
        currentStep = step;
        if (currentStep == SUMMARIZE_PMS)
        {
            query = 'SELECT id, CurrencyIsoCode, Media_Spend_Counter__c, project__r.strike_id__c FROM Payment__c WHERE Media_Spend_Counter__c>0';
            query +=' AND id not in (select project__c from Project_Media_Spend__c WHERE summarized__c=true) ';
            if(Test.isRunningTest()==false) query +=' AND project__r.InvoicesPaid__c=true';
        }          
        if (currentStep == SUMMARIZE_MM_SPENDINGS)
        {
            query = 'SELECT ID, CurrencyIsoCode, MM_Spendings_Counter__c, strike_id__c, Start_Date__c FROM Project__c WHERE  MM_Spendings_Counter__c>0 ';
            query +=' AND id not in (select contract__c from MM_Spendings__c WHERE summarized__c=true) ';
            if(Test.isRunningTest()==false) query +=' AND  InvoicesPaid__c=true';
        }            
        if (currentStep == SET_PMS_LOOKUPS)
        {
            query = 'SELECT id, Project__c, Project__r.Project__c FROM Project_Media_Spend__c WHERE MMSpending__c=null AND summarized__c=true';
        }    
    }     
    
    public Database.Querylocator start(Database.BatchableContext bc)
    {      
        return Database.getQuerylocator(query);
    } 
    
    public void execute(Database.BatchableContext bc, List<SObject> scope)
    {
        MMSpendingsHandler.skipProjectMediaSpendCreation = true;
        
        if (currentStep == SUMMARIZE_MM_SPENDINGS) {
            summarizeMMSpendings((List<Project__c>) scope);
        }  else if(currentStep == SUMMARIZE_PMS) {
            summarizePMS((List<Payment__c>) scope);
        }  else if(currentStep == SET_PMS_LOOKUPS) {
            setLookups((List<Project_Media_Spend__c>) scope);
        }
        
    }    
    
    public void setLookups(List<Project_Media_Spend__c> scope) {
        Set<ID> contractIDs = new Set<ID>();
        for(Project_Media_Spend__c spend: scope) contractIDs.add(spend.Project__r.Project__c);

        Map<Id,Id> MMspendByContract = new Map<Id,Id>();
        for(MM_Spendings__c MMspend: [SELECT Id,Contract__c FROM MM_Spendings__c WHERE Contract__c IN : contractIDs]){
            MMspendByContract.put(MMSpend.Contract__c, MMSpend.Id);
        }
        
        for(Project_Media_Spend__c spend: scope){
            spend.MMSpending__c = MMspendByContract.get(spend.Project__r.Project__c);
        }
        
        update scope;
    }
    
    public void summarizeMMSpendings(List<Project__c> scope){
		List<MM_Spendings__c> summarizedSpends = new List<MM_Spendings__c>(); 
        List<MM_Spendings__c> spendToDelete = new List<MM_Spendings__c>();           
        for(Project__c contract: scope) {
            MM_Spendings__c newSpend = new MM_Spendings__c(Media_Spend__c=0, summarized__c=true);
            newSpend.Date__c=contract.Start_Date__c;
            newSpend.Contract__c=contract.Id;
            newSpend.CurrencyIsoCode=contract.CurrencyIsoCode;
            newSpend.BypassValidationRule__c=true;
            List<MM_Spendings__c> spends  =
                [select id, Media_Spend__c,  (SELECT Id FROM ContractMediaSpend__r) 
                 from MM_Spendings__c WHERE Contract__c=:contract.Id AND summarized__c=false 
                 ORDER By Date__c DESC];  
            Boolean errorDetected = false;
            for(MM_Spendings__c spend: spends) {
                newSpend.Media_Spend__c+=spend.Media_Spend__c;
                if(spend.ContractMediaSpend__r.size()>0) errorDetected=true;
            }
            if(errorDetected==false) {
                summarizedSpends.add(newSpend);            
                spendToDelete.addAll(spends);  
            }
        }
        
        insert summarizedSpends;
        delete spendToDelete;                  
    }
    
    public void summarizePMS(List<Payment__c> scope){
		List<Project_Media_Spend__c> summarizedSpends = new List<Project_Media_Spend__c>(); 
        List<Project_Media_Spend__c> spendToDelete = new List<Project_Media_Spend__c>();         
        for(Payment__c proj: scope) {
            Project_Media_Spend__c newSpend = new Project_Media_Spend__c(delivered__c=0,Amount__c=0, summarized__c=true);
            newSpend.CurrencyIsoCode=proj.CurrencyIsoCode;
            List<Project_Media_Spend__c> spends  =
                [select id, amount__c, delivered__c, Average_Monthly_Currency_History__c, Date__c, MMSpending__c, Project__c 
                 from Project_Media_Spend__c WHERE Project__c=:proj.Id AND summarized__c=false ORDER By Date__c DESC];
            newSpend.Date__c=spends[0].Date__c;
            newSpend.Average_Monthly_Currency_History__c=spends[0].Average_Monthly_Currency_History__c;
            newSpend.MMSpending__c=null;
            newSpend.Project__c =spends[0].Project__c ;
            
            
            for(Project_Media_Spend__c oldSpend: spends){
                if(oldSpend.Amount__c!=null) newSpend.Amount__c+=oldSpend.Amount__c;
                if(oldSpend.delivered__c!=null) newSpend.delivered__c+=oldSpend.delivered__c;
            }
			summarizedSpends.add(newSpend);            
            spendToDelete.addAll(spends);
            
        }
        insert summarizedSpends;
        delete spendToDelete;        
    }
    
    public void finish(Database.BatchableContext bc)
    {
        Iterator<String> iter = steps.iterator();
        while (iter.hasNext()) {
            String step = iter.next();
            if (step == currentStep && iter.hasNext()) {
                String nextStep = iter.next();
                Database.executeBatch(new SCH_BATCH_MediaSpendSummarizer(nextstep), 1);
            }
        }        
    }         
    
}