src/objects/Average_Monthly_Currency_History__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Average Monthly Currency History</label>
    <nameField>
        <label>Average Monthly Currency History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Average Monthly Currency Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Monthly_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Currency_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Average Monthly Currency History</label>
        <referenceTo>Average_Monthly_Currency_History__c</referenceTo>
        <relationshipLabel>Monthly Distributions</relationshipLabel>
        <relationshipName>Monthly_Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_Account_formula__c</fullName>
        <formula>Project__r.Project__r.BrandAccount__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand/Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Account_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand/Account</label>
        <referenceTo>Brand_Account__c</referenceTo>
        <relationshipName>Monthly_Distribution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand_formula__c</fullName>
        <formula>Project__r.Project__r.Brand__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Monthly_Distribution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Monthly Distribution</label>
    <nameField>
        <displayFormat>MD-{00000}</displayFormat>
        <label>MD Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MonthlyDistributionHandler.cls
public class MonthlyDistributionHandler implements ITrigger {

    public MonthlyDistributionHandler() {}

    public void bulkBefore() {}

    public void bulkAfter() {}

    public void beforeInsert(List<SObject> so) {
        List<Average_Monthly_Currency_History__c> avMonthCurrencyHistories = [SELECT Id, Start_Date__c, End_Date__c FROM Average_Monthly_Currency_History__c];

        for (Monthly_Distribution__c monthlyDistribution :(List<Monthly_Distribution__c>) so) {
            monthlyDistribution.Brand_Lookup__c = monthlyDistribution.Brand_formula__c;
            monthlyDistribution.Brand_Account_lookup__c = monthlyDistribution.Brand_Account_formula__c;

            if (!avMonthCurrencyHistories.isEmpty()){
                for (Average_Monthly_Currency_History__c rate: avMonthCurrencyHistories) {
                    if (monthlyDistribution.Date__c >= rate.Start_Date__c && monthlyDistribution.Date__c <= rate.End_Date__c){
                        monthlyDistribution.Average_Monthly_Currency_History__c = rate.Id;
                        break;
                    }
                }
                if (monthlyDistribution.Average_Monthly_Currency_History__c == null) {
                    monthlyDistribution.Average_Monthly_Currency_History__c = avMonthCurrencyHistories[0].Id;
                }
            }
        }
    }

    public void beforeUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) { }

    public void beforeDelete(List<SObject> so) {}

    public void afterInsert(List<SObject> so) {
        MonthlyDistribution.assignMonthlyDistributionToSalesRep((List<Monthly_Distribution__c>) so);
    }

    public void afterUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {}

    public void afterDelete(List<SObject> so) {}

    public void andFinally() {}

}