src/objects/Average_Monthly_Currency_History__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Average Monthly Currency History</label>
    <nameField>
        <label>Average Monthly Currency History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Average Monthly Currency Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission_Profile__c.object
<CustomObject>
    <fields>
        <fullName>GP_Bonus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GP Bonus</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Bonus_GP__c</fullName>
        <formula>Contract__r.ActualGrossProfit__c * Percentage_of_GP_Allocation__c / 100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bonus GP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Profile__c</fullName>
        <label>Sales Rep</label>
        <referenceTo>Commission_Profile__c</referenceTo>
        <relationshipLabel>Sales Reps</relationshipLabel>
        <relationshipName>Sales_Reps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percentage_of_GP_Allocation__c</fullName>
        <label>% of GP Allocation</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <description>Unique ID of Sales Rep prevents from adding him to contract twice.</description>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Gross_Profit__c</fullName>
        <label>Actual Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Currency_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Average Monthly Currency History</label>
        <referenceTo>Average_Monthly_Currency_History__c</referenceTo>
        <relationshipLabel>Monthly Distributions</relationshipLabel>
        <relationshipName>Monthly_Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>TEXT(YEAR(Start_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Monthly Distribution</label>
    <nameField>
        <displayFormat>MD-{00000}</displayFormat>
        <label>MD Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Rep_Annual_Bonus__c.object
<CustomObject>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <summarizedField>Sales_Rep_Quarterly_Bonus__c.Gross_Profit__c</summarizedField>
        <summaryForeignKey>Sales_Rep_Quarterly_Bonus__c.Year__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <label>Sales Rep</label>
        <referenceTo>Commission_Profile__c</referenceTo>
        <relationshipLabel>Sales Rep Annual Bonuses</relationshipLabel>
        <relationshipName>Sales_Rep_Annual_Bonuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Rep Annual Bonus</label>
    <nameField>
        <displayFormat>SRA-{0000}</displayFormat>
        <label>Sales Rep Annual Bonus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Annual Bonuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Rep_MD__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Profile</label>
        <referenceTo>Commission_Profile__c</referenceTo>
        <relationshipLabel>Sales Rep Monthly Distributions</relationshipLabel>
        <relationshipName>Sales_Rep_Monthly_Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>Monthly_Distribution__r.Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <formula>Monthly_Distribution__r.Actual_Gross_Profit__c * Sales_Rep__r.Percentage_of_GP_Allocation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Distribution__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Monthly Distribution</label>
        <referenceTo>Monthly_Distribution__c</referenceTo>
        <relationshipLabel>Sales Rep Monthly Distributions</relationshipLabel>
        <relationshipName>Sales_Rep_MDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>Contract_Sales_Rep__c</referenceTo>
        <relationshipName>Sales_Rep_MDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Rep Monthly Distribution</label>
    <nameField>
        <displayFormat>SRMD-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Rep_Quarterly_Bonus__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <referenceTo>Sales_Rep_Annual_Bonus__c</referenceTo>
        <relationshipLabel>Sales Rep Quarterly Bonuses</relationshipLabel>
        <relationshipName>Sales_Rep_Quarterly_Bonuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Rep Quarterly Bonus</label>
    <nameField>
        <displayFormat>SRQ-{0000}</displayFormat>
        <label>Sales Rep Quarter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Quarterly Bonuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SCH_BATCH_SalesRepBonusCalc.cls
public class SCH_BATCH_SalesRepBonusCalc implements Database.Batchable <sObject>, Database.stateful, Schedulable
{
    public static final string CREATE_BONUSES     = 'Create Annual and Quarter Bonuses records';
    public static final string CALCULATE_BONUSES    = 'Nightly recalculate bonuses';
    
    
    public static final List<string> steps = new List<string>{CREATE_BONUSES,CALCULATE_BONUSES};
        
    public string currentStep;
    private string query;    
    public Date proceedingDate {get; set;}
    
    
    public void execute(SchedulableContext ctx) 
    {        
        if(Date.today().day()==1 && Date.today().month()==1)
            Database.executeBatch(new SCH_BATCH_SalesRepBonusCalc(), 200);
        else 
            Database.executeBatch(new SCH_BATCH_SalesRepBonusCalc(steps[1], Date.today()), 10);
    }   
    
    public SCH_BATCH_SalesRepBonusCalc()
    {
        this (steps [0], Date.today());
    }
    
    public SCH_BATCH_SalesRepBonusCalc(Date eMD)
    {
        this (steps [0], eMD);
    }
    
    public SCH_BATCH_SalesRepBonusCalc(String step,Date pD)
    {
        proceedingDate=pD;
        currentStep = step;
        Integer year = pd.year();
        Integer quarter = getQuarterFromDate(pd);
        
        if (currentStep == CREATE_BONUSES)
        {
            query = 'SELECT ID, CurrencyISOCode FROM Commission_Profile__c WHERE GP_Bonus__c=true';
        }
        if (currentStep == CALCULATE_BONUSES)
        {
            query = 'SELECT ID, quarter__c, CurrencyISOCode, year__r.Sales_Rep__c,Start_Date__c, End_Date__c FROM Sales_Rep_Quarterly_Bonus__c';
        }      
        
    }        
    
    private Integer getQuarterFromDate(Date pD){
        if(pd.month()==1 || pd.month()==2 || pd.month()==3) return 1;
        if(pd.month()==4 || pd.month()==5 || pd.month()==6) return 2;
        if(pd.month()==7 || pd.month()==8 || pd.month()==9) return 3;
        if(pd.month()==10 || pd.month()==11 || pd.month()==12) return 4;
        return -1;
    }
    
    public Database.Querylocator start(Database.BatchableContext bc)
    {
        Integer year = proceedingDate.year();
        Integer quarter = getQuarterFromDate(proceedingDate);        
        return Database.getQuerylocator(query);
    } 
    
    public void execute(Database.BatchableContext bc, List<SObject> scope)
    {
        if (currentStep == CREATE_BONUSES && proceedingDate.day()==1 && proceedingDate.month()==1) {
            createAnnualBonuses((List<Commission_Profile__c>) scope);
        }  else if(currentStep == CALCULATE_BONUSES) {
                       calculateBonuses((List<Sales_Rep_Quarterly_Bonus__c>)scope);
                   }
    }    
    
    private void createAnnualBonuses(List<Commission_Profile__c> salesReps) {
        Integer year = proceedingDate.year();
        List<Sales_Rep_Annual_Bonus__c> years = new List<Sales_Rep_Annual_Bonus__c>();
        for(Commission_Profile__c rep: salesReps){
            years.add(new Sales_Rep_Annual_Bonus__c(Sales_Rep__c=rep.Id, year__c=year,
                                                    Unique_Id__c=year+'#'+rep.Id,
                                                    CurrencyISOCode=rep.CurrencyISOCode));
            Integer nextYear = year +1;
            years.add(new Sales_Rep_Annual_Bonus__c(Sales_Rep__c=rep.Id, year__c=nextYear,
                                                    Unique_Id__c=nextYear+'#'+rep.Id,
                                                    CurrencyISOCode=rep.CurrencyISOCode));
        }
        upsert years Unique_Id__c;
        createQuarterlyBonuses(years);
    }
    
    private void createQuarterlyBonuses(List<Sales_Rep_Annual_Bonus__c> years){        
        List<Sales_Rep_Quarterly_Bonus__c> quarters = new List<Sales_Rep_Quarterly_Bonus__c>();
        for(Sales_Rep_Annual_Bonus__c year: years) {
            quarters.add(new Sales_Rep_Quarterly_Bonus__c(quarter__c=1, year__c=year.Id,
                                                          Start_Date__c=Date.newInstance((integer)year.year__c,1,1),
                                                          End_date__c=Date.newInstance((integer)year.year__c,3,31),
                                                          Unique_Id__c='1#'+year.Id,
                                                          CurrencyISOCode=year.CurrencyISOCode));
            quarters.add(new Sales_Rep_Quarterly_Bonus__c(quarter__c=2, year__c=year.Id,
                                                          Start_Date__c=Date.newInstance((integer)year.year__c,4,1),
                                                          End_date__c=Date.newInstance((integer)year.year__c,6,30),
                                                          Unique_Id__c='2#'+year.Id,
                                                          CurrencyISOCode=year.CurrencyISOCode));
            quarters.add(new Sales_Rep_Quarterly_Bonus__c(quarter__c=3, year__c=year.Id,
                                                          Start_Date__c=Date.newInstance((integer)year.year__c,7,1),
                                                          End_date__c=Date.newInstance((integer)year.year__c,9,30),
                                                          Unique_Id__c='3#'+year.Id,
                                                          CurrencyISOCode=year.CurrencyISOCode));
            quarters.add(new Sales_Rep_Quarterly_Bonus__c(quarter__c=4, year__c=year.Id,
                                                          Start_Date__c=Date.newInstance((integer)year.year__c,10,1),
                                                          End_date__c=Date.newInstance((integer)year.year__c,12,31),
                                                          Unique_Id__c='4#'+year.Id,
                                                          CurrencyISOCode=year.CurrencyISOCode));            
        }
        upsert quarters Unique_ID__c;
    }
    
    private void calculateBonuses(List<Sales_Rep_Quarterly_Bonus__c> bonuses) {
            Map<Id,Average_Monthly_Currency_History__c> rates = new Map<Id,Average_Monthly_Currency_History__c>(
                [SELECT id, AUD__c, CAD__c, EUR__c,GBP__c, NZD__c, PLN__c, SGD__c, IDR__c, MXN__c, MYR__c, PHP__c,
                                               HKD__c, JPY__c, KRW__c, INR__c, THB__c, RUB__c 
                                               FROM Average_Monthly_Currency_History__c ]);

        for(Sales_Rep_Quarterly_Bonus__c bonus: bonuses){
            
            bonus.Gross_profit__c=0;
            for(Sales_Rep_MD__c md: [SELECT Id, Monthly_Distribution__r.Date__c, Monthly_Distribution__r.Actual_Gross_Profit__c,
                                     Monthly_Distribution__r.Average_Monthly_Currency_History__c,
                                     Sales_Rep__c, Sales_Rep__r.Bonus_GP__c, Monthly_Distribution__r.CurrencyISOCode,
                                     Sales_Rep__r.percentage_of_GP_allocation__c, Sales_Rep__r.CurrencyISOCode 
                                     FROM Sales_Rep_MD__c 
                                     WHERE Sales_Rep__r.Commission_Profile__c = : bonus.year__r.Sales_Rep__c
                                     AND Monthly_Distribution__r.Date__c>=:bonus.Start_Date__c
                                     AND Monthly_Distribution__r.Date__c<=:bonus.End_Date__c
                                     AND Sales_Rep__r.Bonus_GP__c!=null
                                     AND Monthly_Distribution__r.Actual_Gross_Profit__c!=null
                                     AND Sales_Rep__r.percentage_of_GP_allocation__c!=null]){
                                         
           		Decimal ratio = 1.0;
                if(bonus.CurrencyISOCode != md.Monthly_Distribution__r.CurrencyISOCode) {
                    Average_Monthly_Currency_History__c rate = rates.get(md.Monthly_Distribution__r.Average_Monthly_Currency_History__c);
                    Decimal ratioBonus = 1.0;
                    if(bonus.CurrencyISOCode!='USD') ratioBonus = (Decimal)rate.get(bonus.CurrencyISOCode+'__c');                    
                    Decimal ratioMD = 1.0;
                    if(md.Monthly_Distribution__r.CurrencyISOCode!='USD') ratioMD = (Decimal)rate.get(md.Monthly_Distribution__r.CurrencyISOCode+'__c');
	       	        ratio = 1.0 * ratioBonus/ratioMD;
                }
				bonus.Gross_profit__c+=md.Monthly_Distribution__r.Actual_Gross_Profit__c * md.Sales_Rep__r.percentage_of_GP_allocation__c / 100.0 * ratio;
        	}
            
            bonus.Gross_profit__c = bonus.Gross_profit__c.setScale(2);
        }
        update bonuses;
    }
    
    public void finish(Database.BatchableContext bc)
    {
        Iterator<String> iter = steps.iterator();
        while (iter.hasNext()) {
            String step = iter.next();
            if (step == currentStep && iter.hasNext()) {
                String nextStep = iter.next();
                Database.executeBatch(new SCH_BATCH_SalesRepBonusCalc(nextstep,proceedingDate), 10);
            }
        }
    }  
    
}