src/objects/Average_Monthly_Currency_History__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Average Monthly Currency History</label>
    <nameField>
        <label>Average Monthly Currency History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Average Monthly Currency Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CurrencyHistory__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Currency History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Currency History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MM_Spendings__c.object
<CustomObject>
    <fields>
        <fullName>Average_Monthly_Currency_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Average Monthly Currency History</label>
        <referenceTo>Average_Monthly_Currency_History__c</referenceTo>
        <relationshipLabel>Media Manager Spendings</relationshipLabel>
        <relationshipName>Media_Manager_Spendings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Media_Spend__c</fullName>
        <label>Media Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <formula>StrikeId__c &amp; &apos;_&apos; &amp; Contract__c &amp; &apos;_&apos; &amp; TEXT(Date__c) &amp; &apos;_&apos; &amp; TEXT(Delivered__c) &amp; &apos;_&apos; &amp; IF( 
BEGINS(TEXT(Media_Spend__c), &apos;.&apos;), 
&apos;0&apos; &amp; TEXT(Media_Spend__c), 
IF(CONTAINS(TEXT(Media_Spend__c), &apos;.&apos;), 
TEXT(Media_Spend__c) , 
TEXT(Media_Spend__c) &amp; &apos;.0&apos; ) 
) &amp; &apos;_&apos; &amp; IF(Is_Sync__c, &apos;1&apos;, &apos;0&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique ID</label>
        <type>Text</type>
    </fields>
    <label>Media Manager Spendings</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Media Manager Spendings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Manager Spendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Gross_Profit__c</fullName>
        <label>Actual Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Revenue_Rep__c</fullName>
        <formula>IF(Project__r.Project__r.No_of_sales_reps__c!=0,
   Actual_Revenue__c / Project__r.Project__r.No_of_sales_reps__c,
NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Revenue/Rep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Revenue__c</fullName>
        <label>Actual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Currency_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Average Monthly Currency History</label>
        <referenceTo>Average_Monthly_Currency_History__c</referenceTo>
        <relationshipLabel>Monthly Distributions</relationshipLabel>
        <relationshipName>Monthly_Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend_Rep__c</fullName>
        <formula>IF(Project__r.Project__r.No_of_sales_reps__c != 0,
Client_Spend__c / Project__r.Project__r.No_of_sales_reps__c,
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Spend/Rep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Revenue__c</fullName>
        <label>Expected Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Profit_Rep__c</fullName>
        <formula>IF(Project__r.Project__r.No_of_sales_reps__c!=0, 
   Actual_Gross_Profit__c / Project__r.Project__r.No_of_sales_reps__c,
NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Profit/Rep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Monthly Distribution</label>
    <nameField>
        <displayFormat>MD-{00000}</displayFormat>
        <label>MD Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Media_Spend__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Media Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Average_Monthly_Currency_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Average Monthly Currency History</label>
        <referenceTo>Average_Monthly_Currency_History__c</referenceTo>
        <relationshipLabel>Contract Media Spend</relationshipLabel>
        <relationshipName>Contract_Media_Spend</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Contract Media Spend</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Media Spend</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CalcAverageMonthlyExchangeRates.cls
global class CalcAverageMonthlyExchangeRates implements Database.Batchable <sObject>, Database.stateful, Schedulable
{
    public static final string CALCULATE_AVERAGE_EX_RATES     = 'Calculate average exchange rates';
    public static final string UPDATE_MONTHLY_DISTRIBUTION      = 'Update monthly distribution';
    public static final string UPDATE_MM_SPENDINGS    = 'Update media manager spendings';
    public static final string UPDATE_CONTRACT_MEDIA_SPEND    = 'Update contract media spends';
    
    Average_Monthly_Currency_History__c currentMonthAvgExchangeRates = new Average_Monthly_Currency_History__c();
    Date endMonthDate;
    Date startMonthDate;
    public static final List<string> steps = new List<string>{CALCULATE_AVERAGE_EX_RATES, UPDATE_MONTHLY_DISTRIBUTION,  UPDATE_MM_SPENDINGS, UPDATE_CONTRACT_MEDIA_SPEND};
        
        global string currentStep;
    private string query;
    
    global void execute(SchedulableContext ctx) 
    {        
        Database.executeBatch(new CalcAverageMonthlyExchangeRates(), 200);
    }   
    
    global CalcAverageMonthlyExchangeRates ()
    {
        this (steps [0], Date.today());
    }
    
    global CalcAverageMonthlyExchangeRates (Date eMD)
    {
        this (steps [0], eMD);
    }
    
    
    global CalcAverageMonthlyExchangeRates (String step,Date endDate)
    {
        endMonthDate=endDate;
        startMonthDate=Date.newInstance(endMonthDate.year(), endMonthDate.month(), 1);
        currentStep = step;
        
        if (currentStep == CALCULATE_AVERAGE_EX_RATES)
        {
            query = 'SELECT id, AUD__c, CAD__c, EUR__c,GBP__c, NZD__c, PLN__c, SGD__c, IDR__c, MXN__c, MYR__c, PHP__c,' +
                + 'HKD__c, JPY__c, KRW__c, INR__c, THB__c, RUB__c ' +
                ' FROM CurrencyHistory__c WHERE Date__c >=:startMonthDate AND Date__c<=:endMonthDate ORDER BY Date__c ASC';
        }
        else if (currentStep == UPDATE_MONTHLY_DISTRIBUTION)
        {
            query = 'SELECT ID, Actual_Gross_Profit__c, Actual_Revenue__c, Actual_Revenue_Rep__c, ' +
                + 'Client_Spend__c, Client_Spend_Rep__c, Expected_Gross_Profit__c, Expected_Revenue__c, ' +
                + 'Gross_Profit_Rep__c, Media_Order__c, CurrencyISOCode, Date__c  ' +
                + 'FROM Monthly_Distribution__c ORDER BY Date__c';
        }
        else if (currentStep == UPDATE_MM_SPENDINGS)
        {
            query = 'SELECT ID, Media_Spend__c, CurrencyISOCode, Date__c ' +
                + 'FROM MM_Spendings__c  ORDER BY Date__c';
        }      
        else if (currentStep == UPDATE_CONTRACT_MEDIA_SPEND)
        {
            query = 'SELECT ID, Amount__c, CurrencyISOCode, Date__c ' +
                + 'FROM Project_Media_Spend__c ORDER BY Date__c';
        }                          
    }
    
    
    global Database.Querylocator start(Database.BatchableContext bc)
    {
        return Database.getQuerylocator(query);
    } 
    
    global void execute(Database.BatchableContext bc, List<SObject> scope)
    {
        MMSpendingsHandler.skipProjectMediaSpendCreation=true;
        if (currentStep == CALCULATE_AVERAGE_EX_RATES)
        {
            calculateAverageExchangeRates ((List<CurrencyHistory__c>) scope);
        }
        else if (currentStep == UPDATE_MONTHLY_DISTRIBUTION || currentStep == UPDATE_MM_SPENDINGS || currentStep == UPDATE_CONTRACT_MEDIA_SPEND)
        {
            updateRecords(scope);
        } 
    }
    
    private void calculateAverageExchangeRates (List <CurrencyHistory__c> scope)
    {
        Map <String, Decimal> averageRates = new Map <String, Decimal> ();
        for (CurrencyHistory__c ch : scope)
        {
            averageRates.put ('AUD', averageRates.get ('AUD') == null ? ch.AUD__c : averageRates.get('AUD') + ch.AUD__c);
            averageRates.put ('CAD', averageRates.get ('CAD') == null ? ch.CAD__c : averageRates.get('CAD') + ch.CAD__c);
            averageRates.put ('EUR', averageRates.get ('EUR') == null ? ch.EUR__c : averageRates.get('EUR') + ch.EUR__c);
            averageRates.put ('GBP', averageRates.get ('GBP') == null ? ch.GBP__c : averageRates.get('GBP') + ch.GBP__c);
            averageRates.put ('NZD', averageRates.get ('NZD') == null ? ch.NZD__c : averageRates.get('NZD') + ch.NZD__c);
            averageRates.put ('PLN', averageRates.get ('PLN') == null ? ch.PLN__c : averageRates.get('PLN') + ch.PLN__c);
            averageRates.put ('SGD', averageRates.get ('SGD') == null ? ch.SGD__c : averageRates.get('SGD') + ch.SGD__c);
            averageRates.put ('IDR', averageRates.get ('IDR') == null ? ch.IDR__c : averageRates.get('IDR') + ch.IDR__c);
            averageRates.put ('MXN', averageRates.get ('MXN') == null ? ch.MXN__c : averageRates.get('MXN') + ch.MXN__c);
            averageRates.put ('MYR', averageRates.get ('MYR') == null ? ch.MYR__c : averageRates.get('MYR') + ch.MYR__c);
            averageRates.put ('PHP', averageRates.get ('PHP') == null ? ch.PHP__c : averageRates.get('PHP') + ch.PHP__c);
            averageRates.put ('HKD', averageRates.get ('HKD') == null ? ch.HKD__c : averageRates.get('HKD') + ch.HKD__c);
            averageRates.put ('JPY', averageRates.get ('JPY') == null ? ch.JPY__c : averageRates.get('JPY') + ch.JPY__c);
            averageRates.put ('KRW', averageRates.get ('KRW') == null ? ch.KRW__c : averageRates.get('KRW') + ch.KRW__c);
            averageRates.put ('INR', averageRates.get ('INR') == null ? ch.INR__c : averageRates.get('INR') + ch.INR__c);
            averageRates.put ('THB', averageRates.get ('THB') == null ? ch.THB__c : averageRates.get('THB') + ch.THB__c);
            averageRates.put ('RUB', averageRates.get ('RUB') == null ? ch.RUB__c : averageRates.get('RUB') + ch.RUB__c);            
        }
        
        for (String currencyName : averageRates.keySet())
        {
            averageRates.put (currencyName, averageRates.get(currencyName)/scope.size());
        }
        
        currentMonthAvgExchangeRates.Start_Date__c = startMonthDate;
        currentMonthAvgExchangeRates.End_Date__c = currentMonthAvgExchangeRates.Start_Date__c.addMonths(1).addDays(-1); 
        currentMonthAvgExchangeRates.Unique_ID__c=endMonthDate.year()+'-'+endMonthDate.month();
        currentMonthAvgExchangeRates.AUD__c = (Decimal)averageRates.get('AUD');
        currentMonthAvgExchangeRates.CAD__c  = (Decimal)averageRates.get('CAD');
        currentMonthAvgExchangeRates.EUR__c  = (Decimal)averageRates.get('EUR');
        currentMonthAvgExchangeRates.GBP__c  = (Decimal)averageRates.get('GBP');
        currentMonthAvgExchangeRates.NZD__c  = (Decimal)averageRates.get('NZD');
        currentMonthAvgExchangeRates.PLN__c  = (Decimal)averageRates.get('PLN');
        currentMonthAvgExchangeRates.SGD__c  = (Decimal)averageRates.get('SGD');
        currentMonthAvgExchangeRates.IDR__c  = (Decimal)averageRates.get('IDR');
        currentMonthAvgExchangeRates.MXN__c  = (Decimal)averageRates.get('MXN');
        currentMonthAvgExchangeRates.MYR__c  = (Decimal)averageRates.get('MYR');
        currentMonthAvgExchangeRates.PHP__c  = (Decimal)averageRates.get('PHP');
        currentMonthAvgExchangeRates.HKD__c  = (Decimal)averageRates.get('HKD');
        currentMonthAvgExchangeRates.JPY__c  = (Decimal)averageRates.get('JPY');
        currentMonthAvgExchangeRates.KRW__c  = (Decimal)averageRates.get('KRW');
        currentMonthAvgExchangeRates.INR__c  = (Decimal)averageRates.get('INR');
        currentMonthAvgExchangeRates.THB__c  = (Decimal)averageRates.get('THB');
        currentMonthAvgExchangeRates.RUB__c  = (Decimal)averageRates.get('RUB');
        
        upsert currentMonthAvgExchangeRates Unique_ID__c;
    }
    
    private void updateRecords(List <SObject> scope)
    {
        List<Average_Monthly_Currency_History__c> rates = [select id, start_date__c, End_date__c from Average_Monthly_Currency_History__c
                                                          ORDER BY Start_Date__c DESC];
        
        
        for (Sobject rec : scope)
        {
            Boolean found=false;
                for(Average_Monthly_Currency_History__c rate: rates){
                    if((Date)rec.get('Date__c')>= rate.Start_Date__c && (Date)rec.get('Date__c')<=rate.End_Date__c){
                        rec.put('Average_Monthly_Currency_History__c',rate.Id);
                        found=true;
                        break;
                    }
                }
            if(found==false) rec.put('Average_Monthly_Currency_History__c',rates[0].Id);
        }
        
        update scope;
    }
    
        
    global void finish(Database.BatchableContext bc)
    {
        Iterator<String> iter = steps.iterator();
        while (iter.hasNext()) {
            String step = iter.next();
            if (step == currentStep && iter.hasNext()) {
                String nextStep = iter.next();
                Database.executeBatch(new CalcAverageMonthlyExchangeRates(nextStep, endMonthDate), 200);
            }
        }
    }
}