src/objects/BillingCondition__c.object
<CustomObject>
    <label>Billing Condition</label>
    <nameField>
        <label>Billing Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Conditions</pluralLabel>
    <recordTypes>
        <fullName>Normal</fullName>
        <active>true</active>
        <label>Normal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MM_Spendings__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Media Manager Spendings</relationshipLabel>
        <relationshipName>Media_Manager_Spendings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Media Manager Spendings</relationshipLabel>
        <relationshipName>MediaManagerSpendings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StrikeId__c</fullName>
        <label>Project ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Media Manager Spendings</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Media Manager Spendings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Manager Spendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Condition</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>BillingCondition__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BillingCondition__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adwords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Reddit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                    <isActive>false</isActive>
                    <label>Instagram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platforms__c</fullName>
        <label>Platforms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>ContractPlatforms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>PlatformAccount__c</fullName>
        <label>Platform Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <formula>Payment__r.Billing_Conditions__c</formula>
        <label>Billing Condition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OpportunityPlatform__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Platform</label>
        <referenceTo>OpportunityPlatform__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StrikeId__c</fullName>
        <label>Project ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Platform__c.object
<CustomObject>
    <fields>
        <fullName>Prefix__c</fullName>
        <label>Prefix</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Condition</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>BillingCondition__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BillingCondition__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platforms__c</fullName>
        <label>Platforms</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpendRefreshDate__c</fullName>
        <label>Spend Refresh Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Client_Services_Rep__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Services Rep</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SpendRetrieveNotificationTest.cls
@isTest
public class SpendRetrieveNotificationTest {

	/*@isTest static void getResponseInvalidError() {
		TestHelper.createAppSettings();
		User usr = TestHelper.createUser();

		Id salesUserProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales User'].Id;
		Date oppStartDate = Date.newInstance(Date.today().year(), Date.today().addDays(-35).month(), 1);
		Integer endDateDifference = 45;
		BillingCondition__c billingCondition = TestHelper.getBillingCondition('Normal');
		Date firstSpendDate = Date.today().addDays(-4);
		Id clientServicesRepId = [SELECT Id FROM User WHERE Client_Services_Rep__c = true LIMIT 1].Id;

		Platform__c dbmtvPlatform = TestHelper.createPlatform('DBM TrueView', 'DT');
		insert TestHelper.platformsMap.values();

		Integer recordsAmount = 1;
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < recordsAmount; i++) {
			accounts.add(TestHelper.createAccount('TestAccount'+i, false));
		}
		insert accounts;

		List<Opportunity> opps = new List<Opportunity>();
		for (Integer i = 0; i < recordsAmount; i++) {
			opps.add(TestHelper.createOpportunity(usr, accounts[i], 'TestOpp'+i, salesUserProfileId, oppStartDate, endDateDifference, billingCondition));
		}
		insert opps;

		List<OpportunityPlatform__c> oppPlatforms = new List<OpportunityPlatform__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			OpportunityPlatform__c oppPlatform = TestHelper.createOpportunityPlatform(opps[i].Id, dbmtvPlatform);
			oppPlatform.PlatformAccount__c = DBMAPIMockResponse.ADVERTISERID + i;
			oppPlatforms.add(oppPlatform);
		}
		insert oppPlatforms;

		List<Project__c> contracts = new List<Project__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			Project__c contract = TestHelper.createContractNoInsert(accounts[i].Id, 'TestContract'+i, opps[i].Id);
			contract.Start_Date__c = Date.valueOf(firstSpendDate.year() + '-' + firstSpendDate.month() + '-01');
			contract.End_Date__c = contract.Start_Date__c.addDays(28); // simplify test for having one month for contract
			contract.SpendRefreshDate__c = contract.Start_Date__c;
			contract.ClientServicesRep__c = clientServicesRepId;
			contract.Platforms__c = dbmtvPlatform.Name;

			contracts.add(contract);
		}
		insert contracts;

		System.assertEquals(recordsAmount, [SELECT COUNT() FROM Project__c WHERE Opportunity__c IN :opps], 'There should be only ' + recordsAmount + ' contracts!');

		List<Payment__c> projects = [SELECT Id, PlatformPrefixText__c, StrikeId__c FROM Payment__c WHERE Project__c IN :contracts];
		for (Payment__c project :projects) {
			System.assertEquals(dbmtvPlatform.Prefix__c, project.PlatformPrefixText__c);
		}

		Integer monthBetween = contracts[0].Start_Date__c.monthsBetween(contracts[0].End_Date__c);
		System.assertEquals(recordsAmount * (monthBetween + 1), projects.size());
		System.assertEquals([SELECT COUNT() FROM MM_Spendings__c WHERE Contract__c IN :contracts], 0, 'No Spends should exist');

		for (Integer i = 0; i < recordsAmount; i++) {
			String advertiserId = DBMAPIMockResponse.ADVERTISERID + i;
			String customResponse = '[{"request_token_id":"e4b9ef938042d49c8f3db1e8b20bce36","metrics":[]}]';
			DBMAPIMockResponse.BATCH_RESPONSE.put(advertiserId, customResponse);
		}

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, DBMAPIMockResponse.getInstance());
		DBMSpendContractRetrieveBatch retrieveBatch = new DBMSpendContractRetrieveBatch();
		Database.executeBatch(retrieveBatch, recordsAmount);
		Test.stopTest();

		System.assertEquals(1, SpendRetrieveNotification.errorsMap.size(), 'Error should be thrown');
		if (SpendRetrieveNotification.errorsMap.size() == 1) {
			String firstMapKey = (new List<String>(SpendRetrieveNotification.errorsMap.keySet()))[0];
			List<String> errorsList = SpendRetrieveNotification.errorsMap.get(firstMapKey);
			for (String error :errorsList) {
				Boolean isErrorFound = false;
				for (Project__c contract :contracts) {
					isErrorFound |= error.contains(SpendRetrieveNotification.getContractLink(contract.Id));
				}
				System.assertEquals(isErrorFound, true, 'An error should contain Contact Link');
			}
		}
	}*/

	/*@isTest static void getNoDataReceivedError() {
		TestHelper.createAppSettings();
		User usr = TestHelper.createUser();

		Id salesUserProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales User'].Id;
		Date oppStartDate = Date.newInstance(Date.today().year(), Date.today().addDays(-35).month(), 1);
		Integer endDateDifference = 45;
		BillingCondition__c billingCondition = TestHelper.getBillingCondition('Normal');
		Date firstSpendDate = Date.today().addDays(-4);
		Id clientServicesRepId = [SELECT Id FROM User WHERE Client_Services_Rep__c = true LIMIT 1].Id;

		Platform__c dbmtvPlatform = TestHelper.createPlatform('DBM TrueView', 'DT');
		insert TestHelper.platformsMap.values();

		Integer recordsAmount = 1;
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < recordsAmount; i++) {
			accounts.add(TestHelper.createAccount('TestAccount'+i, false));
		}
		insert accounts;

		List<Opportunity> opps = new List<Opportunity>();
		for (Integer i = 0; i < recordsAmount; i++) {
			opps.add(TestHelper.createOpportunity(usr, accounts[i], 'TestOpp'+i, salesUserProfileId, oppStartDate, endDateDifference, billingCondition));
		}
		insert opps;

		List<OpportunityPlatform__c> oppPlatforms = new List<OpportunityPlatform__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			OpportunityPlatform__c oppPlatform = TestHelper.createOpportunityPlatform(opps[i].Id, dbmtvPlatform);
			oppPlatform.PlatformAccount__c = DBMAPIMockResponse.ADVERTISERID + i;
			oppPlatforms.add(oppPlatform);
		}
		insert oppPlatforms;

		List<Project__c> contracts = new List<Project__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			Project__c contract = TestHelper.createContractNoInsert(accounts[i].Id, 'TestContract'+i, opps[i].Id);
			contract.Start_Date__c = Date.valueOf(firstSpendDate.year() + '-' + firstSpendDate.month() + '-01');
			contract.End_Date__c = contract.Start_Date__c.addDays(28); // simplify test for having one month for contract
			contract.SpendRefreshDate__c = contract.Start_Date__c;
			contract.ClientServicesRep__c = clientServicesRepId;
			contract.Platforms__c = dbmtvPlatform.Name;

			contracts.add(contract);
		}
		insert contracts;

		System.assertEquals(recordsAmount, [SELECT COUNT() FROM Project__c WHERE Opportunity__c IN :opps], 'There should be only ' + recordsAmount + ' contracts!');

		List<Payment__c> projects = [SELECT Id, PlatformPrefixText__c, StrikeId__c FROM Payment__c WHERE Project__c IN :contracts];
		for (Payment__c project :projects) {
			System.assertEquals(dbmtvPlatform.Prefix__c, project.PlatformPrefixText__c);
		}

		Integer monthBetween = contracts[0].Start_Date__c.monthsBetween(contracts[0].End_Date__c);
		System.assertEquals(recordsAmount * (monthBetween + 1), projects.size());
		System.assertEquals([SELECT COUNT() FROM MM_Spendings__c WHERE Contract__c IN :contracts], 0, 'No Spends should exist');

		for (Integer i = 0; i < recordsAmount; i++) {
			String advertiserId = DBMAPIMockResponse.ADVERTISERID + i;
			String customResponse = '[]';
			DBMAPIMockResponse.BATCH_RESPONSE.put(advertiserId, customResponse);
		}

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, DBMAPIMockResponse.getInstance());
		DBMSpendContractRetrieveBatch retrieveBatch = new DBMSpendContractRetrieveBatch();
		Database.executeBatch(retrieveBatch, recordsAmount);
		Test.stopTest();

		System.assertEquals(1, SpendRetrieveNotification.errorsMap.size(), 'Error should be thrown');
		if (SpendRetrieveNotification.errorsMap.size() == 1) {
			String firstMapKey = (new List<String>(SpendRetrieveNotification.errorsMap.keySet()))[0];
			System.assert(firstMapKey.contains(SpendRetrieveNotification.ERR_NO_DATA_PATTERN));
			List<String> errorsList = SpendRetrieveNotification.errorsMap.get(firstMapKey);
			for (String error :errorsList) {
				Boolean isErrorFound = false;
				for (Project__c contract :contracts) {
					isErrorFound |= error.contains(SpendRetrieveNotification.getContractLink(contract.Id));
				}
				System.assertEquals(isErrorFound, true, 'An error should contain Contact Link');
			}
		}
	}*/

	/*@isTest static void getCurrencyDifferenceError() {
		TestHelper.createAppSettings();
		User usr = TestHelper.createUser();

		Id salesUserProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales User'].Id;
		Date oppStartDate = Date.newInstance(Date.today().year(), Date.today().addDays(-35).month(), 1);
		Integer endDateDifference = 45;
		BillingCondition__c billingCondition = TestHelper.getBillingCondition('Normal');
		Date firstSpendDate = Date.today().addDays(-4);
		Id clientServicesRepId = [SELECT Id FROM User WHERE Client_Services_Rep__c = true LIMIT 1].Id;

		Platform__c dbmtvPlatform = TestHelper.createPlatform('DBM TrueView', 'DT');
		insert TestHelper.platformsMap.values();

		Integer recordsAmount = 5;
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < recordsAmount; i++) {
			accounts.add(TestHelper.createAccount('TestAccount'+i, false));
		}
		insert accounts;

		List<Opportunity> opps = new List<Opportunity>();
		for (Integer i = 0; i < recordsAmount; i++) {
			opps.add(TestHelper.createOpportunity(usr, accounts[i], 'TestOpp'+i, salesUserProfileId, oppStartDate, endDateDifference, billingCondition));
		}
		insert opps;

		List<OpportunityPlatform__c> oppPlatforms = new List<OpportunityPlatform__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			OpportunityPlatform__c oppPlatform = TestHelper.createOpportunityPlatform(opps[i].Id, dbmtvPlatform);
			oppPlatform.PlatformAccount__c = DBMAPIMockResponse.ADVERTISERID + i;
			oppPlatforms.add(oppPlatform);
		}
		insert oppPlatforms;

		List<Project__c> contracts = new List<Project__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			Project__c contract = TestHelper.createContractNoInsert(accounts[i].Id, 'TestContract'+i, opps[i].Id);
			contract.Start_Date__c = Date.valueOf(firstSpendDate.year() + '-' + firstSpendDate.month() + '-01');
			contract.End_Date__c = contract.Start_Date__c.addDays(28); // simplify test for having one month for contract
			contract.SpendRefreshDate__c = contract.Start_Date__c;
			contract.ClientServicesRep__c = clientServicesRepId;
			contract.Platforms__c = dbmtvPlatform.Name;
			contract.CurrencyIsoCode = 'EUR';

			contracts.add(contract);
		}
		insert contracts;

		System.assertEquals(recordsAmount, [SELECT COUNT() FROM Project__c WHERE Opportunity__c IN :opps], 'There should be only ' + recordsAmount + ' contracts!');

		List<Payment__c> projects = [SELECT Id, PlatformPrefixText__c, StrikeId__c FROM Payment__c WHERE Project__c IN :contracts];
		for (Payment__c project :projects) {
			System.assertEquals(dbmtvPlatform.Prefix__c, project.PlatformPrefixText__c);
		}

		Integer monthBetween = contracts[0].Start_Date__c.monthsBetween(contracts[0].End_Date__c);
		System.assertEquals(recordsAmount * (monthBetween + 1), projects.size());
		System.assertEquals([SELECT COUNT() FROM MM_Spendings__c WHERE Contract__c IN :contracts], 0, 'No Spends should exist');

		for (Integer i = 0; i < recordsAmount; i++) {
			String advertiserId = DBMAPIMockResponse.ADVERTISERID + i;
			String customResponse = '[{' +
					'"impressions":3,' +
					'"views":0,' +
					'"clicks":0,' +
					'"engagements":0,' +
					'"spend":0.0,' +
					'"currency":"USD",' +
					'"cost_structure":"CPV",' +
					'"start_date":"' + parseDate(firstSpendDate) + '",' +
					'"end_date":"' + parseDate(firstSpendDate.addDays(10)) + '",' +
					'"delivered":0,' +
					'"advertiser_id":' + advertiserId + ',' +
					'"date":"' + parseDate(firstSpendDate) + '",' +
					'"signature":"[' + projects[i].StrikeId__c + ' - ' + Date.today().year() + '.' + Date.today().month() + '.21 - '+ Date.today().year() + '.' + Date.today().month() + '.31]",' +
					'"project_id":"' + projects[i].StrikeId__c + '"' +
					'}]';
			DBMAPIMockResponse.BATCH_RESPONSE.put(advertiserId, customResponse);
		}

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, DBMAPIMockResponse.getInstance());
		DBMSpendContractRetrieveBatch retrieveBatch = new DBMSpendContractRetrieveBatch();
		Database.executeBatch(retrieveBatch, recordsAmount);
		Test.stopTest();

		System.assertEquals(1, SpendRetrieveNotification.errorsMap.size(), 'Error should be thrown');
		if (SpendRetrieveNotification.errorsMap.size() == 1) {
			String firstMapKey = (new List<String>(SpendRetrieveNotification.errorsMap.keySet()))[0];
			System.assert(firstMapKey.contains(MMSpendingsRepository.CURR_ERR));
			List<String> errorsList = SpendRetrieveNotification.errorsMap.get(firstMapKey);
			for (String error :errorsList) {
				Boolean isErrorFound = false;
				for (Project__c contract :contracts) {
					isErrorFound |= error.contains(contract.Name);

				}
				System.assertEquals(isErrorFound, true, 'An error should contain information about Contact.');

				isErrorFound = false;
				for (Project__c contract :contracts) {
					isErrorFound |= error.contains(SpendRetrieveNotification.getContractLink(contract.Id));
				}
				System.assertEquals(isErrorFound, true, 'An error should contain Contact Link.');

				isErrorFound = false;
				for (Project__c contract :contracts) {
					isErrorFound |= error.contains(Contract.CurrencyIsoCode);
				}
				System.assertEquals(isErrorFound, true, 'An error should contain Contact CurrencyISOCode.');
			}
		}
	}*/

	/*@isTest static void getContractNotFoundError() {
		TestHelper.createAppSettings();
		User usr = TestHelper.createUser();

		Id salesUserProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales User'].Id;
		Date oppStartDate = Date.newInstance(Date.today().year(), Date.today().addDays(-35).month(), 1);
		Integer endDateDifference = 45;
		BillingCondition__c billingCondition = TestHelper.getBillingCondition('Normal');
		Date firstSpendDate = Date.today().addDays(-4);
		Id clientServicesRepId = [SELECT Id FROM User WHERE Client_Services_Rep__c = true LIMIT 1].Id;

		Platform__c dbmtvPlatform = TestHelper.createPlatform('DBM TrueView', 'DT');
		insert TestHelper.platformsMap.values();

		Integer recordsAmount = 5;
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < recordsAmount; i++) {
			accounts.add(TestHelper.createAccount('TestAccount'+i, false));
		}
		insert accounts;

		List<Opportunity> opps = new List<Opportunity>();
		for (Integer i = 0; i < recordsAmount; i++) {
			opps.add(TestHelper.createOpportunity(usr, accounts[i], 'TestOpp'+i, salesUserProfileId, oppStartDate, endDateDifference, billingCondition));
		}
		insert opps;

		List<OpportunityPlatform__c> oppPlatforms = new List<OpportunityPlatform__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			OpportunityPlatform__c oppPlatform = TestHelper.createOpportunityPlatform(opps[i].Id, dbmtvPlatform);
			oppPlatform.PlatformAccount__c = DBMAPIMockResponse.ADVERTISERID + i;
			oppPlatforms.add(oppPlatform);
		}
		insert oppPlatforms;

		List<Project__c> contracts = new List<Project__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			Project__c contract = TestHelper.createContractNoInsert(accounts[i].Id, 'TestContract'+i, opps[i].Id);
			contract.Start_Date__c = Date.valueOf(firstSpendDate.year() + '-' + firstSpendDate.month() + '-01');
			contract.End_Date__c = contract.Start_Date__c.addDays(28); // simplify test for having one month for contract
			contract.SpendRefreshDate__c = contract.Start_Date__c;
			contract.ClientServicesRep__c = clientServicesRepId;
			contract.Platforms__c = dbmtvPlatform.Name;
			contract.CurrencyIsoCode = 'EUR';

			contracts.add(contract);
		}
		insert contracts;

		System.assertEquals(recordsAmount, [SELECT COUNT() FROM Project__c WHERE Opportunity__c IN :opps], 'There should be only ' + recordsAmount + ' contracts!');

		List<Payment__c> projects = [SELECT Id, PlatformPrefixText__c, StrikeId__c FROM Payment__c WHERE Project__c IN :contracts];
		for (Payment__c project :projects) {
			System.assertEquals(dbmtvPlatform.Prefix__c, project.PlatformPrefixText__c);
		}

		Integer monthBetween = contracts[0].Start_Date__c.monthsBetween(contracts[0].End_Date__c);
		System.assertEquals(recordsAmount * (monthBetween + 1), projects.size());
		System.assertEquals([SELECT COUNT() FROM MM_Spendings__c WHERE Contract__c IN :contracts], 0, 'No Spends should exist');

		for (Integer i = 0; i < recordsAmount; i++) {
			String advertiserId = DBMAPIMockResponse.ADVERTISERID + i;
			String projectIdNotExisting = projects[i].StrikeId__c + i;
			String customResponse = '[{' +
					'"impressions":3,' +
					'"views":0,' +
					'"clicks":0,' +
					'"engagements":0,' +
					'"spend":0.0,' +
					'"currency":"USD",' +
					'"cost_structure":"CPV",' +
					'"start_date":"' + parseDate(firstSpendDate) + '",' +
					'"end_date":"' + parseDate(firstSpendDate.addDays(10)) + '",' +
					'"delivered":0,' +
					'"advertiser_id":' + advertiserId + ',' +
					'"date":"' + parseDate(firstSpendDate) + '",' +
					'"signature":"[' + projectIdNotExisting + ' - ' + Date.today().year() + '.' + Date.today().month() + '.21 - '+ Date.today().year() + '.' + Date.today().month() + '.31]",' +
					'"project_id":"' + projectIdNotExisting + '"' +
					'}]';
			DBMAPIMockResponse.BATCH_RESPONSE.put(advertiserId, customResponse);
		}

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, DBMAPIMockResponse.getInstance());
		DBMSpendContractRetrieveBatch retrieveBatch = new DBMSpendContractRetrieveBatch();
		Database.executeBatch(retrieveBatch, recordsAmount);
		Test.stopTest();

		System.assertEquals(1, SpendRetrieveNotification.errorsMap.size(), 'Error should be thrown');
		if (SpendRetrieveNotification.errorsMap.size() == 1) {
			String firstMapKey = (new List<String>(SpendRetrieveNotification.errorsMap.keySet()))[0];
			System.assert(firstMapKey.contains(MMSpendingsRepository.NO_CONTRACT));
			List<String> errorsList = SpendRetrieveNotification.errorsMap.get(firstMapKey);
			for (String error :errorsList) {
				Boolean isErrorFound = false;
				for (Payment__c project :projects) {
					isErrorFound |= error.contains(project.StrikeId__c);
				}
				System.assertEquals(isErrorFound, true, 'An error should contain information about Contact Name.');
			}
		}
	}*/

	/*@isTest static void getAccountDifferenceError() {
		TestHelper.createAppSettings();
		User usr = TestHelper.createUser();

		Id salesUserProfileId = [SELECT Id FROM Profile WHERE Name = 'Sales User'].Id;
		Date oppStartDate = Date.newInstance(Date.today().year(), Date.today().addDays(-35).month(), 1);
		Integer endDateDifference = 45;
		BillingCondition__c billingCondition = TestHelper.getBillingCondition('Normal');
		Date firstSpendDate = Date.today().addDays(-4);
		Id clientServicesRepId = [SELECT Id FROM User WHERE Client_Services_Rep__c = true LIMIT 1].Id;

		Platform__c dbmtvPlatform = TestHelper.createPlatform('DBM TrueView', 'DT');
		insert TestHelper.platformsMap.values();

		Integer recordsAmount = 5;
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < recordsAmount; i++) {
			accounts.add(TestHelper.createAccount('TestAccount'+i, false));
		}
		insert accounts;

		List<Opportunity> opps = new List<Opportunity>();
		for (Integer i = 0; i < recordsAmount; i++) {
			opps.add(TestHelper.createOpportunity(usr, accounts[i], 'TestOpp'+i, salesUserProfileId, oppStartDate, endDateDifference, billingCondition));
		}
		insert opps;

		List<OpportunityPlatform__c> oppPlatforms = new List<OpportunityPlatform__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			OpportunityPlatform__c oppPlatform = TestHelper.createOpportunityPlatform(opps[i].Id, dbmtvPlatform);
			oppPlatform.PlatformAccount__c = DBMAPIMockResponse.ADVERTISERID + i;
			oppPlatforms.add(oppPlatform);
		}
		insert oppPlatforms;

		List<Project__c> contracts = new List<Project__c>();
		for (Integer i = 0; i < recordsAmount; i++) {
			Project__c contract = TestHelper.createContractNoInsert(accounts[i].Id, 'TestContract'+i, opps[i].Id);
			contract.Start_Date__c = Date.valueOf(firstSpendDate.year() + '-' + firstSpendDate.month() + '-01');
			contract.End_Date__c = contract.Start_Date__c.addDays(28); // simplify test for having one month for contract
			contract.SpendRefreshDate__c = contract.Start_Date__c;
			contract.ClientServicesRep__c = clientServicesRepId;
			contract.Platforms__c = dbmtvPlatform.Name;
			contract.CurrencyIsoCode = 'USD';

			contracts.add(contract);
		}
		insert contracts;

		System.assertEquals(recordsAmount, [SELECT COUNT() FROM Project__c WHERE Opportunity__c IN :opps], 'There should be only ' + recordsAmount + ' contracts!');

		List<Payment__c> projects = [SELECT Id, PlatformPrefixText__c, StrikeId__c FROM Payment__c WHERE Project__c IN :contracts];
		for (Payment__c project :projects) {
			System.assertEquals(dbmtvPlatform.Prefix__c, project.PlatformPrefixText__c);
		}

		Integer monthBetween = contracts[0].Start_Date__c.monthsBetween(contracts[0].End_Date__c);
		System.assertEquals(recordsAmount * (monthBetween + 1), projects.size());
		System.assertEquals([SELECT COUNT() FROM MM_Spendings__c WHERE Contract__c IN :contracts], 0, 'No Spends should exist');

		for (Integer i = 0; i < recordsAmount; i++) {
			Integer incIndex = i + 10;
			String advertiserIdNonExisting = DBMAPIMockResponse.ADVERTISERID + incIndex;
			String advertiserId = DBMAPIMockResponse.ADVERTISERID + i;
			String projectId = projects[i].StrikeId__c;
			String customResponse = '[{' +
					'"impressions":3,' +
					'"views":0,' +
					'"clicks":0,' +
					'"engagements":0,' +
					'"spend":0.0,' +
					'"currency":"USD",' +
					'"cost_structure":"CPV",' +
					'"start_date":"' + parseDate(firstSpendDate) + '",' +
					'"end_date":"' + parseDate(firstSpendDate.addDays(10)) + '",' +
					'"delivered":0,' +
					'"advertiser_id":' + advertiserIdNonExisting + ',' +
					'"date":"' + parseDate(firstSpendDate) + '",' +
					'"signature":"[' + projectId + ' - ' + Date.today().year() + '.' + Date.today().month() + '.21 - '+ Date.today().year() + '.' + Date.today().month() + '.31]",' +
					'"project_id":"' + projectId + '"' +
				'}]';
			DBMAPIMockResponse.BATCH_RESPONSE.put(advertiserId, customResponse);
		}

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, DBMAPIMockResponse.getInstance());
		DBMSpendContractRetrieveBatch retrieveBatch = new DBMSpendContractRetrieveBatch();
		Database.executeBatch(retrieveBatch, recordsAmount);
		Test.stopTest();

		System.assertEquals(1, SpendRetrieveNotification.errorsMap.size(), 'Error should be thrown');
		if (SpendRetrieveNotification.errorsMap.size() == 1) {
			String firstMapKey = (new List<String>(SpendRetrieveNotification.errorsMap.keySet()))[0];
			System.assert(firstMapKey.contains(MMSpendingsRepository.DBM_ACCOUNT_ERR));
			List<String> errorsList = SpendRetrieveNotification.errorsMap.get(firstMapKey);
			for (String error :errorsList) {
				Boolean isErrorFound = false;
				for (Payment__c project :projects) {
					isErrorFound |= error.contains(project.StrikeId__c);
				}
				System.assertEquals(isErrorFound, true, 'An error should contain information about Contact Name.');

				isErrorFound = false;
				Integer i = 0;
				for (Payment__c project :projects) {
					Integer incIndex = i + 10;
					String advertiserIdNonExisting = DBMAPIMockResponse.ADVERTISERID + incIndex;
					isErrorFound |= error.contains(advertiserIdNonExisting);
					i++;
				}
				System.assertEquals(isErrorFound, true, 'An error should contain information about account that doesn\'t exist.');

				isErrorFound = false;
				i = 0;
				for (Payment__c project :projects) {
					String advertiserIdReal = DBMAPIMockResponse.ADVERTISERID + i;
					isErrorFound |= error.contains(advertiserIdReal);
					i++;
				}
				System.assertEquals(isErrorFound, true, 'An error should contain information about account that exists.');
			}
		}
	}*/

}