src/objects/BillingCondition__c.object
<CustomObject>
    <fields>
        <fullName>Default_Margin__c</fullName>
        <label>Default Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Rebate_Rate__c</fullName>
        <label>Rebate Rate %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Strike_Profit__c</fullName>
        <label>Strike Profit %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Billing Condition</label>
    <nameField>
        <label>Billing Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <formula>Payment__r.Billing_Conditions__c</formula>
        <label>Billing Condition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Status__c</fullName>
        <formula>IF( 
AND( Start_Date__c &lt;= TODAY(),TODAY() &lt;= End_Date__c) ,&quot;In Progress&quot;, 
IF(TODAY() &gt; End_Date__c,&quot;Finished&quot;, 
&quot;Planned&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rebate_Rate__c</fullName>
        <formula>Project__r.BillingCondition__r.Rebate_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rebate Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Strike_Profit__c</fullName>
        <formula>Project__r.BillingCondition__r.Strike_Profit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike Profit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Condition</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>BillingCondition__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BillingCondition__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Status__c</fullName>
        <formula>IF(
AND( Start_Date__c &lt;= TODAY(),TODAY() &lt;= End_Date__c) ,&quot;In Progress&quot;,
IF(TODAY() &gt; End_Date__c,&quot;Finished&quot;,
&quot;Planned&quot;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Strike_Profit__c</fullName>
        <formula>BillingCondition__r.Strike_Profit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike Profit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Status__c</fullName>
        <formula>IF( 
AND( Start_Date__c &lt;= TODAY(),TODAY() &lt;= End_Date__c) ,&quot;In Progress&quot;, 
IF(TODAY() &gt; End_Date__c,&quot;Finished&quot;, 
&quot;Planned&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BillingConditionHandler.cls
/**
 * Created by Pavel Lapitski on 2020-03-25.
 */

public with sharing class BillingConditionHandler implements ITrigger {

    public void bulkBefore() {}

    public void bulkAfter() {}

    public void beforeInsert(List<SObject> so) {}

    public void beforeUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {}

    public void beforeDelete(List<SObject> so) {}

    public void afterInsert(List<SObject> so) {}

    public void afterUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {

        Set<Id> changedBCIds = new Set<Id>();
        for (Id bcId :so.keySet()) {
            BillingCondition__c newBC = (BillingCondition__c) so.get(bcId), oldBC = (BillingCondition__c) oldSo.get(bcId);

            Boolean isRebateChanged = newBC.Rebate_Rate__c != oldBC.Rebate_Rate__c,
                    isRecordTypeChanged = newBC.RecordTypeId != oldBC.RecordTypeId,
                    isStrikeProfitChanged = newBC.Strike_Profit__c != oldBC.Strike_Profit__c,
                    isRebateRateChanged = newBC.Rebate_Rate__c != oldBC.Rebate_Rate__c,
                    isDefaultMarginChanged = newBC.Default_Margin__c != oldBC.Default_Margin__c;

            if (isRebateChanged || isRecordTypeChanged || isStrikeProfitChanged || isDefaultMarginChanged || isRebateRateChanged) {
                changedBCIds.add(bcId);
            }
        }

        // for all active campaigns (contracts) find projects to have invoice amount recalculated
        List<Payment__c> projects = [SELECT Id FROM Payment__c WHERE Project__r.Campaign_Status__c != 'Finished' AND End_Date__c > TODAY AND Payment__r.Checked__c = FALSE AND Project__r.BillingCondition__c IN :changedBCIds];
        update projects;
    }

    public void afterDelete(List<SObject> so) {}

    public void andFinally() {}

}