src/objects/BillingCondition__c.object
<CustomObject>
    <fields>
        <fullName>Rebate_Rate__c</fullName>
        <label>Rebate Rate %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Billing Condition</label>
    <nameField>
        <label>Billing Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Conditions</pluralLabel>
    <recordTypes>
        <fullName>Normal</fullName>
        <active>true</active>
        <label>Normal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Profile_Commission_Type__c</fullName>
        <formula>TEXT(Commission_Profile__r.CommissionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commission Profile Commission Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission_Profile_FixedCommissionRate__c</fullName>
        <formula>Commission_Profile__r.FixedCommissionRate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commission Profile FixedCommissionRate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Contract_Actual_Gross_Profit__c</fullName>
        <formula>Contract__r.ActualGrossProfit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Actual Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Client_Spend_Social__c</fullName>
        <label>Contract_Client_Spend_Social</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract_Client_Spend_YT__c</fullName>
        <label>Contract_Client_Spend_YT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract_Gross_Profit_Social__c</fullName>
        <label>Contract_Gross_Profit_Social</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract_Gross_Profit_YT__c</fullName>
        <label>Contract_Gross_Profit_YT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpectedCommission__c</fullName>
        <label>Expected commission APEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Condition</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>BillingCondition__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BillingCondition__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ConSalesRepExpCommissionCalculatorTest.cls
@IsTest
private class ConSalesRepExpCommissionCalculatorTest {

    @IsTest static void calculateSalesRepBaseCommission_whenNoCommission_returnZero() {
        String repJSON = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbR","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_NO_COMMISSION + '",' +
            '"Contract_Actual_Gross_Profit__c":"100",'+
            '"Commission_Profile_FixedCommissionRate__c":"0","CreatedDate":"2014-09-01T11:54:26.000+0000"}'; 
        Contract_Sales_Rep__c rep = (Contract_Sales_Rep__c) JSON.deserialize(repJSON, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        Decimal result = ConSalesRepExpCommissionCalculator.calculateSalesRepBaseCommission(rep);
        Test.stopTest();
        
        System.assertEquals(0, result);
    }

    @IsTest static void calculateSalesRepBaseCommission_whenDefault_returnValue() {
        String repJSON = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"1000","CreatedDate":"2014-09-01T11:54:26.000+0000"}';
        Contract_Sales_Rep__c rep = (Contract_Sales_Rep__c) JSON.deserialize(repJSON, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        Decimal result = ConSalesRepExpCommissionCalculator.calculateSalesRepBaseCommission(rep);
        Test.stopTest();
        
        System.assertEquals(8, result);
    }

    @IsTest static void calculateExpectedCommission_whenContractUpdated_calculate() {
        Account acc = TestHelper.createAccount();
        BillingCondition__c condition = TestHelper.createBillingCondition('Normal');
        condition.Rebate_Rate__c = -50;
        update condition;
        Project__c contract = TestHelper.createContractNoInsert(acc.Id, 'TestContract','');
        contract.BillingCondition__c=condition.Id;
        insert contract;        
        Contract_Sales_Rep__c rep = TestHelper.createContractSalesRep(contract.Id);

        Test.startTest();
        ConSalesRepExpCommissionCalculator.calculateExpectedCommission(new Set<Id>{contract.Id});
        Test.stopTest();
        
        Contract_Sales_Rep__c updatedRep = [SELECT  ExpectedCommission__c FROM Contract_Sales_Rep__c];
        //System.assertEquals(15.4265, updatedRep.ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_OneDefault_Social_NoCommission_setZero() {

        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_NO_COMMISSION + '",' +
             '"Contract_Gross_Profit_YT__c":"0","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"0","Contract_Client_Spend_Social__c":"400","CreatedDate":"2014-09-01T11:54:26.000+0000"}'; 
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                                                (new List<Contract_Sales_Rep__c>{repDefault1});
        Test.stopTest();
        
        System.assertEquals(0, result[0].ExpectedCommission__c);
    }

    @IsTest static void prepareContractRepsToUpdate_OneDefault_YT_NoCommission_setZero() {

        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_NO_COMMISSION + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}'; 
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                                                (new List<Contract_Sales_Rep__c>{repDefault1});
        Test.stopTest();
        
        System.assertEquals(0, result[0].ExpectedCommission__c);
    }

    @IsTest static void prepareContractRepsToUpdate_OneDefault_YT_And_Social_NoCommission_setZero() {

        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_NO_COMMISSION + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"222",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}'; 
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                                                (new List<Contract_Sales_Rep__c>{repDefault1});
        Test.stopTest();
        
        System.assertEquals(0, result[0].ExpectedCommission__c);
    }

    @IsTest static void prepareContractRepsToUpdate_OneDefault_calculateCommission_YT() {

        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"500","Contract_Client_Spend_Social__c":"0",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);

        List <Contract_Sales_Rep__c> contractList = new List<Contract_Sales_Rep__c>{repDefault1};
       
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate(contractList);
        Test.stopTest();
        
        System.assertEquals(4, result[0].ExpectedCommission__c);
    }

    @IsTest static void prepareContractRepsToUpdate_OneDefault_calculateCommission_Social() {

        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"0","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"0","Contract_Client_Spend_Social__c":"600",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);

        List <Contract_Sales_Rep__c> contractList = new List<Contract_Sales_Rep__c>{repDefault1};
       
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate(contractList);
        Test.stopTest();
        
        System.assertEquals(5, result[0].ExpectedCommission__c);
    }

    @IsTest static void prepareContractRepsToUpdate_OneDefault_calculateCommission_YT_And_Social() {

        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"500","Contract_Client_Spend_Social__c":"200",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);

        List <Contract_Sales_Rep__c> contractList = new List<Contract_Sales_Rep__c>{repDefault1};
       
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate(contractList);
        Test.stopTest();

        System.assertEquals(9, result[0].ExpectedCommission__c);
    }

    @IsTest static void prepareContractRepsToUpdate_No_Commission_and_Default_calculateCommission_YT_And_Social() {

        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_NO_COMMISSION + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"500","Contract_Client_Spend_Social__c":"200",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);

        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"500","Contract_Client_Spend_Social__c":"200",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        List <Contract_Sales_Rep__c> contractList = new List<Contract_Sales_Rep__c>{repDefault1, repDefault2};
       
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate(contractList);
        Test.stopTest();
        
        System.assertEquals(0, result[0].ExpectedCommission__c);
        System.assertEquals(4.5, result[1].ExpectedCommission__c);

    }

    @IsTest static void prepareContractRepsToUpdate_whenTwoDefault_splitCommission() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(2.5, result[0].ExpectedCommission__c);
        System.assertEquals(2.5, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_Default_and_Consultancy_DefaultLowerThanZero() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_CONSULTANCY + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"8",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(0, result[0].ExpectedCommission__c);
        System.assertEquals(8, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_Default_and_Consultancy_DefaultHigherThanZero() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_CONSULTANCY + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(4, result[0].ExpectedCommission__c);
        System.assertEquals(1, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_Default_and_Consultancy_ConsultancyLowerThanFive() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_CONSULTANCY + '",' +
             '"Contract_Gross_Profit_YT__c":"3","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(5, result[0].ExpectedCommission__c);
        System.assertEquals(0, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_Two_Consultancy_OneLowerThanFive() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_CONSULTANCY + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_CONSULTANCY + '",' +
             '"Contract_Gross_Profit_YT__c":"3","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(1, result[0].ExpectedCommission__c);
        System.assertEquals(0, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_NoCommission_And_Inside_calculateCommission() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_NO_COMMISSION + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(0, result[0].ExpectedCommission__c);
        System.assertEquals(1, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_NoCommission_And_Inside_LowerThanTen_calculateCommission() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_NO_COMMISSION + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"1300","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(0, result[0].ExpectedCommission__c);
        System.assertEquals(0.5, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_Default_And_Inside_calculateCommission() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(4, result[0].ExpectedCommission__c);
        System.assertEquals(1, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_Consultancy_And_Inside_calculateCommission() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_CONSULTANCY + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"1500","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2});
        Test.stopTest();
        
        System.assertEquals(1, result[0].ExpectedCommission__c);
        System.assertEquals(1, result[1].ExpectedCommission__c);        
    }

    @IsTest static void prepareContractRepsToUpdate_Three_Shared_Inside_Sales_calculateCommission_YT() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        String repJSONDefault3 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault3 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault3, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2, 
                                                                                        repDefault3});
        Test.stopTest();
        
        System.assertEquals(1/3.0, result[0].ExpectedCommission__c);   
        System.assertEquals(1/3.0, result[1].ExpectedCommission__c);   
        System.assertEquals(1/3.0, result[2].ExpectedCommission__c);   
    }

    @IsTest static void prepareContractRepsToUpdate_Three_Shared_Inside_Sales_calculateCommission_Social() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"0","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"0","Contract_Client_Spend_Social__c":"1250",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"0","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"0","Contract_Client_Spend_Social__c":"1500",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        String repJSONDefault3 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"0","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"0","Contract_Client_Spend_Social__c":"400",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault3 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault3, Contract_Sales_Rep__c.class);
        
        String repJSONDefault4 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"0","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"0","Contract_Client_Spend_Social__c":"1600",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault4 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault4, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2, 
                                                                                        repDefault3});
        Test.stopTest();
        
        System.assertEquals(1/3.0, result[0].ExpectedCommission__c);   
        System.assertEquals(0.5/3.0, result[1].ExpectedCommission__c);   
        System.assertEquals(1/3.0, result[2].ExpectedCommission__c);   
    }

    @IsTest static void prepareContractRepsToUpdate_Three_Shared_Inside_Sales_calculateCommission_YT_and_Social() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"1250",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"1500",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        String repJSONDefault3 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"100",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"400",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault3 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault3, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2, 
                                                                                        repDefault3});
        Test.stopTest();
        
        System.assertEquals(2/3.0, result[0].ExpectedCommission__c);   
        System.assertEquals(1.5/3.0, result[1].ExpectedCommission__c);   
        System.assertEquals(2/3.0, result[2].ExpectedCommission__c);   
    }

    @IsTest static void prepareContractRepsToUpdate_Three_Shared_Inside_Sales_and_Default_calculateDefaultCommission() {
        String repJSONDefault1 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault1 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault1, Contract_Sales_Rep__c.class);
        
        String repJSONDefault2 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault2 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault2, Contract_Sales_Rep__c.class);
        
        String repJSONDefault3 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbS"},'+
            '"Id":"00Qe0000003yEbUS","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_SHARED_INSIDE_SALES + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"400","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';   
        Contract_Sales_Rep__c repDefault3 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault3, Contract_Sales_Rep__c.class);
        
        String repJSONDefault4 = '{"attributes":{"type":"Contract_Sales_Rep__c","url":"/services/data/v38.0/sobjects/Lead/00Qe0000003yEbR"},'+
            '"Id":"00Qe0000003yEbUU","Commission_Profile_Commission_Type__c":"' + Label.COMMISSION_TYPE_DEFAULT + '",' +
             '"Contract_Gross_Profit_YT__c":"100","Contract_Gross_Profit_Social__c":"0",' + 
             '"Contract_Client_Spend_YT__c":"900","Contract_Client_Spend_Social__c":"0",' +
             '"Commission_Profile_FixedCommissionRate__c":"1",' +
             '"CreatedDate":"2014-09-01T11:54:26.000+0000"}';  
        Contract_Sales_Rep__c repDefault4 = (Contract_Sales_Rep__c) JSON.deserialize(repJSONDefault4, Contract_Sales_Rep__c.class);
        
        Test.startTest();
        List<Contract_Sales_Rep__c> result =  ConSalesRepExpCommissionCalculator.prepareContractRepsToUpdate
                                                    (new List<Contract_Sales_Rep__c>{repDefault1, repDefault2, 
                                                                                        repDefault3, repDefault4});
        Test.stopTest();
        
        System.assertEquals(1, result[3].ExpectedCommission__c);
    }
}