src/objects/BillingCondition__c.object
<CustomObject>
    <fields>
        <fullName>Default_Margin__c</fullName>
        <label>Default Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Rebate_Rate__c</fullName>
        <label>Rebate Rate %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Rebate_Type__c</fullName>
        <label>Rebate Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Instant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strike_Profit__c</fullName>
        <label>Strike Profit %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Billing Condition</label>
    <nameField>
        <label>Billing Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Conditions</pluralLabel>
    <recordTypes>
        <fullName>Normal</fullName>
        <active>true</active>
        <label>Normal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rebate</fullName>
        <active>true</active>
        <label>Rebate</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Condition</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>BillingCondition__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BillingCondition__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <inlineHelpText>Explain what the KPI means. What does the &quot;A&quot; mean in CPA (cost per acquisition)?</inlineHelpText>
        <label>KPI</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adwords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Reddit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                    <isActive>false</isActive>
                    <label>Instagram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>CTA_Overlay_Text__c</fullName>
        <label>CTA Overlay</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CostStructure__c</fullName>
        <label>Cost Structure</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPA</fullName>
                </value>
                <value>
                    <fullName>CPAC</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPE</fullName>
                </value>
                <value>
                    <fullName>CPER</fullName>
                </value>
                <value>
                    <fullName>CPF</fullName>
                </value>
                <value>
                    <fullName>CPI</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>CPLC</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPPL</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CPSU</fullName>
                </value>
                <value>
                    <fullName>CPV</fullName>
                </value>
                <value>
                    <fullName>CPLP</fullName>
                </value>
                <value>
                    <fullName>CPCO</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>CPDPV</fullName>
                </value>
                <value>
                    <fullName>CPCV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <label>KPI</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NoCostStructure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Cost Structure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Pixel_Tracking__c</fullName>
        <label>Tags</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Implemented</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <formula>Payment__r.Billing_Conditions__c</formula>
        <label>Billing Condition</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTA_Overlay_Text__c</fullName>
        <label>CTA Overlay</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <label>KPI</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OpportunityPlatform__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Platform</label>
        <referenceTo>OpportunityPlatform__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pixel_Tracking__c</fullName>
        <label>Tags</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Platform_Prefix__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Implemented</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rebate_Rate__c</fullName>
        <formula>Project__r.BillingCondition__r.Rebate_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rebate Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Strike_Profit__c</fullName>
        <formula>Project__r.BillingCondition__r.Strike_Profit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike Profit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>BillingCondition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Condition</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>BillingCondition__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>BillingCondition__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <label>KPI TO BE DELETED</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strike_Profit__c</fullName>
        <formula>BillingCondition__r.Strike_Profit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike Profit %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Sub_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GrossProfitCalculationTest.cls
/**
 * Created by pavel on 2020-07-29.
 */

@IsTest private class GrossProfitCalculationTest {

    private static BillingCondition__c rebateBC { get {
        if (rebateBC == null) {
            rebateBC = TestHelper.createBillingCondition('Rebate 10%/30%', false);
            rebateBC.Rebate_Rate__c = 10.00;
            rebateBC.Default_Margin__c = 30.00;
            rebateBC.Strike_Profit__c = 0;
            rebateBC.Rebate_Type__c = 'Normal';
            insert rebateBC;
        }
        return rebateBC;
    } set; }

    private static BillingCondition__c instantRebateBC { get {
        if (instantRebateBC == null) {
            instantRebateBC = TestHelper.createBillingCondition('Instant Rebate 50:50 / 50%', false);
            instantRebateBC.Rebate_Rate__c = null;
            instantRebateBC.Default_Margin__c = 50.00;
            instantRebateBC.Rebate_Type__c = 'Instant';
            instantRebateBC.Strike_Profit__c = 50.00;
            insert instantRebateBC;
        }
        return instantRebateBC;
    } set; }

    private static BillingCondition__c marginSplitBC { get {
        if (marginSplitBC == null) {
            marginSplitBC = TestHelper.createBillingCondition('Margin Split 50:50 / 30%', false);
            marginSplitBC.Rebate_Rate__c = 15.00;
            marginSplitBC.Default_Margin__c = 30.00;
            marginSplitBC.Strike_Profit__c = 50.00;
            marginSplitBC.Rebate_Type__c = 'Normal';
            insert marginSplitBC;
        }
        return marginSplitBC;
    } set; }

    private static Platform__c adWordPlatform { get {
        if (adWordPlatform == null) {
            adWordPlatform = TestHelper.createAdWordsPlatform();
            insert adWordPlatform;
        }
        return adWordPlatform;
    } set; }

    private static final Decimal CLIENT_SPEND = 100000;

    private static OpportunityPlatform__c createOpportunityPlatform_CPM_OR_NoCostStructure(Id oppId) {
        OpportunityPlatform__c oppPlatform = new OpportunityPlatform__c(Opportunity__c = oppId, Platform__c = adWordPlatform.Id, CTA_Overlay_Text__c = 'Text', Pixel_Tracking__c = 'Yes', KPI__c = 'KPI',
                NoCostStructure__c = true, CostStructure__c = '');
        insert oppPlatform;
        return oppPlatform;
    }

    // Instant Rebate billing condition
    @IsTest static void testGrossProfitCalculation_Custom1() {
        Decimal margin = instantRebateBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Client;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, instantRebateBC, CLIENT_SPEND, margin, '% of Media', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, instantRebateBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM1 MediaSpend: ' + project.AdWordsSpend__c + ' _ MediaOrder: ' + project.Media_Order__c);

        Decimal expectedActualRebate = (project.Client_Spend__c - project.AdWordsSpend__c) * (1 - instantRebateBC.Strike_Profit__c/100);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c);
        System.debug('### CUSTOM1 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
    }

    @IsTest static void testGrossProfitCalculation_Custom2() {
        Decimal margin = instantRebateBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Strike;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, instantRebateBC, CLIENT_SPEND, margin, '% of Media', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, instantRebateBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        Decimal expectedActualRebate = (project.Client_Spend__c - project.AdWordsSpend__c) * (1 - instantRebateBC.Strike_Profit__c/100);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c);
        System.debug('### CUSTOM2 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
    }

    @IsTest static void testGrossProfitCalculation_Custom3() {
        Decimal margin = instantRebateBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Client;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, instantRebateBC, CLIENT_SPEND, margin, '% of Budget', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, instantRebateBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        Decimal expectedActualRebate = (project.Client_Spend__c - project.AdWordsSpend__c) * (1 - instantRebateBC.Strike_Profit__c/100);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c);
        System.debug('### CUSTOM3 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
    }

    @IsTest static void testGrossProfitCalculation_Custom4() {
        Decimal margin = instantRebateBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Strike;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, instantRebateBC, CLIENT_SPEND, margin, '% of Budget', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, instantRebateBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        Decimal expectedActualRebate = (project.Client_Spend__c - project.AdWordsSpend__c) * (1 - instantRebateBC.Strike_Profit__c/100);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c);
        System.debug('### CUSTOM4 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
    }

    // Margin Split billing condition
    @IsTest static void testGrossProfitCalculation_Custom5() {
        Decimal margin = marginSplitBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Strike;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, marginSplitBC, CLIENT_SPEND, margin, '% of Budget', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, marginSplitBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM5 InvoiceAmount: ' + project.InvoiceAmount__c);
        Decimal expectedActualRebate = (project.InvoiceAmount__c - project.AdWordsSpend__c) * (1 - marginSplitBC.Strike_Profit__c/100);
        System.debug('### CUSTOM5 expectedActualRebate: ' + expectedActualRebate);
        System.debug('### CUSTOM5 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c.setScale(3));
    }

    @IsTest static void testGrossProfitCalculation_Custom6() {
        Decimal margin = marginSplitBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Strike;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, marginSplitBC, CLIENT_SPEND, margin, '% of Media', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, marginSplitBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM6 InvoiceAmount: ' + project.InvoiceAmount__c);
        Decimal expectedActualRebate = (project.InvoiceAmount__c - project.AdWordsSpend__c) * (1 - marginSplitBC.Strike_Profit__c/100);
        System.debug('### CUSTOM6 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c.setScale(3));
    }

    @IsTest static void testGrossProfitCalculation_Custom7() {
        Decimal margin = marginSplitBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Client;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, marginSplitBC, CLIENT_SPEND, margin, '% of Budget', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, marginSplitBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM7 InvoiceAmount: ' + project.InvoiceAmount__c);
        Decimal expectedActualRebate = project.InvoiceAmount__c * (1 - marginSplitBC.Strike_Profit__c/100);
        System.debug('### CUSTOM7 expectedActualRebate: ' + expectedActualRebate);
        System.debug('### CUSTOM7 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c.setScale(3));
    }

    @IsTest static void testGrossProfitCalculation_Custom8() {
        Decimal margin = marginSplitBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Client;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, marginSplitBC, CLIENT_SPEND, margin, '% of Media', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, marginSplitBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM8 InvoiceAmount: ' + project.InvoiceAmount__c);
        Decimal expectedActualRebate = project.InvoiceAmount__c * (1 - marginSplitBC.Strike_Profit__c/100);
        System.debug('### CUSTOM8 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c.setScale(3));
    }

    // Rebate billing condition
    @IsTest static void testGrossProfitCalculation_Custom9() {
        Decimal margin = rebateBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Strike;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, rebateBC, CLIENT_SPEND, margin, '% of Budget', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, rebateBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM9 InvoiceAmount: ' + project.InvoiceAmount__c);
        Decimal expectedActualRebate = CLIENT_SPEND * rebateBC.Rebate_Rate__c/100;
        System.debug('### CUSTOM9 expectedActualRebate: ' + expectedActualRebate);
        System.debug('### CUSTOM9 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c.setScale(3));
    }

    @IsTest static void testGrossProfitCalculation_Custom10() {
        Decimal margin = rebateBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Strike;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, rebateBC, CLIENT_SPEND, margin, '% of Media', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, rebateBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = 90000;

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM10 MediaSpend: ' + project.AdWordsSpend__c);
        Decimal expectedActualRebate = (project.AdWordsSpend__c + project.AdWordsSpend__c * margin/100) * rebateBC.Rebate_Rate__c/100;
        System.debug('### CUSTOM10 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c.setScale(3));
    }

    @IsTest static void testGrossProfitCalculation_Custom11() {
        Decimal margin = rebateBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Client;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, rebateBC, CLIENT_SPEND, margin, '% of Budget', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, rebateBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM11 InvoiceAmount: ' + project.InvoiceAmount__c + '   mediaSpend: ' + mediaSpend);
        Decimal expectedActualRebate = (project.InvoiceAmount__c / (margin/100)) * rebateBC.Rebate_Rate__c/100;
        System.debug('### CUSTOM11 expectedActualRebate: ' + expectedActualRebate);
        System.debug('### CUSTOM11 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c.setScale(3));
    }

    @IsTest static void testGrossProfitCalculation_Custom12() {
        Decimal margin = rebateBC.Default_Margin__c;
        Utility.BILLING_PROFILES billingProfile = Utility.BILLING_PROFILES.Client;

        Opportunity opp = TestHelper.createMeetingOppWithoutOppPlatform(billingProfile, rebateBC, CLIENT_SPEND, margin, '% of Media', true );
        createOpportunityPlatform_CPM_OR_NoCostStructure(opp.Id);

        opp.StageName = OpportunityRepository.STAGE_CLOSED_WON;
        update opp;

        // Verify Contract data
        Project__c contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        System.assertEquals(contract.BillingCondition__c, rebateBC.Id);
        System.assertEquals(contract.Account_Type__c, billingProfile.name());
        System.assertEquals(contract.Margin__c, margin);

        // Verify Payment data
        Sub_Project__c payment = contract.Sub_Projects__r[0];
        System.assertEquals(payment.Margin_Type__c, contract.Margin_Type__c);
        System.assertEquals(payment.Billing_Profile__c, contract.Account_Type__c);
        System.assertEquals(payment.Contract_Billing_Condition_Id__c, contract.BillingCondition__c);

        // Verify Project data
        Payment__c project = contract.Payments__r[0];
        System.assertEquals(contract.Margin_Type__c, project.Margin_Type__c);

        Integer delivered = 1;
        Decimal mediaSpend = CLIENT_SPEND * (1 - margin/100);

        Test.startTest();
        insert TestHelper.createMediaSpendings(contract.Id, project.End_Date__c, delivered, mediaSpend, adWordPlatform.Id, '');
        payment.Checked__c = true;
        update payment;
        Test.stopTest();

        contract = ContractRepository.getContractByOppIdWithPaymentsAndProjects(opp.Id);
        payment = contract.Sub_Projects__r[0];
        project = contract.Payments__r[0];

        System.debug('### CUSTOM6 InvoiceAmount: ' + project.InvoiceAmount__c);
        Decimal expectedActualRebate = (project.AdWordsSpend__c + project.InvoiceAmount__c) * rebateBC.Rebate_Rate__c/100;
        System.debug('### CUSTOM6 ActualRebate: ' + project.Actual_Rebate__c + ' ? ' + expectedActualRebate);
        System.assertEquals(expectedActualRebate.setScale(3), project.Actual_Rebate__c.setScale(3));
    }
}