src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand_Account__c.object
<CustomObject>
    <description>junction between brand and account</description>
    <fields>
        <fullName>Brand_Account__c</fullName>
        <formula>Brand__r.Name  &amp;&quot; / &quot;&amp;   Accounts__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand/Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Brand_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Brand/Account</label>
    <nameField>
        <label>Brand/Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand/Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_End__c</fullName>
        <inlineHelpText>The date that the campaign will finish.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Start__c</fullName>
        <inlineHelpText>The date that the campaign will start.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adwords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Reddit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                    <isActive>false</isActive>
                    <label>Instagram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Platform__c.object
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PerformMMSync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Given contract should be synchronized to MM.</description>
        <label>Perform MM Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sync_with_MM__c</fullName>
        <label>Sync with MM</label>
        <type>DateTime</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VideoUrl__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Video</fullName>
                    <default>true</default>
                    <label>Video</label>
                </value>
                <value>
                    <fullName>Carousel</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Page Post</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AdWords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Display Network</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salesforce_ID__c</fullName>
        <label>Salesforce_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Creative</label>
    <nameField>
        <label>Creative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VideoUrlHandlerTest.cls
@isTest
private class VideoUrlHandlerTest 
{
    static testMethod void willWillAssignToContractOnInsertWhenOpportunityDefined()
    {
        User usr = TestHelper.createUser();
        Account acc = TestHelper.createAccount();
        
        Opportunity opp = TestHelper.createOpportunity(usr, acc);        
        insert opp;
        
        Project__c contract = TestHelper.createContract(acc.Id, 'testContract', opp.Id);
        
        test.startTest();
        
            VideoUrl__c url = TestHelper.createVideoUrl();
            url.Opportunity__c = opp.Id;
       		url.Platform__c = 'TrueView';
	        url.Format__c = 'Video';
            url.StartDate__c = opp.Flight_Start__c;
            url.EndDate__c = opp.Flight_End__c;
            insert url;         
        
        test.stopTest();
        
        System.assertEquals(contract.Id, [SELECT Contract__c FROM VideoUrl__c WHERE Id = :url.Id].Contract__c);
    }
    
    static testMethod void willWillAssignToOpportunityOnInsertWhenContractDefined()
    {
        User usr = TestHelper.createUser();
        Account acc = TestHelper.createAccount();
        
        Opportunity opp = TestHelper.createOpportunity(usr, acc);
        insert opp;
        
        Project__c contract = TestHelper.createContract(acc.Id, 'testContract', opp.Id);
        
        test.startTest();
        
            VideoUrl__c url = TestHelper.createVideoUrl();
            url.Contract__c = contract.Id;
       		url.Platform__c = 'TrueView';
	        url.Format__c = 'Video';
            url.StartDate__c = opp.Flight_Start__c;
            url.EndDate__c = opp.Flight_End__c;
            insert url;         
        
        test.stopTest();
        
        System.assertEquals(opp.Id, [SELECT Opportunity__c FROM VideoUrl__c WHERE Id = :url.Id].Opportunity__c);
    }
    
    static testMethod void willSetPerformMMSyncOnInsert()
    {
        Account acc = TestHelper.createAccount();
        
        Project__c contractSynced = TestHelper.createContractNoInsert(acc.Id, 'syncedWithMM', NULL);
        contractSynced.Sync_with_MM__c = System.Now();
        Project__c contractNotSynced = TestHelper.createContractNoInsert(acc.Id, 'notSyncedWithMM', NULL);
        insert new List<Project__c> { contractSynced, contractNotSynced };
        
        contractSynced.PerformMMSync__c = false;
        update contractSynced;
        
        test.startTest();
            
            System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractSynced.Id].PerformMMSync__c);
            System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractNotSynced.Id].PerformMMSync__c);
            
            VideoUrl__c url1 = TestHelper.createVideoUrl();
            url1.Contract__c = contractSynced.Id;
       		url1.Platform__c = 'TrueView';
	        url1.Format__c = 'Video';
        	url1.StartDate__c = contractSynced.Start_Date__c;
            url1.EndDate__c = contractSynced.End_Date__c;
            
            VideoUrl__c url2 = TestHelper.createVideoUrl();
            url2.Contract__c = contractNotSynced.Id;
       		url2.Platform__c = 'TrueView';
	        url2.Format__c = 'Video';
        	url2.StartDate__c = contractNotSynced.Start_Date__c;
            url2.EndDate__c = contractNotSynced.End_Date__c;
            
            insert new List<VideoUrl__c> { url1, url2 };   
        
        test.stopTest();
        
        System.assertEquals(true, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractSynced.Id].PerformMMSync__c);
        System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractNotSynced.Id].PerformMMSync__c);
    }
    
    static testMethod void willSetPerformMMSyncOnUpdate()
    {
        Account acc = TestHelper.createAccount();
        
        Project__c contractSynced1 = TestHelper.createContractNoInsert(acc.Id, 'syncedWithMM', NULL);
        contractSynced1.Sync_with_MM__c = System.Now();
        
        Project__c contractSynced2 = TestHelper.createContractNoInsert(acc.Id, 'syncedWithMM', NULL);
        contractSynced2.Sync_with_MM__c = System.Now();
        
        Project__c contractNotSynced = TestHelper.createContractNoInsert(acc.Id, 'notSyncedWithMM', NULL);
        
        insert new List<Project__c> { contractSynced1, contractSynced2, contractNotSynced };
        
        test.startTest();

            VideoUrl__c url1 = TestHelper.createVideoUrl();
            url1.Contract__c = contractSynced1.Id;
       		url1.Platform__c = 'TrueView';
	        url1.Format__c = 'Video';
        	url1.StartDate__c = contractSynced1.Start_Date__c;
            url1.EndDate__c = contractSynced1.End_Date__c;
            
            VideoUrl__c url2 = TestHelper.createVideoUrl();
            url2.Contract__c = contractSynced2.Id;
       		url2.Platform__c = 'TrueView';
	        url2.Format__c = 'Video';
        	url2.StartDate__c = contractSynced2.Start_Date__c;
            url2.EndDate__c = contractSynced2.End_Date__c;
            
            VideoUrl__c url3 = TestHelper.createVideoUrl();
            url3.Contract__c = contractNotSynced.Id;
       		url3.Platform__c = 'TrueView';
	        url3.Format__c = 'Video';
        	url3.StartDate__c = contractNotSynced.Start_Date__c;
            url3.EndDate__c = contractNotSynced.End_Date__c;
            
            insert new List<VideoUrl__c> { url1, url2, url3 };  
            
            contractSynced1.PerformMMSync__c = false;
            contractSynced2.PerformMMSync__c = false;
            contractNotSynced.PerformMMSync__c = false;
        
            update new List<Project__c> {contractSynced1, contractSynced2, contractNotSynced};
        
            url1.Url__c += '123';
            url3.Url__c += '456';
            
            update new List<VideoUrl__c> { url1, url2, url3 };
        
        test.stopTest();
        
        System.assertEquals(true, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractSynced1.Id].PerformMMSync__c);
        System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractSynced2.Id].PerformMMSync__c);
        System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractNotSynced.Id].PerformMMSync__c);
    }
    
    static testMethod void willAssignSalesforceID() {
        Account acc          = TestHelper.createAccount();
        Brand__c brand             = TestHelper.createBrand('testBrand');
        Brand_Account__c brandAcc  = TestHelper.createBrandAccount(acc.Id, brand.Id);
        
        Project__c contract1 = TestHelper.createContractNoInsert(acc.Id, 'syncedWithMM', NULL);
        
        insert new List<Project__c> { contract1 };
            
            VideoUrl__c url1 = TestHelper.createVideoUrl();
            url1.Contract__c = contract1.Id;
       		url1.Platform__c = 'TrueView';
	        url1.Format__c = 'Video';
        	url1.StartDate__c = System.today();
            url1.EndDate__c = System.today()+1;
        	url1.Salesforce_ID__c = '906F00000008zgyIAA';
        Test.startTest();
        insert url1;
        Test.stopTest();
        
        url1 = [SELECT Salesforce_ID__c FROM VideoUrl__c WHERE Id = :url1.Id];
        
        //System.assert(!string.isBlank(url1.Salesforce_ID__c));
        //System.assertEquals(url1.Id, url1.Salesforce_ID__c);
    }
}