src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractPreLaunchCSRepNotifyCtrlTest.cls
@IsTest
private class ContractPreLaunchCSRepNotifyCtrlTest  {

    @IsTest private static void testDisplayLaunchingContracts() {
        Account acc = TestHelper.createAccount();
        User clientServicesRep = TestHelper.createClientServiceUser();

        insert TestHelper.brandRecord;
    
        //Correct
        Project__c contract1 = TestHelper.createContractNoInsert(acc.Id, 'testContract1', null);
        contract1.Start_Date__c = System.today().addDays(ContractRepository.preLaunchNotificationAdvance);
        contract1.End_Date__c = contract1.Start_Date__c.addDays(30);
        contract1.ClientServicesRep__c = clientServicesRep.Id;
        contract1.Brand__c = TestHelper.brandRecord.Id;
        
        //Wrong date
        Project__c contract2 = TestHelper.createContractNoInsert(acc.Id, 'testContract2', null);
        contract2.Start_Date__c = contract1.Start_Date__c.addDays(1);
        contract2.End_Date__c = contract2.Start_Date__c.addDays(30);
        contract2.ClientServicesRep__c = clientServicesRep.Id;
        contract2.Brand__c = TestHelper.brandRecord.Id;
        
        //No client service rep
        Project__c contract3 = TestHelper.createContractNoInsert(acc.Id, 'testContract3', null);
        contract3.Start_Date__c = contract1.Start_Date__c;
        contract3.End_Date__c = contract2.Start_Date__c.addDays(30);
        contract3.Brand__c = TestHelper.brandRecord.Id;

        //Correct
        Project__c contract4 = TestHelper.createContractNoInsert(acc.Id, 'testContract4', null);
        contract4.Start_Date__c = contract1.Start_Date__c;
        contract4.End_Date__c = contract4.Start_Date__c.addDays(60);
        contract4.ClientServicesRep__c = clientServicesRep.Id;
        contract4.Brand__c = TestHelper.brandRecord.Id;
        
        insert new List<Project__c> {contract1, contract2, contract3, contract4}; 
        
        Test.startTest();
        ContractPreLaunchCSRepNotifyCtrl controller = new ContractPreLaunchCSRepNotifyCtrl();
        controller.clientService = clientServicesRep.Id;
        List<Project__c> contracts = controller.getPreLaunchContracts();
        Test.stopTest();
        
        System.assertEquals(2, contracts.size());
        System.assertEquals(contract1.Id, contracts[0].Id);
        System.assertEquals(contract4.Id, contracts[1].Id);
    }
}