src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand_Account__c.object
<CustomObject>
    <description>junction between brand and account</description>
    <fields>
        <fullName>Brand_Account__c</fullName>
        <formula>Brand__r.Name  &amp;&quot; / &quot;&amp;   Accounts__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand/Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Brand_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Brand/Account</label>
    <nameField>
        <label>Brand/Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand/Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BrandAccountHandlerTest.cls
@isTest
public class BrandAccountHandlerTest {

    static testMethod void cannotCreateDuplicatedBrandAccount(){
        
        Account acc = TestHelper.createAccount();
        Brand__c brand = TestHelper.createBrand('testBrand');
        
		test.startTest();
        
        Boolean duplicateException = false;

        Brand_Account__c brandAcc1 = TestHelper.createBrandAccount(acc.Id, brand.Id);
        
        try {
            Brand_Account__c brandAcc2 = TestHelper.createBrandAccount(acc.Id, brand.Id);
        }
        catch (Exception ex) {
            duplicateException = true;            
        }
        
		test.stopTest();
		
        System.assert(duplicateException);
    }
}