src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Verticals__c</fullName>
        <label>Company Verticals</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adult Beverage</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>Baby &amp; Child Care (CPG)</fullName>
                </value>
                <value>
                    <fullName>Beverages (CPG)</fullName>
                </value>
                <value>
                    <fullName>Business &amp; Finance</fullName>
                </value>
                <value>
                    <fullName>Consumer App</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy &amp; Industrial Services</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Fitness</fullName>
                </value>
                <value>
                    <fullName>Food (CPG)</fullName>
                </value>
                <value>
                    <fullName>Gambling</fullName>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                </value>
                <value>
                    <fullName>Government &amp; Advocacy</fullName>
                </value>
                <value>
                    <fullName>Health &amp; Beauty (CPG)</fullName>
                </value>
                <value>
                    <fullName>Healthcare &amp; Insurance</fullName>
                </value>
                <value>
                    <fullName>Home &amp; Garden (CPG)</fullName>
                </value>
                <value>
                    <fullName>Household Appliances (CPG)</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>News &amp; Politics</fullName>
                </value>
                <value>
                    <fullName>Pets (CPG)</fullName>
                </value>
                <value>
                    <fullName>Photography, Publishing &amp; Art</fullName>
                </value>
                <value>
                    <fullName>QSR</fullName>
                </value>
                <value>
                    <fullName>Restaurants</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Science &amp; Technology</fullName>
                </value>
                <value>
                    <fullName>Sports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PerformMMSync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Given contract should be synchronized to MM.</description>
        <label>Perform MM Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sync_with_MM__c</fullName>
        <label>Sync with MM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Verticals__c</fullName>
        <label>Content Verticals</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Beauty</fullName>
                </value>
                <value>
                    <fullName>Beer</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Cooking</fullName>
                </value>
                <value>
                    <fullName>DIY</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Fitness</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Home &amp; Garden</fullName>
                </value>
                <value>
                    <fullName>Moms</fullName>
                </value>
                <value>
                    <fullName>Movies</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>News</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
                <value>
                    <fullName>Sports</fullName>
                </value>
                <value>
                    <fullName>Tech</fullName>
                </value>
                <value>
                    <fullName>Toys</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrandHandler.cls
public class BrandHandler implements ITrigger {
    public BrandHandler() {}
    
    public void bulkBefore() {}

    public void bulkAfter() {}

    public void beforeInsert(List<SObject> so) {}

    public void beforeUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {}
    
    public void beforeDelete(List<SObject> so) {}

    public void afterInsert(List<SObject> so) {}
    
    public void afterUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {
        Map<Id, Brand__c> oldMap = (Map<Id, Brand__c>)oldSo;
        Set<Id> updatedBrandIds = new Set<Id>();
        for (Brand__c brand :((Map<Id, Brand__c>)so).values()) {
            if (brand.Verticals__c != oldMap.get(brand.Id).Verticals__c) {
                updatedBrandIds.add(brand.Id);
            }
        }
        
        markForMMSync(updatedBrandIds);
    }
        
    public void afterDelete(List<SObject> so) {}

    public void andFinally() {}
    
    private static void markForMMSync(Set<Id> brandIds) {
        List<Project__c> contractsToSyncWithMM = new List<Project__c>();
        for (Project__c contract :[SELECT Id, PerformMMSync__c FROM Project__c WHERE Sync_with_MM__c != NULL AND PerformMMSync__c = false AND Brand__c IN :brandIds]) {
            contract.PerformMMSync__c = true;
            contractsToSyncWithMM.add(contract);
        }
        update contractsToSyncWithMM;
    }
}