src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CreditNote__c.object
<CustomObject>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MM_Spendings__c.object
<CustomObject>
    <fields>
        <fullName>Media_Spend__c</fullName>
        <label>Media Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Media Manager Spendings</relationshipLabel>
        <relationshipName>MediaManagerSpendings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media Manager Spendings</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Media Manager Spendings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Manager Spendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Billing Profile</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strike</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adwords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Reddit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                    <isActive>false</isActive>
                    <label>Instagram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>CostStructure__c</fullName>
        <label>Cost Structure</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPA</fullName>
                </value>
                <value>
                    <fullName>CPAC</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>CPE</fullName>
                </value>
                <value>
                    <fullName>CPER</fullName>
                </value>
                <value>
                    <fullName>CPF</fullName>
                </value>
                <value>
                    <fullName>CPI</fullName>
                </value>
                <value>
                    <fullName>CPL</fullName>
                </value>
                <value>
                    <fullName>CPLC</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CPPL</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>CPSU</fullName>
                </value>
                <value>
                    <fullName>CPV</fullName>
                </value>
                <value>
                    <fullName>CPLP</fullName>
                </value>
                <value>
                    <fullName>CPCO</fullName>
                </value>
                <value>
                    <fullName>CPVC</fullName>
                </value>
                <value>
                    <fullName>CPDPV</fullName>
                </value>
                <value>
                    <fullName>CPCV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Platform__c.object
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Billing Profile</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strike</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Billing Profile</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Maker</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Strike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InvoiceNotificationSent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Sub_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubProjectNotificationTest.cls
@isTest
private class SubProjectNotificationTest {

    private static Opportunity opp1;
    private static Opportunity opp2;
    private static Opportunity opp3;

    private static user clientServicesRep1;
    private static user clientServicesRep2;
    private static user clientServicesRep3;

    private static void closeOpportunities()
    {
        opp1.StageName = 'Closed Won';
        opp2.StageName = 'Closed Won';
        opp3.StageName = 'Closed Won';
        update new List<Opportunity> {opp1, opp2, opp3};
    }

    private static void setupCSReps()
    {
        clientServicesRep1 = TestHelper.createClientServiceUserNoInsert();
        clientServicesRep1.UserName += '1';
        clientServicesRep2 = TestHelper.createClientServiceUserNoInsert();
        clientServicesRep2.UserName += '2';
        clientServicesRep3 = TestHelper.createClientServiceUserNoInsert();
        clientServicesRep3.UserName += '3';
        insert new List<User> {clientServicesRep1, clientServicesRep2, clientServicesRep3};
    }
    
    private static void setupOpportunities()
    {
        Account acc = TestHelper.createAccount();
        Brand__c brand = TestHelper.createBrand('testBrand');
        User usr = TestHelper.createUser();
    
        opp1 = TestHelper.createOpportunity(usr, acc);  
        opp1.Account_Type__c = 'Client';
        opp1.Brand__c = brand.Id;
        opp1.ClientServicesRep__c = clientServicesRep1.Id;
        
        opp2 = TestHelper.createOpportunity(usr, acc);  
        opp2.Account_Type__c = 'Client';
        opp2.Brand__c = brand.Id;
        opp2.ClientServicesRep__c = clientServicesRep2.Id;
        
        opp3 = TestHelper.createOpportunity(usr, acc);  
        opp3.Account_Type__c = 'Client';
        opp3.Brand__c = brand.Id;
        opp3.ClientServicesRep__c = clientServicesRep3.Id;
    }
    
    private static void setupPlatforms()
    {
        Platform__c platformTV = TestHelper.getTrueViewPlatform();
        
        OpportunityPlatform__c opp1Platform = TestHelper.createOpportunityPlatform(opp1.Id, platformTV.Id);
        opp1Platform.CostStructure__c = 'CPV';
        OpportunityPlatform__c opp2Platform = TestHelper.createOpportunityPlatform(opp2.Id, platformTV.Id);
        opp2Platform.CostStructure__c = 'CPV';
        OpportunityPlatform__c opp3Platform = TestHelper.createOpportunityPlatform(opp3.Id, platformTV.Id);
        opp3Platform.CostStructure__c = 'CPV';
        
        insert new List<OpportunityPlatform__c> {opp1Platform, opp2Platform, opp3Platform}; 
    }

    static testMethod void willSendNotificationWhenLastMediaSpendDelivered()
    {
        Date today = System.today();
        
        TestHelper.createAppSettings();
        
        setupCSReps();
        
        setupOpportunities();
        
        insert new List<Opportunity> {opp1, opp2, opp3};
        
        setupPlatforms();
        
        closeOpportunities();
        
        Project__c contract1 = [SELECT Id FROM Project__c WHERE Opportunity__c = :opp1.Id];
        Project__c contract2 = [SELECT Id FROM Project__c WHERE Opportunity__c = :opp2.Id];
        
        Sub_Project__c payment1 = [SELECT Id, End_Date__c FROM Sub_Project__c WHERE Project__c = :contract1.Id LIMIT 1];
        Sub_Project__c payment2 = [SELECT Id, End_Date__c FROM Sub_Project__c WHERE Project__c = :contract2.Id LIMIT 1];
        
        CreditNote__c creditNote = TestHelper.createCreditNoteNoInsert(payment1.Id);
        insert creditNote;
        
        test.startTest();
        
            System.assertEquals(false, [SELECT InvoiceNotificationSent__c FROM Sub_Project__c WHERE Id = :payment1.Id].InvoiceNotificationSent__c);
            
            MM_Spendings__c mmSpending = TestHelper.createMediaSpendings(contract1.Id, payment1.End_Date__c);
            insert mmSpending;
        
            SubProjectNotification.sendPaymentsNotification();
        	SubProjectNotification.sendCreditNotesNotification();
        
        test.stopTest();
        
        System.assertEquals(true, [SELECT InvoiceNotificationSent__c FROM Sub_Project__c WHERE Id = :payment1.Id].InvoiceNotificationSent__c);
        System.assertEquals(false, [SELECT InvoiceNotificationSent__c FROM Sub_Project__c WHERE Id = :payment2.Id].InvoiceNotificationSent__c);
    }
    
    private static testMethod void testPrepareInvoiceNotifications() 
    {
        TestHelper.createAppSettings();

        setupCSReps();
        
        setupOpportunities();
        
        insert new List<Opportunity> {opp1, opp2, opp3};
        
        setupPlatforms();
        
        closeOpportunities();
        
        Project__c contract1 = [SELECT Id, End_Date__c, ClientServicesRep__c FROM Project__c WHERE Opportunity__c = :opp1.Id];
        Project__c contract2 = [SELECT Id, End_Date__c, ClientServicesRep__c FROM Project__c WHERE Opportunity__c = :opp2.Id];
        Project__c contract3 = [SELECT Id, End_Date__c, ClientServicesRep__c FROM Project__c WHERE Opportunity__c = :opp3.Id];
        
        test.startTest();
        
            System.assertNotEquals(contract1.ClientServicesRep__c, contract2.ClientServicesRep__c);
            System.assertNotEquals(contract2.ClientServicesRep__c, contract3.ClientServicesRep__c);
            
            MM_Spendings__c spend1 = TestHelper.createMediaSpendings(contract1.Id, contract1.End_Date__c);
            spend1.Media_Spend__c = 150000;
            MM_Spendings__c spend2 = TestHelper.createMediaSpendings(contract2.Id, contract2.End_Date__c);
            spend2.Media_Spend__c = 150000;
            
            insert new List<MM_Spendings__c> {spend1, spend2};
        
            List<Messaging.SingleEmailMessage> clientServiceNotifications = SubProjectNotification.getPaymentNotifications(new List<Contact>()); 
            
        test.stopTest();
        
        Set<String> whatIds = new Set<String>();
        
        for (Messaging.SingleEmailMessage message : clientServiceNotifications)
        {
            whatIds.add(message.getWhatId());
        }

        System.assertEquals(2, clientServiceNotifications.size());
        System.assert(whatIds.contains(clientServicesRep1.Id));
        System.assert(whatIds.contains(clientServicesRep2.Id));
        System.assert(!whatIds.contains(clientServicesRep3.Id));
    }
    
}