src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand_Account__c.object
<CustomObject>
    <description>junction between brand and account</description>
    <fields>
        <fullName>Accounts__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brand_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Brand_Account__c</fullName>
        <formula>Brand__r.Name  &amp;&quot; / &quot;&amp;   Accounts__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand/Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Brand_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Brand/Account</label>
    <nameField>
        <label>Brand/Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand/Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BrandAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand/Account</label>
        <referenceTo>Brand_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_End__c</fullName>
        <inlineHelpText>The date that the campaign will finish.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Start__c</fullName>
        <inlineHelpText>The date that the campaign will start.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrandAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand/Account</label>
        <referenceTo>Brand_Account__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsRunning__c</fullName>
        <formula>AND(Start_Date__c &lt;= TODAY(), End_Date__c &gt;= TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Running</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Opportunity__r.Strike_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sub_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <formula>Project__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Synced_with_Xero__c</fullName>
        <formula>ISBLANK(Xero_ID__c) == false</formula>
        <label>Synced with Xero</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PodDashboardCtrl.cls
global class PodDashboardCtrl {
    
    public String selectedAccount {get; set;}
    public String selectedBrand {get; set;}
    public String selectedClientServicesRep {get; set;}
    
    @RemoteAction
    global static List<ClientWrapper> getClients(Integer pageSize, Integer offset, String filter) {
        List<ClientWrapper> clients = new List<ClientWrapper>();
        Set<String> brandAccountIds = new Set<String>();
        Map<String, Object> filterMap = new Map<String, Object>();
        
        if (!string.isBlank(filter)){
            filterMap = (Map<String, Object>)JSON.deserializeUntyped(filter);
        }
        
        String query = ' SELECT Count(Id), Max(BrandAccount__c) BrandAccountId FROM Project__c WHERE Name != NULL AND BrandAccount__c != NULL ';
        
        for(String filteredField : filterMap.keySet())
        {
            query += ' AND ' + filterMap.get(filteredField);               
        }
        
        query += ' Group BY BrandAccount__r.Accounts__r.Name ORDER BY BrandAccount__r.Accounts__r.Name LIMIT :pageSize OFFSET :offset '; 
			        
        for (AggregateResult ar : Database.query(query))
        {
            brandAccountIds.add(String.valueOf(ar.get('BrandAccountId')));             
        }  
        
        for (Brand_Account__c brandAccount : getBrandAccountsById(brandAccountIds))
        {
            clients.add(new ClientWrapper(brandAccount));                
        }
        
        return clients;
    }
    
    @RemoteAction
    global static List<Sub_Project__c> readAwaitingPayments(Integer pageSize, Integer offset, String filter)
    {
        Map<String, Object> filterMap = new Map<String, Object>();
        Date paymentEndDate = System.Today().addDays(-5);
        Date paymentsEarliestDate = Date.newInstance(2016, 1, 1);
    
        if (!string.isBlank(filter)) {
            filterMap = (Map<String, Object>)JSON.deserializeUntyped(filter);
        }
    
        String query = ' SELECT Id, Invoice_Amount__c, End_Date__c, Name, Project__c, Project__r.Name, Project__r.Account__c, Project__r.Account__r.Name, ';
        query += ' ProjectID__c, Start_Date__c ';
        query += ' FROM Sub_Project__c ';
        query += ' WHERE End_Date__c <= :paymentEndDate AND  End_Date__c > :paymentsEarliestDate AND Synced_with_Xero__c = false ';
        
        for(String filteredField : filterMap.keySet())
        {
            query += ' AND Project__r.' + filterMap.get(filteredField);               
        }
        
        query += ' ORDER BY Project__r.Name ASC LIMIT :pageSize OFFSET :offset ';
        
        return Database.query(query);
    }
    
    @RemoteAction
    global static List<Project__c> readMyContracts(Integer pageSize, Integer offset, String filter)
    {
        Map<String, Object> filterMap = new Map<String, Object>();
    
        if (!string.isBlank(filter)) {
            filterMap = (Map<String, Object>)JSON.deserializeUntyped(filter);
        }
    
        String query = ' SELECT Id, Client_Spend__c, End_Date__c, isRunning__c, Name, Account__c, Account__r.Name, Project_ID__c, Start_Date__c FROM Project__c ';
        query += ' WHERE End_Date__c >= TODAY ';
        
        for(String filteredField : filterMap.keySet())
        {
            query += ' AND ' + filterMap.get(filteredField);               
        }
        
        query += ' ORDER BY Name LIMIT :pageSize OFFSET :offset ';
        
        return Database.query(query);
    }
    
    @RemoteAction
    global static List<Opportunity> readMyOpportunities(Integer pageSize, Integer offset, String filter)
    {
        Map<String, Object> filterMap = new Map<String, Object>();
        String stageWon = 'Closed Won';
        String stageLost = 'Closed Lost';
    
        if (!string.isBlank(filter)) {
            filterMap = (Map<String, Object>)JSON.deserializeUntyped(filter);
        }
    
        String query = ' SELECT Id, Amount, Name, AccountId, Account.Name, CloseDate, Flight_End__c, Flight_Start__c, StageName ';
        query += ' FROM Opportunity ';
        query += ' WHERE StageName != :stageWon AND StageName != :stageLost ';
        
        for(String filteredField : filterMap.keySet())
        {
            query += ' AND ' + filterMap.get(filteredField);               
        }
        
        query += ' ORDER BY Name LIMIT :pageSize OFFSET :offset ';
        
        return Database.query(query);
    }
    
    @RemoteAction
    global static ClientWrapper readContracts(String clientId) {
        
        Brand_Account__c brandAccount = getDataForBrandAccount(clientId);
        
        ClientWrapper retVal = new ClientWrapper(brandAccount); 
        
        return retVal;
    }
    
    private static Brand_Account__c getDataForBrandAccount(String clientId)
    {
         return [SELECT Accounts__c, Accounts__r.Name, Brand__c, Brand__r.Name,
                       (SELECT Id, CurrencyIsoCode, Name, Start_Date__c, End_Date__c, Client_Spend__c, Project_ID__c
                        FROM Contracts__r 
                        WHERE Start_Date__c <= TODAY AND End_Date__c >= TODAY),
                       (SELECT Id, CurrencyIsoCode, Name, Amount, CloseDate, Flight_Start__c, Flight_End__c 
                        FROM Opportunities__r 
                        WHERE StageName != 'Closed Won' AND StageName != 'Closed Lost')
                FROM Brand_Account__c 
                WHERE Id = :clientId];          
    }
    
    private static List<Brand_Account__c> getBrandAccountsById(Set<String> brandAccountIds)
    {
        return [SELECT Accounts__c, Accounts__r.Name, Brand__c, Brand__r.Name,
                       (SELECT Id
                        FROM Contracts__r 
                        WHERE Start_Date__c <= TODAY AND End_Date__c >= TODAY
                        LIMIT 1),
                       (SELECT Id
                        FROM Opportunities__r 
                        WHERE StageName != 'Closed Won' AND StageName != 'Closed Lost'
                        LIMIT 1)
                FROM Brand_Account__c 
                WHERE Id IN :brandAccountIds
                ORDER BY Accounts__r.Name];           
    }
    
    global class ClientWrapper
    {
        public Brand_Account__c client {get; set;}
        public Boolean isActive {get; set;}
        public List<Project__c> contracts {get; set;}
        public List<Opportunity> opportunities {get; set;}
        
        public ClientWrapper(Brand_Account__c brandAccount)
        {
            contracts = new List<Project__c>();
            opportunities = new List<Opportunity>();
            client = brandAccount;
            isActive = !brandAccount.Contracts__r.isEmpty() || !brandAccount.Opportunities__r.isEmpty();
            
            if (!brandAccount.Contracts__r.isEmpty())
            {
                contracts.addAll(brandAccount.Contracts__r);                   
            }
            
            if (!brandAccount.Opportunities__r.isEmpty())
            {
                opportunities.addAll(brandAccount.Opportunities__r);                      
            }
        }
    }
}