src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Verticals__c</fullName>
        <label>Company Verticals</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adult Beverage</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>Baby &amp; Child Care (CPG)</fullName>
                </value>
                <value>
                    <fullName>Beverages (CPG)</fullName>
                </value>
                <value>
                    <fullName>Business &amp; Finance</fullName>
                </value>
                <value>
                    <fullName>Consumer App</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy &amp; Industrial Services</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Fitness</fullName>
                </value>
                <value>
                    <fullName>Food (CPG)</fullName>
                </value>
                <value>
                    <fullName>Gambling</fullName>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                </value>
                <value>
                    <fullName>Government &amp; Advocacy</fullName>
                </value>
                <value>
                    <fullName>Health &amp; Beauty (CPG)</fullName>
                </value>
                <value>
                    <fullName>Healthcare &amp; Insurance</fullName>
                </value>
                <value>
                    <fullName>Home &amp; Garden (CPG)</fullName>
                </value>
                <value>
                    <fullName>Household Appliances (CPG)</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>News &amp; Politics</fullName>
                </value>
                <value>
                    <fullName>Pets (CPG)</fullName>
                </value>
                <value>
                    <fullName>Photography, Publishing &amp; Art</fullName>
                </value>
                <value>
                    <fullName>QSR</fullName>
                </value>
                <value>
                    <fullName>Restaurants</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Science &amp; Technology</fullName>
                </value>
                <value>
                    <fullName>Sports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PerformMMSync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Given contract should be synchronized to MM.</description>
        <label>Perform MM Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sync_with_MM__c</fullName>
        <label>Sync with MM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Verticals__c</fullName>
        <label>Content Verticals</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Beauty</fullName>
                </value>
                <value>
                    <fullName>Beer</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Cooking</fullName>
                </value>
                <value>
                    <fullName>DIY</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Fashion</fullName>
                </value>
                <value>
                    <fullName>Fitness</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Gaming</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Home &amp; Garden</fullName>
                </value>
                <value>
                    <fullName>Moms</fullName>
                </value>
                <value>
                    <fullName>Movies</fullName>
                </value>
                <value>
                    <fullName>Music</fullName>
                </value>
                <value>
                    <fullName>News</fullName>
                </value>
                <value>
                    <fullName>Pets</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
                <value>
                    <fullName>Sports</fullName>
                </value>
                <value>
                    <fullName>Tech</fullName>
                </value>
                <value>
                    <fullName>Toys</fullName>
                </value>
                <value>
                    <fullName>Travel</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrandHandlerTest.cls
@isTest
private class BrandHandlerTest {

    @IsTest static void willSetPerformMMSyncOnUpdate() {
        Account acc = TestHelper.createAccount();
        Date nextMonth = System.today().addMonths(1);
        Brand__c brand1 = TestHelper.createBrand('testBrand1', false);
        Brand__c brand2 = TestHelper.createBrand('testBrand2', false);
        Brand__c brand3 = TestHelper.createBrand('testBrand3', false);
        insert new List<Brand__c> {brand1, brand2, brand3};
        
        Project__c contractSynced1 = TestHelper.createContractNoInsert(acc.Id, 'syncedWithMM', null);
        contractSynced1.Brand__c = brand1.Id;
        contractSynced1.Start_Date__c = Date.newInstance(nextMonth.year(), nextMonth.month(), 1);
        contractSynced1.End_Date__c = contractSynced1.Start_Date__c.addMonths(1).addDays(-1);
        contractSynced1.Sync_with_MM__c = System.now();
        
        Project__c contractSynced2 = TestHelper.createContractNoInsert(acc.Id, 'syncedWithMM', null);
        contractSynced2.Brand__c = brand2.Id;
        contractSynced2.Start_Date__c = contractSynced1.Start_Date__c;
        contractSynced2.End_Date__c = contractSynced1.End_Date__c;
        contractSynced2.Sync_with_MM__c = System.now();
        
        Project__c contractNotSynced = TestHelper.createContractNoInsert(acc.Id, 'notSyncedWithMM', null);
        contractNotSynced.Brand__c = brand3.Id;
        contractNotSynced.Start_Date__c = contractSynced1.Start_Date__c;
        contractNotSynced.End_Date__c = contractSynced1.End_Date__c;
        
        insert new List<Project__c> { contractSynced1, contractSynced2, contractNotSynced };
        
        Test.startTest();
            update [SELECT Id FROM Brand__c];
            
            contractSynced1.PerformMMSync__c = false;
            contractSynced2.PerformMMSync__c = false;
            contractNotSynced.PerformMMSync__c = false;
            update new List<Project__c> {contractSynced1, contractSynced2, contractNotSynced};
            
            brand1.Verticals__c = 'Beauty';
            brand3.Verticals__c = 'Retail';
            System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractSynced1.Id].PerformMMSync__c);
            System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractSynced2.Id].PerformMMSync__c);
            System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractNotSynced.Id].PerformMMSync__c);
            update new List<Brand__c> { brand1, brand2, brand3 };
        Test.stopTest();

        System.assertEquals(true, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractSynced1.Id].PerformMMSync__c);
        System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractSynced2.Id].PerformMMSync__c);
        System.assertEquals(false, [SELECT PerformMMSync__c FROM Project__c WHERE Id = :contractNotSynced.Id].PerformMMSync__c);
    }
}