src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sales Reps</relationshipLabel>
        <relationshipName>Sales_Reps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Gross_Profit__c</fullName>
        <label>Actual Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Revenue__c</fullName>
        <label>Actual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Monthly_Distribution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContractID__c</fullName>
        <formula>Project__r.Payment__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContractID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <formula>Project__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Revenue__c</fullName>
        <label>Expected Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Monthly Distributions</relationshipLabel>
        <relationshipName>Monthly_Distribution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Monthly Distribution</label>
    <nameField>
        <displayFormat>MD-{00000}</displayFormat>
        <label>MD Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Gross_Profit_New__c</fullName>
        <label>Actual Gross Profit New</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Revenue__c</fullName>
        <formula>IF(Payment__r.Synced_with_Xero__c || !ISPICKVAL( Payment__r.XeroStatus__c,&quot;&quot;),
   InvoiceAmount__c,
Expected_Revenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ContractId__c</fullName>
        <formula>Payment__r.Project__c</formula>
        <label>Contract Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Running__c</fullName>
        <formula>End_Date__c - Start_Date__c +1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Running</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit_New__c</fullName>
        <label>Expected Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <formula>IF (ISPICKVAL(Project__r.BillingCondition__r.Rebate_Type__c,&quot;Instant&quot;),
  (Client_Spend__c - Media_Order__c) * (1 - Project__r.BillingCondition__r.Rebate_Rate__c),
  (Client_Spend__c - Media_Order__c) - (Client_Spend__c * Project__r.BillingCondition__r.Rebate_Rate__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Gross Profit OLD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Revenue__c</fullName>
        <formula>IF(Account_Type__c = &quot;Client&quot;, 
   Client_Spend__c - Media_Order__c, 
Client_Spend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <formula>IF(ISPICKVAL(Margin_Type__c,&apos;% of Media&apos;),
   Client_Spend__c / (1+Margin__c),
   Client_Spend__c * (1-Margin__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Gross_Profit__c</fullName>
        <label>Actual Gross Profit No Rebate Rollup</label>
        <summarizedField>Sub_Project__c.ActualGrossProfitCopy__c</summarizedField>
        <summaryForeignKey>Sub_Project__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_running__c</fullName>
        <formula>End_Date__c - Start_Date__c +1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days running</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <summarizedField>Sub_Project__c.Expected_Gross_Profit__c</summarizedField>
        <summaryForeignKey>Sub_Project__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <formula>IF(ISPICKVAL(Margin_Type__c,&apos;% of Media&apos;),
Client_Spend__c / (1+Margin__c),
Client_Spend__c * (1-Margin__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Rep_MD__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <formula>Monthly_Distribution__r.Client_Spend__c * Sales_Rep__r.Commission_Percentage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Distribution__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Monthly Distribution</label>
        <referenceTo>Monthly_Distribution__c</referenceTo>
        <relationshipLabel>Sales Rep Monthly Distributions</relationshipLabel>
        <relationshipName>Sales_Rep_MDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>Contract_Sales_Rep__c</referenceTo>
        <relationshipName>Sales_Rep_MDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Rep Monthly Distribution</label>
    <nameField>
        <displayFormat>SRMD-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <formula>HYPERLINK( &apos;https://strike.my.salesforce.com/&apos;&amp;Project__r.Id , Project__r.Name  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_running__c</fullName>
        <formula>End_Date__c - Start_Date__c +1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days running</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <summarizedField>Payment__c.Expected_Gross_Profit_New__c</summarizedField>
        <summaryForeignKey>Payment__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <formula>IF(ISPICKVAL(Margin_Type__c,&apos;% of Media&apos;),
   Client_Spend__c / (1+Margin__c),
   Client_Spend__c * (1-Margin__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MonthlyDistribution.cls
public class MonthlyDistribution {

    public static void assignMonthlyDistributionToSalesRep(List<Monthly_Distribution__c> monthlyDistributions) {
        Map<Id, List<Monthly_Distribution__c>> monthlyDistributionsForContracts = new Map<Id, List<Monthly_Distribution__c>>();
        for (Monthly_Distribution__c monthlyDistribution :monthlyDistributions) {
            if (!monthlyDistributionsForContracts.containsKey(monthlyDistribution.ContractID__c)) {
                monthlyDistributionsForContracts.put(monthlyDistribution.ContractID__c, new List<Monthly_Distribution__c>{monthlyDistribution});
            } else {
                monthlyDistributionsForContracts.get(monthlyDistribution.ContractID__c).add(monthlyDistribution);
            }
        }

        Map<Id, Set<Id>> salesRepsForContracts = new Map<Id, Set<Id>>();
        for (Contract_Sales_Rep__c salesRep :[SELECT Id, Contract__c FROM Contract_Sales_Rep__c WHERE Contract__c In :monthlyDistributionsForContracts.keySet()]) {
            if (!salesRepsForContracts.containsKey(salesRep.Contract__c)) {
                salesRepsForContracts.put(salesRep.Contract__c, new Set<Id> {salesRep.Id});
            } else {
                salesRepsForContracts.get(salesRep.Contract__c).add(salesRep.Id);
            }
        }
        assignMonthlyDistributions(salesRepsForContracts, monthlyDistributionsForContracts);
    }

    private static void assignMonthlyDistributions(Map<Id, Set<Id>> salesRepsForContracts, Map<Id, List<Monthly_Distribution__c>> monthlyDistributionsForContracts) {
        List<Sales_Rep_MD__c> salesRepMonthlyDistributions = new List<Sales_Rep_MD__c>();
        for (Id contractId : salesRepsForContracts.keySet()) {
            for (Id salesRepId : salesRepsForContracts.get(contractId)) {
                if (monthlyDistributionsForContracts.containsKey(contractId)) {
                    for (Monthly_Distribution__c md :monthlyDistributionsForContracts.get(contractId)) {
                        salesRepMonthlyDistributions.add(new Sales_Rep_MD__c(
                            Sales_Rep__c = salesRepId,
                            Monthly_Distribution__c = md.Id
                        ));
                    }
                }
            }
        }
        insert salesRepMonthlyDistributions;
    }

    public static void assignSalesRepToMonthlyDistribution(List<Contract_Sales_Rep__c> salesReps) {
        Map<Id, Set<Id>> salesRepsForContracts = new Map<Id, Set<Id>>();
        Map<Id, List<Monthly_Distribution__c>> monthlyDistributionsForContracts = new Map<Id, List<Monthly_Distribution__c>>();
        for (Contract_Sales_Rep__c salesRep : salesReps) {
            if (!salesRepsForContracts.containsKey(salesRep.Contract__c)) {
                salesRepsForContracts.put(salesRep.Contract__c, new Set<Id> {salesRep.Id});
            } else {
                salesRepsForContracts.get(salesRep.Contract__c).add(salesRep.Id);
            }
        }
        for (Monthly_Distribution__c monthlyDistribution : [SELECT Id, Project__c,Project__r.Payment__r.Project__c  FROM Monthly_Distribution__c WHERE Project__r.Payment__r.Project__c IN :salesRepsForContracts.keySet()]) {
            if (!monthlyDistributionsForContracts.containsKey(monthlyDistribution.Project__r.Payment__r.Project__c)) {
                monthlyDistributionsForContracts.put(monthlyDistribution.Project__r.Payment__r.Project__c, new List<Monthly_Distribution__c>{monthlyDistribution});
            } else {
                monthlyDistributionsForContracts.get(monthlyDistribution.Project__r.Payment__r.Project__c).add(monthlyDistribution);
            }
        }
        assignMonthlyDistributions(salesRepsForContracts, monthlyDistributionsForContracts);
    }

    public static void createMonthlyDistribution(List<Payment__c> projects)  {
        List<Monthly_Distribution__c> monthlyDistributions = new List<Monthly_Distribution__c>();

        Set<Id> paymentIds = new Map<Id,Payment__c>(projects).keySet();
        delete [SELECT Id FROM Monthly_Distribution__c WHERE Project__c IN :paymentIds];

        for (Payment__c project :projects) {
            Date startDate = project.Start_Date__c;

            while (startDate <= project.End_Date__c) {
                Monthly_Distribution__c monthlyDistribution = new Monthly_Distribution__c(CurrencyIsoCode = project.CurrencyIsoCode);
                monthlyDistribution.Project__c = project.Id;
                monthlyDistribution.Start_Date__c = startDate;
                monthlyDistribution.End_Date__c = Date.newInstance(startDate.year(), startDate.month() + 1, 1).addDays(-1);
                monthlyDistribution.Brand_Lookup__c = project.Project__r.Brand__r.Id;

                if (monthlyDistribution.End_Date__c > project.End_Date__c) {
                    monthlyDistribution.End_Date__c = project.End_Date__c;
                }
                Integer monthlyDistributionLength = monthlyDistribution.Start_Date__c.daysBetween(monthlyDistribution.End_Date__c) + 1;
                if (project.Client_Spend__c != null) {
                    monthlyDistribution.Client_Spend__c = (project.Client_Spend__c/project.Days_Running__c * monthlyDistributionLength).setScale(4, System.RoundingMode.HALF_DOWN);
                }
                if (project.Actual_Gross_Profit_New__c != null) {
                    monthlyDistribution.Actual_Gross_Profit__c = (project.Actual_Gross_Profit_New__c/project.Days_Running__c * monthlyDistributionLength).setScale(4, System.RoundingMode.HALF_DOWN);
                }
                if (project.Expected_Gross_Profit_New__c != null) {
                    monthlyDistribution.Expected_Gross_Profit__c = (project.Expected_Gross_Profit_New__c/project.Days_Running__c * monthlyDistributionLength).setScale(4, System.RoundingMode.HALF_DOWN);
                }
                if (project.Expected_Revenue__c != null) {
                    monthlyDistribution.Expected_Revenue__c = (project.Expected_Revenue__c/project.Days_Running__c * monthlyDistributionLength).setScale(4, System.RoundingMode.HALF_DOWN);
                }
                if (project.Actual_Revenue__c != null) {
                    monthlyDistribution.Actual_Revenue__c = (project.Actual_Revenue__c/project.Days_Running__c * monthlyDistributionLength).setScale(4, System.RoundingMode.HALF_DOWN);
                }
                if (project.Media_Order__c != null) {
                    monthlyDistribution.Media_Order__c = (project.Media_Order__c/project.Days_Running__c * monthlyDistributionLength).setScale(4, System.RoundingMode.HALF_DOWN);
                }
                startDate = monthlyDistribution.End_Date__c.addDays(1);
                monthlyDistributions.add(monthlyDistribution);
            }
        }

        insert monthlyDistributions;
    }
}