src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Sales_Rep__c.object
<CustomObject>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Gross_Profit__c</fullName>
        <label>Actual Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Revenue__c</fullName>
        <label>Actual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Monthly_Distribution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Revenue__c</fullName>
        <label>Expected Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Project</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Monthly Distributions</relationshipLabel>
        <relationshipName>Monthly_Distribution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Monthly Distribution</label>
    <nameField>
        <displayFormat>MD-{00000}</displayFormat>
        <label>MD Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Revenue__c</fullName>
        <formula>IF(Payment__r.Synced_with_Xero__c || !ISPICKVAL( Payment__r.XeroStatus__c,&quot;&quot;),
   InvoiceAmount__c,
Expected_Revenue__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <formula>IF (ISPICKVAL(Project__r.BillingCondition__r.Rebate_Type__c,&quot;Instant&quot;),
  (Client_Spend__c - Media_Order__c) * (1 - Project__r.BillingCondition__r.Rebate_Rate__c),
  (Client_Spend__c - Media_Order__c) - (Client_Spend__c * Project__r.BillingCondition__r.Rebate_Rate__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Gross Profit OLD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Revenue__c</fullName>
        <formula>IF(Account_Type__c = &quot;Client&quot;, 
   Client_Spend__c - Media_Order__c, 
Client_Spend__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Gross_Profit__c</fullName>
        <label>Actual Gross Profit No Rebate Rollup</label>
        <summarizedField>Sub_Project__c.ActualGrossProfitCopy__c</summarizedField>
        <summaryForeignKey>Sub_Project__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <summarizedField>Sub_Project__c.Expected_Gross_Profit__c</summarizedField>
        <summaryForeignKey>Sub_Project__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Gaps_Exist_Between_Projects__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gaps Exist Between Projects</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Rep_MD__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <formula>Monthly_Distribution__r.Client_Spend__c * Sales_Rep__r.Commission_Percentage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Distribution__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Monthly Distribution</label>
        <referenceTo>Monthly_Distribution__c</referenceTo>
        <relationshipLabel>Sales Rep Monthly Distributions</relationshipLabel>
        <relationshipName>Sales_Rep_MDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>Contract_Sales_Rep__c</referenceTo>
        <relationshipName>Sales_Rep_MDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Rep Monthly Distribution</label>
    <nameField>
        <displayFormat>SRMD-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <summarizedField>Payment__c.Expected_Gross_Profit_New__c</summarizedField>
        <summaryForeignKey>Payment__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MonthlyDistributionTest.cls
@IsTest
private class MonthlyDistributionTest {

    static testMethod void willCreateMonhlyDistributionOnInsert() {
        Project__c contract = TestHelper.createContractNoInsert(TestHelper.createAccount().Id, 'testContract', null);
        contract.Start_Date__c = Date.newInstance(System.today().year(), 3, 1);
        contract.End_Date__c = contract.Start_Date__c.addMonths(4).addDays(-1);
        contract.Gaps_Exist_Between_Projects__c = true;
        contract.Client_Spend__c = 200;
        insert contract;

        delete [SELECT Id FROM Sub_Project__c];

        Sub_Project__c payment1 = TestHelper.createPaymentNoInsert(contract);
        payment1.End_Date__c = payment1.Start_Date__c.addMonths(1).addDays(15);
        payment1.Client_Spend__c = 100;

        Sub_Project__c payment2 = TestHelper.createPaymentNoInsert(contract);
        payment2.Start_Date__c = payment1.End_Date__c.addDays(1);
        payment2.Client_Spend__c = 100;

        Test.startTest();
        insert new List<Sub_Project__c> {payment1, payment2};
        Test.stopTest();

        List<Monthly_Distribution__c> payment1Distributions = [
            SELECT Id, Client_Spend__c, Actual_Gross_Profit__c, Expected_Gross_Profit__c, Expected_Revenue__c, Actual_Revenue__c
            FROM Monthly_Distribution__c
            WHERE Project__c IN (SELECT Id FROM Payment__c WHERE Payment__c= :payment1.Id)
            ORDER BY Start_Date__c
        ];
        List<Monthly_Distribution__c> payment2Distributions = [
            SELECT Id, Client_Spend__c, Actual_Gross_Profit__c, Expected_Gross_Profit__c, Expected_Revenue__c, Actual_Revenue__c
            FROM Monthly_Distribution__c
            WHERE Project__c IN (SELECT Id FROM Payment__c WHERE Payment__c= :payment2.Id)
            ORDER BY Start_Date__c
        ];

        System.assertEquals(2, payment1Distributions.size());
        System.assertEquals(3, payment2Distributions.size());

        Integer payment1Length = payment1.Start_Date__c.daysBetween(payment1.End_Date__c) + 1;
        Integer payment2Length = payment2.Start_Date__c.daysBetween(payment2.End_Date__c) + 1;

        System.assertEquals((payment1.Client_Spend__c/payment1Length*31).setScale(4, System.RoundingMode.HALF_DOWN), payment1Distributions[0].Client_Spend__c);
        System.assertEquals(payment1.Client_Spend__c, payment1Distributions[0].Client_Spend__c + payment1Distributions[1].Client_Spend__c);

        System.assertEquals((payment2.Client_Spend__c/payment2Length*31).setScale(4, System.RoundingMode.HALF_DOWN), payment2Distributions[1].Client_Spend__c);
        System.assertEquals(payment2.Client_Spend__c, payment2Distributions[0].Client_Spend__c + payment2Distributions[1].Client_Spend__c + payment2Distributions[2].Client_Spend__c);
    }

    static testMethod void willUpdateMonhlyDistribution() {
        Project__c contract = TestHelper.createContractNoInsert(TestHelper.createAccount().Id, 'testContract', null);
        contract.Start_Date__c = Date.newInstance(System.today().year(), 3, 1);
        contract.End_Date__c = contract.Start_Date__c.addMonths(1).addDays(-1);
        contract.Gaps_Exist_Between_Projects__c = true;
        insert contract;

        List<Sub_Project__c> payments = [SELECT Id, Client_Spend__c, Project__c FROM Sub_Project__c];

        Test.startTest();
        contract.Client_Spend__c = 200;
        update contract;
        Test.stopTest();

        List<Monthly_Distribution__c> paymentDistributions = [
            SELECT Id, Client_Spend__c, Actual_Gross_Profit__c, Expected_Gross_Profit__c, Expected_Revenue__c, Actual_Revenue__c
            FROM Monthly_Distribution__c
            WHERE Project__c IN (SELECT Id FROM Payment__c WHERE Payment__c= :payments[0].Id)
            ORDER BY Start_Date__c
        ];
        System.assertEquals(contract.Client_Spend__c, [SELECT Client_Spend__c FROM Payment__c WHERE Payment__c = :payments[0].Id].Client_Spend__c);
        System.assertEquals(contract.Client_Spend__c, paymentDistributions[0].Client_Spend__c);
    }

    static testMethod void willAssignSalesRepMonthlyDistributionOnSalesRepInsert() {
        Project__c contract1 = TestHelper.createContractNoInsert(TestHelper.createAccount().Id, 'testContract1', null);
        contract1.Start_Date__c = Date.newInstance(System.today().year(), 3, 1);
        contract1.End_Date__c = contract1.Start_Date__c.addMonths(1).addDays(-1);
        insert contract1;

        Test.startTest();
        Contract_Sales_Rep__c salesRepContract1 = TestHelper.createContractSalesRepNoInsert(contract1.Id);
        insert salesRepContract1;
        Test.stopTest();

        List<Sales_Rep_MD__c> salesRepContract1Assignments = [
            SELECT Id
            FROM Sales_Rep_MD__c
            WHERE Sales_Rep__c = :salesRepContract1.Id AND Monthly_Distribution__r.Project__r.Payment__r.Project__c = :contract1.Id
        ];
        System.assertEquals(1, salesRepContract1Assignments.size());
    }

    static testMethod void willAssignSalesRepMonthlyDistributionOnMonthlyDistributionInsert() {
        Project__c contract1 = TestHelper.createContractNoInsert(TestHelper.createAccount().Id, 'testContract1', null);
        contract1.Start_Date__c = Date.newInstance(System.today().year(), 3, 1);
        contract1.End_Date__c = contract1.Start_Date__c.addMonths(1).addDays(-1);
        contract1.Gaps_Exist_Between_Projects__c = true;
        contract1.Client_Spend__c = 100;
        insert contract1;

        Contract_Sales_Rep__c salesRepContract1 = TestHelper.createContractSalesRepNoInsert(contract1.Id);
        insert salesRepContract1;

        delete [SELECT Id FROM Sub_Project__c];

        Test.startTest();
        Sub_Project__c paymentContract1 = TestHelper.createPaymentNoInsert(contract1);
        paymentContract1.Start_Date__c = contract1.Start_Date__c;
        paymentContract1.End_Date__c = contract1.End_Date__c;
        paymentContract1.Client_Spend__c = 100;
        insert new List<Sub_Project__c> {paymentContract1};
        Test.stopTest();

        List<Sales_Rep_MD__c> salesRepContract1Assignments = [
            SELECT Id
            FROM Sales_Rep_MD__c
            WHERE Sales_Rep__c = :salesRepContract1.Id AND Monthly_Distribution__r.Project__r.Payment__r.Project__c = :contract1.Id
        ];
    }

    @IsTest static void beforeInsert_setBrandLookup(){
        Project__c contract = TestHelper.createContractNoInsert(TestHelper.createAccount().Id, 'testContract', null);
        contract.Start_Date__c = Date.newInstance(System.today().year(), 3, 1);
        contract.End_Date__c = contract.Start_Date__c.addMonths(4).addDays(-1);
        contract.Gaps_Exist_Between_Projects__c = true;
        contract.Client_Spend__c = 200;

        Test.startTest();
        insert contract;
        Test.stopTest();

        Monthly_Distribution__c result = [SELECT Brand_Lookup__c FROM Monthly_Distribution__c LIMIT 1];
        Project__c expected = [SELECT Brand__r.Id FROM Project__c WHERE Id=:contract.Id];
        System.assertEquals(expected.Brand__r.Id, result.Brand_Lookup__c);
    }
}