src/objects/Brand__c.object
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand_Account__c.object
<CustomObject>
    <description>junction between brand and account</description>
    <fields>
        <fullName>Accounts__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brand_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Brand_Account__c</fullName>
        <formula>Brand__r.Name  &amp;&quot; / &quot;&amp;   Accounts__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand/Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Brand_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniqueKey__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand/Account</label>
    <nameField>
        <label>Brand/Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brand/Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BrandAccountHandler.cls
public class BrandAccountHandler implements ITrigger {

    public BrandAccountHandler() {}
    
    public void bulkBefore() {}

    public void bulkAfter() {}

    public void beforeInsert(List<SObject> so) {
        checkDuplicates((List<Brand_Account__c>)so);
    }

    public void beforeUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {
        checkDuplicates(((Map<Id, Brand_Account__c>)so).values());
    }
    
    public void beforeDelete(List<SObject> so) {}

    public void afterInsert(List<SObject> so) {
        List <Brand_Account__c> brandAccs = [SELECT Id, Brand_Account__c, Name FROM Brand_Account__c WHERE Name = 'tmpBrand / tmpAccount'];
        for (Brand_Account__c brandAcc :brandAccs) {
            if (brandAcc.Brand_Account__c != null && brandAcc.Brand_Account__c.length() > 80) {
                brandAcc.Name = brandAcc.Brand_Account__c.substring(0,79);
            } else {
                brandAcc.Name = brandAcc.Brand_Account__c;
            }
        }
        update brandAccs;
    }
    
    public void afterUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {}
        
    public void afterDelete(List<SObject> so) {}

    public void andFinally() {}
    
    private void checkDuplicates(List<Brand_Account__c> brandAccounts) {
        for (Brand_Account__c brandAcc :brandAccounts) {
        	brandAcc.UniqueKey__c = (String) brandAcc.Accounts__c + (String) brandAcc.Brand__c;
        }
    }    
}