src/objects/Commission_Profile__c.object
<CustomObject>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Profile__c</fullName>
        <label>Sales Rep</label>
        <referenceTo>Commission_Profile__c</referenceTo>
        <relationshipLabel>Sales Reps</relationshipLabel>
        <relationshipName>Sales_Reps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Rep_MD__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commission Profile</label>
        <referenceTo>Commission_Profile__c</referenceTo>
        <relationshipLabel>Sales Rep Monthly Distributions</relationshipLabel>
        <relationshipName>Sales_Rep_Monthly_Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>Contract_Sales_Rep__c</referenceTo>
        <relationshipName>Sales_Rep_MDs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Rep Monthly Distribution</label>
    <nameField>
        <displayFormat>SRMD-{00000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Monthly Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesRepMDHandler.cls
public with sharing class SalesRepMDHandler implements ITrigger {

    public SalesRepMDHandler() {}

    public void bulkBefore() {}

    public void bulkAfter() {}

    public void beforeInsert(List<SObject> so) {
        Set<Id> contractSalesRepIDs = new Set<Id>();
        for (Sales_Rep_MD__c srmd : (List<Sales_Rep_MD__c>) so) {
            contractSalesRepIDs.add(srmd.Sales_Rep__c);
        }

        Map<Id, Contract_Sales_Rep__c> reps = new Map<Id, Contract_Sales_Rep__c>([
                SELECT Id, Commission_Profile__c, Commission_Profile__r.CurrencyISOCode
                FROM Contract_Sales_Rep__c
                WHERE Id IN :contractSalesRepIDs
        ]);

        for (Sales_Rep_MD__c srmd : (List<Sales_Rep_MD__c>) so) {
            if (String.isBlank(srmd.Sales_Rep__c)) continue;

            Contract_Sales_Rep__c contractSalesRep = reps.get(srmd.Sales_Rep__c);
            srmd.Commission_Profile__c = contractSalesRep.Commission_Profile__c;
            srmd.CurrencyIsoCode = contractSalesRep.Commission_Profile__r.CurrencyISOCode;
        }
    }

    public void beforeUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {}

    public void beforeDelete(List<SObject> so) {}

    public void afterInsert(List<SObject> so) {}

    public void afterUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {}

    public void afterDelete(List<SObject> so) {}

    public void andFinally() {}
}