src/objects/Commission_Profile__c.object
<CustomObject>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Profile__c</fullName>
        <label>Sales Rep</label>
        <referenceTo>Commission_Profile__c</referenceTo>
        <relationshipLabel>Sales Reps</relationshipLabel>
        <relationshipName>Sales_Reps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractPreLaunchSalesRepNotifyCtrlTest.cls
@isTest
private class ContractPreLaunchSalesRepNotifyCtrlTest
{
    private static testMethod void testDisplayLaunchingContracts()
    {
        Account acc = TestHelper.createAccount();
    
        Project__c contract1 = TestHelper.createContractNoInsert(acc.Id, 'testContract1', NULL);
        contract1.Start_Date__c = System.Today().addDays(ContractRepository.prelaunchNotificationAdvance);
        contract1.End_Date__c = contract1.Start_Date__c.addDays(30);
        
        Project__c contract2 = TestHelper.createContractNoInsert(acc.Id, 'testContract2', NULL);
        contract2.Start_Date__c = contract1.Start_Date__c.addDays(1);
        contract2.End_Date__c = contract2.Start_Date__c.addDays(30);
        
        Project__c contract3 = TestHelper.createContractNoInsert(acc.Id, 'testContract3', NULL);
        contract3.Start_Date__c = contract1.Start_Date__c;
        contract3.End_Date__c = contract3.Start_Date__c.addDays(60);
        
        insert new List<Project__c> {contract1, contract2, contract3};
        
        Contract_Sales_Rep__c salesRep1 = TestHelper.createContractSalesRepNoInsert(contract1.Id);
        Contract_Sales_Rep__c salesRep2 = TestHelper.createContractSalesRepNoInsert(contract2.Id, salesRep1.Commission_Profile__c);
        Contract_Sales_Rep__c salesRep3 = TestHelper.createContractSalesRepNoInsert(contract3.Id, salesRep1.Commission_Profile__c);
        insert new List<Contract_Sales_Rep__c> {salesRep1, salesRep2, salesRep3};
        
        test.startTest();
        
            System.assertEquals(salesRep1.Commission_Profile__c, salesRep2.Commission_Profile__c);
        
            ContractPreLaunchSalesRepNotifyCtrl controller = new ContractPreLaunchSalesRepNotifyCtrl();
            controller.salesRep = salesRep1.Commission_Profile__c;
            
            List<Project__c> contracts = controller.getPreLaunchContracts(); 
        
        test.stopTest();
        
        System.assertEquals(2, contracts.size());
        System.assertEquals(contract1.Id, contracts[0].Id);
        System.assertEquals(contract3.Id, contracts[1].Id);
    }
}