src/objects/Commission_Profile__c.object
<CustomObject>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CurrencyHistory__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Currency History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Currency History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Rep_Quarterly_Bonus__c.object
<CustomObject>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Rep Quarterly Bonus</label>
    <nameField>
        <displayFormat>SRQ-{0000}</displayFormat>
        <label>Sales Rep Quarter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Quarterly Bonuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommissionProfileBonusesController_Test.cls
@isTest
public class CommissionProfileBonusesController_Test {

    testmethod static void getBonuses() {
    	Commission_Profile__c profile1 = TestHelper.createSalesCommissionProfile();
		CurrencyHistory__c ch1 = new CurrencyHistory__c (Date__c = Date.newInstance(2018, 01, 1),
            AUD__c = 0.6, EUR__c = 2.8, CAD__c  = 0, GBP__c  = 0, NZD__c  = 0, PLN__c  = 0, SGD__c  = 0,
            IDR__c  = 0, MXN__c  = 0, MYR__c=0, PHP__c  = 0, HKD__c  = 0, JPY__c  = 0, KRW__c  = 0, INR__c  = 0,
            THB__c  = 0, RUB__c  = 0);
        insert ch1;     
           
        Test.startTest();
        database.executeBatch(new SCH_BATCH_SalesRepBonusCalc(Date.newInstance(2018,01,01)));
        Test.stopTest();

        Sales_Rep_Quarterly_Bonus__c bonus = [SELECT Id FROM Sales_Rep_Quarterly_Bonus__c LIMIT 1];
        bonus.Gross_Profit__c=1;
        update bonus;
        CommissionProfileBonusesController ctrl = new CommissionProfileBonusesController(new ApexPages.StandardController(profile1));


        List<Sales_Rep_Quarterly_Bonus__c> bonuses = ctrl.getBonuses();
		system.assertEquals(1, bonuses.size());        
        
    }
}