src/objects/Commission_Profile__c.object
<CustomObject>
    <fields>
        <fullName>ActiveUser__c</fullName>
        <formula>Salesforce_User__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CommissionType__c</fullName>
        <label>Commission Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No commission</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Consultancy</fullName>
                </value>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Shared Inside Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GP_Bonus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GP Bonus</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>CommissionProfileCurrency__c</fullName>
        <formula>text(Commission_Profile__r.CurrencyIsoCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CommissionProfileCurrency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission_Profile_Commission_Type__c</fullName>
        <formula>TEXT(Commission_Profile__r.CommissionType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commission Profile Commission Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission_Profile__c</fullName>
        <label>Sales Rep</label>
        <referenceTo>Commission_Profile__c</referenceTo>
        <relationshipLabel>Sales Reps</relationshipLabel>
        <relationshipName>Sales_Reps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Commission_Type__c</fullName>
        <label>Commission Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sales Reps</relationshipLabel>
        <relationshipName>Sales_Reps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percentage_of_GP_Allocation__c</fullName>
        <label>% of GP Allocation</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <description>Unique ID of Sales Rep prevents from adding him to contract twice.</description>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>64</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractSalesRepHandler.cls
public class ContractSalesRepHandler implements ITrigger {
    private Boolean isInsert = false;
    
    public ContractSalesRepHandler() {}
    
    public void bulkBefore() {}
    
    public void bulkAfter() {}
    
    public void beforeInsert(List<SObject> so) {
        Set<String> newUniqueIds = new Set<String>();
        for (Contract_Sales_Rep__c salesRep :(List<Contract_Sales_Rep__c>) so) {
            salesRep.Unique_ID__c = salesRep.Commission_Profile__c + '#' + salesRep.Contract__c;
            newUniqueIds.add(salesRep.Unique_ID__c);
            
            if (salesRep.CurrencyIsoCode != salesRep.CommissionProfileCurrency__c) {
                salesRep.CurrencyIsoCode = salesRep.CommissionProfileCurrency__c;
            }
            
            if (salesRep.Commission_Profile_Commission_Type__c != null) {
                salesRep.Commission_Type__c = salesRep.Commission_Profile_Commission_Type__c;
            }
        }
    }
    
    public void beforeUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {
        for (Contract_Sales_Rep__c salesRep :((Map<Id, Contract_Sales_Rep__c>) so).values()) {
            if (salesRep.CurrencyIsoCode != salesRep.CommissionProfileCurrency__c) {
                salesRep.CurrencyIsoCode = salesRep.CommissionProfileCurrency__c;
            }
            if (salesRep.Commission_Profile_Commission_Type__c != null) {
                salesRep.Commission_Type__c = salesRep.Commission_Profile_Commission_Type__c;
            }
        }
    }
    
    public void beforeDelete(List<SObject> so) {}
    
    public void afterInsert(List<SObject> so) {
        MonthlyDistribution.assignSalesRepToMonthlyDistribution((List<Contract_Sales_Rep__c>)so);
        isInsert = true; 
        List<Contract_Sales_Rep__c> salesReps = (List<Contract_Sales_Rep__c>) so;
        recalculateCommissions(salesReps);
        
        Set<Id> contractsWithInsertedRepsSet = new Set <Id> ();
        for (Contract_Sales_Rep__c rep :salesReps) {
            contractsWithInsertedRepsSet.add (rep.Contract__c);
        }
        setDefaultPercentageOfGPAllocation(contractsWithInsertedRepsSet);
    }
    
    public void afterUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {
        List <Contract_Sales_Rep__c> salesReps = new List <Contract_Sales_Rep__c>();
        for (Contract_Sales_Rep__c newRep : (Contract_Sales_Rep__c []) so.values()) {
            salesReps.add (newRep);
        }
        recalculateCommissions(salesReps);
    }
    
    public void afterDelete(List<SObject> so) {
        Set <Id> contractsWithDeletedRepsSet = new Set<Id> ();
        for (Contract_Sales_Rep__c rep :(List<Contract_Sales_Rep__c>) so) {
            contractsWithDeletedRepsSet.add (rep.Contract__c);
        }
        
        List <Project__c> contractsWithDeletedReps = [SELECT Id FROM Project__c WHERE Id IN :contractsWithDeletedRepsSet];
        ConSalesRepExpCommissionCalculator.calculateExpectedCommission(contractsWithDeletedReps);
        setDefaultPercentageOfGPAllocation(contractsWithDeletedRepsSet);
    }
    
    public void andFinally() {}
    
    private void recalculateCommissions(List <Contract_Sales_Rep__c> salesReps) {
        List<Contract_Sales_Rep__c> fullList = new List<Contract_Sales_Rep__c>();
        List<Id> commissionProfileIds = new List<Id>();
        Set<Id> contractIds = new Set<Id>();
        for (Contract_Sales_Rep__c salesRep : salesReps) {
            if (salesRep.Commission_Profile_Commission_Type__c == Label.COMMISSION_TYPE_SHARED_INSIDE_SALES){
                commissionProfileIds.add(salesRep.Commission_Profile__c);
                contractIds.add(salesRep.Contract__c);
            }
        }
        
        if (commissionProfileIds.size() > 0 && isInsert) {
            List <Commission_Profile__c> missingSharedRepsProfiles = [
                SELECT Id
                FROM Commission_Profile__c
                WHERE CommissionType__c = :Label.COMMISSION_TYPE_SHARED_INSIDE_SALES
                    AND ActiveUser__c = TRUE
                    AND Id NOT IN :commissionProfileIds
                    AND Id NOT IN (SELECT Commission_Profile__c FROM Contract_Sales_Rep__c WHERE Contract__c IN :contractIds)
            ];
            if (missingSharedRepsProfiles.size() > 0) {
                List <Contract_Sales_Rep__c> missingSalesReps = new List<Contract_Sales_Rep__c>();
                for (Commission_Profile__c missingRep :missingSharedRepsProfiles) {
                    Contract_Sales_Rep__c rep = new Contract_Sales_Rep__c ();
                    rep.Commission_Profile__c = missingRep.Id;
                    rep.Contract__c = salesReps [0].Contract__c;
                    missingSalesReps.add (rep);
                }
                Database.insert(missingSalesReps,false);
                fullList.addAll(missingSalesReps);
            }
        }
        fullList.addAll(salesReps);
        ConSalesRepExpCommissionCalculator.calculateExpectedCommission(fullList);
        //ConSalesRepExpCommissionCalculator.SALES_REP_EXPECTED_COMMISSIONS_RECALCULATED = false;                    
    }
    
    private void setDefaultPercentageOfGPAllocation(Set<Id> contractIDs) {
        List<Contract_Sales_Rep__c> repsToUpdate = new List <Contract_Sales_Rep__c>();
        for (Project__c contract :[
            SELECT Id, (SELECT Id, Commission_Profile__r.GP_Bonus__c FROM Sales_Reps__r)
            FROM Project__c
            WHERE Id IN :contractIDs
        ]) {
            Integer repsWithBonus = 0;
            for (Contract_Sales_Rep__c rep : contract.Sales_Reps__r) {
                if (rep.Commission_Profile__r.GP_Bonus__c) {
                    repsWithBonus++;
                }
            }
            for (Contract_Sales_Rep__c rep :contract.Sales_Reps__r) {
                if (rep.Commission_Profile__r.GP_Bonus__c) {
                    rep.percentage_of_GP_allocation__c = 100.0 / repsWithBonus;
                } else {
                    rep.percentage_of_GP_allocation__c = null;
                }
                repsToUpdate.add(rep);
            }
        }    
        update repsToUpdate;
    }
}