src/objects/Commission_Profile__c.object
<CustomObject>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Rep_Annual_Bonus__c.object
<CustomObject>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <summarizedField>Sales_Rep_Quarterly_Bonus__c.Gross_Profit__c</summarizedField>
        <summaryForeignKey>Sales_Rep_Quarterly_Bonus__c.Year__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <label>Sales Rep</label>
        <referenceTo>Commission_Profile__c</referenceTo>
        <relationshipLabel>Sales Rep Annual Bonuses</relationshipLabel>
        <relationshipName>Sales_Rep_Annual_Bonuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Rep Annual Bonus</label>
    <nameField>
        <displayFormat>SRA-{0000}</displayFormat>
        <label>Sales Rep Annual Bonus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Annual Bonuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Rep_Quarterly_Bonus__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GP_Threshold__c</fullName>
        <label>GP Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <referenceTo>Sales_Rep_Annual_Bonus__c</referenceTo>
        <relationshipLabel>Sales Rep Quarterly Bonuses</relationshipLabel>
        <relationshipName>Sales_Rep_Quarterly_Bonuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Rep Quarterly Bonus</label>
    <nameField>
        <displayFormat>SRQ-{0000}</displayFormat>
        <label>Sales Rep Quarter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Quarterly Bonuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommissionProfileBonusesController.cls
public class CommissionProfileBonusesController {
    
    private final Commission_Profile__c profile;

    public CommissionProfileBonusesController(ApexPages.StandardController stdController) {
        profile = (Commission_Profile__c) stdController.getRecord();

    }

    public List<Sales_Rep_Quarterly_Bonus__c> getBonuses() {
        return [SELECT ID, quarter__c, CurrencyISOCode, year__r.Sales_Rep__c,Start_Date__c, End_Date__c,
                year__c, year__r.year__c, Gross_Profit__c, GP_Threshold__c
                FROM Sales_Rep_Quarterly_Bonus__c 
               WHERE year__r.Sales_Rep__c=:profile.Id AND Gross_Profit__c!=0
               ORDER BY year__r.year__c DESC, quarter__c DESC];
    }    
}