src/objects/Commission_Profile__c.object
<CustomObject>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CurrencyHistory__c.object
<CustomObject>
    <fields>
        <fullName>AUD__c</fullName>
        <label>AUD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAD__c</fullName>
        <label>CAD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EUR__c</fullName>
        <label>EUR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GBP__c</fullName>
        <label>GBP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HKD__c</fullName>
        <label>HKD</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IDR__c</fullName>
        <label>IDR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>INR__c</fullName>
        <label>INR</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>JPY__c</fullName>
        <label>JPY</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KRW__c</fullName>
        <label>KRW</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MXN__c</fullName>
        <label>MXN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MYR__c</fullName>
        <label>MYR</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NZD__c</fullName>
        <label>NZD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PHP__c</fullName>
        <label>PHP</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PLN__c</fullName>
        <label>PLN</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RUB__c</fullName>
        <label>RUB</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SGD__c</fullName>
        <label>SGD</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>THB__c</fullName>
        <label>THB</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Currency History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Currency History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Rep_Annual_Bonus__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Rep Annual Bonus</label>
    <nameField>
        <displayFormat>SRA-{0000}</displayFormat>
        <label>Sales Rep Annual Bonus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Annual Bonuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sales_Rep_Quarterly_Bonus__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <referenceTo>Sales_Rep_Annual_Bonus__c</referenceTo>
        <relationshipLabel>Sales Rep Quarterly Bonuses</relationshipLabel>
        <relationshipName>Sales_Rep_Quarterly_Bonuses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Rep Quarterly Bonus</label>
    <nameField>
        <displayFormat>SRQ-{0000}</displayFormat>
        <label>Sales Rep Quarter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Rep Quarterly Bonuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SCH_BATCH_SalesRepBonusCalc_Test.cls
@isTest
public class SCH_BATCH_SalesRepBonusCalc_Test {

    testmethod static void createAnnualBonus() {
    	Commission_Profile__c profile1 = TestHelper.createSalesCommissionProfile();
        
        Test.startTest();
        database.executeBatch(new SCH_BATCH_SalesRepBonusCalc(Date.newInstance(2018,01,01)));
        Test.stopTest();
        
        system.assertEquals(1, [SELECT count() FROM Sales_Rep_Annual_Bonus__c where year__c=2018]);        
    }
    
    testmethod static void createQuarterBonus() {
    	Commission_Profile__c profile1 = TestHelper.createSalesCommissionProfile();
        database.executeBatch(new SCH_BATCH_SalesRepBonusCalc(Date.newInstance(2018,01,01)));
		CurrencyHistory__c ch1 = new CurrencyHistory__c (Date__c = Date.newInstance(2018, 01, 1),
            AUD__c = 0.6, EUR__c = 2.8, CAD__c  = 0, GBP__c  = 0, NZD__c  = 0, PLN__c  = 0, SGD__c  = 0,
            IDR__c  = 0, MXN__c  = 0, MYR__c=0, PHP__c  = 0, HKD__c  = 0, JPY__c  = 0, KRW__c  = 0, INR__c  = 0,
            THB__c  = 0, RUB__c  = 0);
        insert ch1;        
        
        Test.startTest();
        database.executeBatch(new SCH_BATCH_SalesRepBonusCalc(Date.newInstance(2018,10,01)));
        Test.stopTest();
        
        system.assertEquals(1, [SELECT count() FROM Sales_Rep_Quarterly_Bonus__c where quarter__c=4
                               and start_date__c=:date.newInstance(2018,10,1)
                               and end_Date__c=:date.newInstance(2018,12,31)]);        
    }   
        
}