src/objects/Contact_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contact_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Contact_Opportunities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Evaluator</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Negative Influencer</fullName>
                </value>
                <value>
                    <fullName>Business User</fullName>
                    <isActive>false</isActive>
                    <label>Business User</label>
                </value>
                <value>
                    <fullName>Economic Buyer</fullName>
                    <isActive>false</isActive>
                    <label>Economic Buyer</label>
                </value>
                <value>
                    <fullName>Economic Decision Maker</fullName>
                    <isActive>false</isActive>
                    <label>Economic Decision Maker</label>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                    <isActive>false</isActive>
                    <label>Executive Sponsor</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Technical Buyer</fullName>
                    <isActive>false</isActive>
                    <label>Technical Buyer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <label>Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Opportunity Contact</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Contact Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SCH_BATCH_ContactRolesSynchronizer.cls
public class SCH_BATCH_ContactRolesSynchronizer implements Database.Batchable <sObject>, Database.stateful, Schedulable {

    public void execute(SchedulableContext ctx) 
    {        
        Database.executeBatch(new SCH_BATCH_ContactRolesSynchronizer(), 200);
    }   
    
    public Database.Querylocator start(Database.BatchableContext bc)
    {      
        return Database.getQuerylocator([select id , 
                                         (select id, opportunityid, contactid, role from opportunitycontactroles), 
                                         (select id, unique_id__c, role__c, contact__c, opportunity__c from Contact_Opportunities__r) 
                                         from opportunity where id in (select opportunityid from opportunitycontactrole)]);
    } 
    
    public void execute(Database.BatchableContext bc, List<Opportunity> scope)
    {
		Map<String,Contact_Opportunity__c> cos = new Map<String,Contact_Opportunity__c>();
        for(Opportunity opp: scope){
            for(Contact_Opportunity__c co: opp.Contact_Opportunities__r){
                cos.put(co.unique_id__c, co);
            }
            
            for(OpportunityContactRole ocr: opp.opportunitycontactroles){
            	String uniqueKey = ocr.ContactId+'#'+ocr.OpportunityId;
                Contact_Opportunity__c co = cos.get(uniqueKey);
                if(co==null) {
                    co = new Contact_Opportunity__c(Contact__c=ocr.ContactId, Opportunity__c=ocr.OpportunityId,
                                                   Unique_Id__c=uniqueKey);
                }
                co.Role__c=ocr.Role;
                cos.put(co.Unique_Id__c,co);
            }
            
            
        }
        database.upsert(cos.values());
    }    
    
    public void finish(Database.BatchableContext bc)
    {
    }         
    
}