src/objects/Contract_Sales_Rep__c.object
<CustomObject>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sales Reps</relationshipLabel>
        <relationshipName>Sales_Reps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExpectedCommission__c</fullName>
        <label>Expected commission APEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit_per_Rep__c</fullName>
        <label>Expected GP/Rep APEX</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_commission__c</fullName>
        <formula>IF(Contract__r.Opportunity__r.CloseDate&gt;=DATE(2017,1,1),	
  ExpectedCommission__c,
  IF(AND(Contract__r.Client_Spend__c!=0,Contract__r.No_of_sales_reps__c!=0),
    IF(ISPICKVAL(Commission_Profile__r.CommissionType__c,&quot;No Commission&quot;),NULL,
      IF( ROUND(Contract__r.ActualGrossProfit__c / Contract__r.Client_Spend__c,2) &lt; 0.05, 0,
      IF( ROUND(Contract__r.ActualGrossProfit__c / Contract__r.Client_Spend__c,2) &lt; 0.10, Contract__r.ActualGrossProfit__c *0.01,
      IF( ROUND(Contract__r.ActualGrossProfit__c / Contract__r.Client_Spend__c,2) &lt; 0.15, Contract__r.ActualGrossProfit__c *0.02,
      IF( ROUND(Contract__r.ActualGrossProfit__c / Contract__r.Client_Spend__c,2) &lt; 0.20, Contract__r.ActualGrossProfit__c *0.03,
      IF( ROUND(Contract__r.ActualGrossProfit__c / Contract__r.Client_Spend__c,2) &lt; 0.25, Contract__r.ActualGrossProfit__c *0.04,
      Contract__r.Client_Spend__c *0.0125)))))
    )/ Contract__r.No_of_sales_reps__c
  ,NULL)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GrossProfitperRep__c</fullName>
        <label>Gross Profit per Rep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Rep</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Reps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Ended__c</fullName>
        <formula>Today()&gt;=End_Date__c + 3</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract End Date+3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InvoicesPaid__c</fullName>
        <formula>NoOfIvoicesNotPaid__c = 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoices Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Net 30</fullName>
                </value>
                <value>
                    <fullName>Net 45</fullName>
                </value>
                <value>
                    <fullName>Net 60</fullName>
                </value>
                <value>
                    <fullName>Net 90</fullName>
                </value>
                <value>
                    <fullName>Net 120</fullName>
                </value>
                <value>
                    <fullName>50/50</fullName>
                </value>
                <value>
                    <fullName>100% Upfront</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Issue__c</fullName>
        <formula>Project__r.Contract_Ended__c != Contract_Ended__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract End Issue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_Ended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract End Date+3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <formula>HYPERLINK( &apos;https://strike.my.salesforce.com/&apos;&amp;Project__r.Id , Project__r.Name  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Net 30</fullName>
                </value>
                <value>
                    <fullName>Net 45</fullName>
                </value>
                <value>
                    <fullName>Net 60</fullName>
                </value>
                <value>
                    <fullName>Net 90</fullName>
                </value>
                <value>
                    <fullName>Net 120</fullName>
                </value>
                <value>
                    <fullName>50/50</fullName>
                </value>
                <value>
                    <fullName>100% Upfront</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubProjectEndingBatch.cls
public class SubProjectEndingBatch implements Schedulable, Database.Batchable<SObject>  {

   public void execute(SchedulableContext sc) {
       Database.executeBatch(new SubProjectEndingBatch(), 200);
   }

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Project__c, Project__r.Contract_Ended__c, Contract_Ended__c FROM Sub_Project__c WHERE Contract_End_Issue__c = true]);
    }

    public void execute(Database.BatchableContext BC, List<Sub_Project__c> scope){
        Set<ID> contractIDs = new Set<Id>();
        for (Sub_Project__c payment: scope) {
            payment.Contract_Ended__c = payment.Project__r.Contract_Ended__c;
            contractIDs.add(payment.Project__c);
        }
        update scope;

        List<Contract_Sales_Rep__c> salesReps = [
            SELECT Commission__c, Expected_commission__c, ExpectedCommission__c, GrossProfitperRep__c, Expected_Gross_Profit_per_Rep__c
            FROM Contract_Sales_Rep__c
            WHERE Contract__c IN :contractIDs AND Commission__c = NULL
                AND Contract__r.Payment_Type__c = '100% Upfront'
                AND Contract__r.InvoicesPaid__c = true
                AND Contract__r.Contract_Ended__c = true
        ];
        ProjectHandler.copySalesRepCommissions(salesReps);
        update salesReps;
    }

    public void finish(Database.BatchableContext BC) {}

}