src/objects/Contact_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Contact_Opportunities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Contact</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Contact Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NewContactOpportunityController.cls
public class NewContactOpportunityController {
    
    public Id opportunityId { get; set; }
    public List<Contact_Opportunity__c> contactRoles { get; set; }
    public Integer contactRoleRow { get; set; }

    public NewContactOpportunityController(ApexPages.StandardSetController stdController) {
        opportunityId = ApexPages.currentPage().getParameters().get('id');
        contactRoles = new List<Contact_Opportunity__c>{
                new Contact_Opportunity__c(Opportunity__c = opportunityId)
        };
    }

    public PageReference save() {
        if (!contactRoles.isEmpty()) {
            database.upsert(contactRoles,false);
        }
        return new PageReference('/' + opportunityId);
    }

    public void addNewContactRole() {
        contactRoles.add(new Contact_Opportunity__c(Opportunity__c = opportunityId));
    }

    public void deleteContactRole() {
        Boolean success = true;
        Contact_Opportunity__c recordToDelete = contactRoles[contactRoleRow];

        if (!string.isBlank(recordToDelete.Id)) {
            try {
                delete recordToDelete;
            } catch (DmlException ex) {
                success = false;
                ApexPages.addMessage(new ApexPages.Message(Apexpages.Severity.ERROR, ex.getDMLMessage(0)));
            }
        }

        if (success) {
            contactRoles.remove(contactRoleRow);
        }
    }

}