src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Replied</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Pre-Meeting</fullName>
                </value>
                <value>
                    <fullName>Reschedule</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Proposal/Price Quote</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>In-House/Self-Serve</fullName>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
                <value>
                    <fullName>Unqualified</fullName>
                </value>
                <value>
                    <fullName>Closed Lost</fullName>
                </value>
                <value>
                    <fullName>Marketing/Recycle</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventLog__c.object
<CustomObject>
    <description>Record errors, events</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Event Logs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Info__c</fullName>
        <label>Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Event Logs</relationshipLabel>
        <relationshipName>Event_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Media Manager report</fullName>
                </value>
                <value>
                    <fullName>MM report provided</fullName>
                </value>
                <value>
                    <fullName>MM parsing error</fullName>
                </value>
                <value>
                    <fullName>MM data failure</fullName>
                </value>
                <value>
                    <fullName>Kevin Organization</fullName>
                </value>
                <value>
                    <fullName>Kevin Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Log</label>
    <nameField>
        <displayFormat>EventLog-{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Lifetime</fullName>
                </value>
                <value>
                    <fullName>Once</fullName>
                </value>
                <value>
                    <fullName>Month</fullName>
                    <isActive>false</isActive>
                    <label>Month</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Xero_Id__c</fullName>
        <externalId>true</externalId>
        <label>Xero Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Id__c</fullName>
        <externalId>true</externalId>
        <label>Xero Invoice Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice_Name__c</fullName>
        <label>Xero Invoice Name</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/XeroSettings__c.object
<CustomObject>
    <label>Xero Settings</label>
    <nameField>
        <label>XeroSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceHelperTest.cls
/**
 * Created by pavel on 2020-10-23.
 */

@IsTest
private class InvoiceHelperTest {

    @IsTest
    static void invoiceSchedulerTestSuccess() {
        TestHelper.createAppSettings();

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InvoiceHelper.ResponseMockSuccess());
        System.schedule('Test Scheduler', '0 0 23 * * ?', new InvoiceScheduler());
        Test.stopTest();

        List<EventLog__c> logs = [SELECT Id, Info__c, Status__c FROM EventLog__c WHERE Type__c = :EventLog.STRIKE_DATA_CALLOUT AND Status__c = :EventLog.STATUS_ERROR];
        System.assertEquals(logs.size(), 0, 'No Errors Should Be');
    }

    @IsTest
    static void calloutInvoicesTestSuccess() {
        TestHelper.createAppSettings();
        InvoiceHelper.ResponseMockSuccess mockClass = new InvoiceHelper.ResponseMockSuccess();

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mockClass);
        InvoiceScheduler.calloutInvoices(System.today().month(), System.today().year());
        Test.stopTest();

        List<EventLog__c> logs = [SELECT Id, Info__c, Status__c FROM EventLog__c WHERE Type__c = :EventLog.STRIKE_DATA_CALLOUT AND Status__c = :EventLog.STATUS_ERROR];
        System.assertEquals(logs.size(), 0, 'No Errors Should Be');

        List<Invoice__c> invoices = [SELECT Id FROM Invoice__c];
        System.assertEquals(mockClass.invoice_amount, invoices.size());
    }

    @IsTest
    static void sendInvoiceTest() {
        String region = 'EMEA';
        Integer invoices_amount = 1;

        XeroSettings__c xs = TestHelper.createXeroEntityByRegion(region, true);
        List<Invoice__c> invoices = new List<Invoice__c>();
        for (Integer i = 1; i <= invoices_amount; i++) {
            invoices.add(TestHelper.createInvoice(100*i, xs.Id, region, false));
        }
        insert invoices;

        List<Invoice__c> invoicesSelected = [SELECT Xero_Invoice_Id__c, Xero_Invoice_Name__c, Xero_Id__c FROM Invoice__c WHERE Id IN :invoices];
        for (Invoice__c invoice :invoicesSelected) {
            System.assertEquals(null, invoice.Xero_Invoice_Id__c, 'Id should be equal to null');
            System.assertEquals(null, invoice.Xero_Invoice_Name__c, 'Id should be equal to null');
            System.assertNotEquals(null, invoice.Xero_Id__c, 'Xero Contract Id should be defined to create Invoice record in Xero');
        }

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new XeroMockUpResponseGenerator());
        for (Invoice__c invoice :invoices) {
            InvoiceHelper.sendInvoice(invoice);
        }
        Test.stopTest();

        invoicesSelected = [SELECT Xero_Invoice_Id__c, Xero_Invoice_Name__c FROM Invoice__c WHERE Id IN :invoices];
        for (Invoice__c invoice :invoicesSelected) {
            System.assertNotEquals(null, invoice.Xero_Invoice_Id__c, 'Id should be assigned');
            System.assertNotEquals(null, invoice.Xero_Invoice_Name__c, 'Id should be assigned');
        }
    }

    @IsTest
    static void calloutInvoicesTestSuccessDuplicationCheck1() {
        TestHelper.createAppSettings();
        InvoiceHelper.ResponseMockSuccess mockClass = new InvoiceHelper.ResponseMockSuccess();

        Test.startTest();
        // create duplicate records with modified dates
        List<Invoice__c> invoicesToInsert = new List<Invoice__c>();
        for (InvoiceHelper.InvoiceResponse invoice :mockClass.getBodyFor5Records()) {
            invoicesToInsert.add(InvoiceHelper.setInvoice(invoice));
        }
        for (Invoice__c invoice :invoicesToInsert) {
            invoice.Start_Date__c = invoice.Start_Date__c.addMonths(-1);
            invoice.End_Date__c = invoice.End_Date__c.addMonths(-1);
        }
        Integer existingInvoiceAmount = invoicesToInsert.size();
        insert invoicesToInsert;

        Test.setMock(HttpCalloutMock.class, mockClass);
        InvoiceScheduler.calloutInvoices(System.today().month(), System.today().year());
        Test.stopTest();

        List<EventLog__c> logs = [SELECT Id, Info__c, Status__c FROM EventLog__c WHERE Type__c = :EventLog.STRIKE_DATA_CALLOUT AND Status__c = :EventLog.STATUS_ERROR];
        System.assertEquals(logs.size(), 0, 'No Errors Should Be');

        List<Invoice__c> invoices = [SELECT Id FROM Invoice__c];
        System.assertEquals(existingInvoiceAmount * 2, invoices.size(), 'Old records stay unchanged, new records have been added');
    }

    @IsTest
    static void calloutInvoicesTestSuccessDuplicationCheck2() {
        Decimal initialInvoiceAmount = 100;
        TestHelper.createAppSettings();
        InvoiceHelper.ResponseMockSuccess mockClass = new InvoiceHelper.ResponseMockSuccess();

        Test.startTest();
        // create duplicate records
        List<Invoice__c> invoicesToInsert = new List<Invoice__c>();
        for (InvoiceHelper.InvoiceResponse invoice :mockClass.getBodyFor5Records()) {
            invoice.invoice_amount = initialInvoiceAmount;
            invoicesToInsert.add(InvoiceHelper.setInvoice(invoice));
        }
        insert invoicesToInsert;

        Test.setMock(HttpCalloutMock.class, mockClass);
        InvoiceScheduler.calloutInvoices(System.today().month(), System.today().year());
        Test.stopTest();

        List<EventLog__c> logs = [SELECT Id, Info__c, Status__c FROM EventLog__c WHERE Type__c = :EventLog.STRIKE_DATA_CALLOUT AND Status__c = :EventLog.STATUS_ERROR];
        System.assertEquals(logs.size(), 0, 'No Errors Should Be');

        List<Invoice__c> invoices = [SELECT Id, Invoice_Amount__c FROM Invoice__c];
        System.assertEquals(mockClass.invoice_amount, invoices.size(), 'Old records have been replaced by new ones');
        for (Invoice__c invoice :invoices) {
            System.assertNotEquals(initialInvoiceAmount, invoice.Invoice_Amount__c, 'Invoice Amount should be updated');
        }
    }

    @IsTest
    static void calloutCheckedInvoicesWithoutChangingInvoiceAmountTest1() {
        Decimal initialInvoiceAmount = 100;
        String initialContractName = 'TestContract';
        TestHelper.createAppSettings();
        InvoiceHelper.ResponseMockSuccess mockClass = new InvoiceHelper.ResponseMockSuccess();

        Test.startTest();
        // create duplicate records
        List<Invoice__c> invoicesToInsert = new List<Invoice__c>();
        for (InvoiceHelper.InvoiceResponse invoice :mockClass.getBodyFor5Records()) {
            invoice.invoice_amount = initialInvoiceAmount;
            Invoice__c invoiceToInsert = InvoiceHelper.setInvoice(invoice);
            invoiceToInsert.Checked__c = true;
            invoiceToInsert.Contract__c = initialContractName;

            invoicesToInsert.add(invoiceToInsert);
        }
        insert invoicesToInsert;

        Test.setMock(HttpCalloutMock.class, mockClass);
        InvoiceScheduler.calloutInvoices(System.today().month(), System.today().year());
        Test.stopTest();

        List<EventLog__c> logs = [SELECT Id, Info__c, Status__c FROM EventLog__c WHERE Type__c = :EventLog.STRIKE_DATA_CALLOUT AND Status__c = :EventLog.STATUS_ERROR];
        System.assertEquals(logs.size(), 0, 'No Errors Should Be');

        List<Invoice__c> invoices = [SELECT Id, Invoice_Amount__c, Contract__c  FROM Invoice__c];
        System.assertEquals(mockClass.invoice_amount, invoices.size(), 'Old records have been replaced by new ones');
        for (Invoice__c invoice :invoices) {
            System.assertEquals(initialInvoiceAmount, invoice.Invoice_Amount__c, 'Invoice Amount should NOT be updated for Checked invoice');
            System.assertNotEquals(initialContractName, invoice.Contract__c, 'Contact Name should be updated even for Checked invoice');
        }
    }

    @IsTest
    static void calloutCheckedInvoicesWithoutChangingInvoiceAmountTest2() {
        Decimal initialInvoiceAmount = 100;
        Date initialDueDate = Date.newInstance(System.today().year(), System.today().month(), System.today().day());
        TestHelper.createAppSettings();
        InvoiceHelper.ResponseMockSuccess mockClass = new InvoiceHelper.ResponseMockSuccess();

        Test.startTest();
        // create duplicate records
        List<Invoice__c> invoicesToInsert = new List<Invoice__c>();
        for (InvoiceHelper.InvoiceResponse invoice :mockClass.getBodyFor5Records()) {
            invoice.invoice_amount = initialInvoiceAmount;
            Invoice__c invoiceToInsert = InvoiceHelper.setInvoice(invoice);
            invoiceToInsert.Checked__c = true;
            invoiceToInsert.Due_Date__c = initialDueDate;

            invoicesToInsert.add(invoiceToInsert);
        }
        insert invoicesToInsert;

        Test.setMock(HttpCalloutMock.class, mockClass);
        InvoiceScheduler.calloutInvoices(System.today().month(), System.today().year());
        Test.stopTest();

        List<EventLog__c> logs = [SELECT Id, Info__c, Status__c FROM EventLog__c WHERE Type__c = :EventLog.STRIKE_DATA_CALLOUT AND Status__c = :EventLog.STATUS_ERROR];
        System.assertEquals(logs.size(), 0, 'No Errors Should Be');

        List<Invoice__c> invoices = [SELECT Id, Invoice_Amount__c, Contract__c, Due_Date__c  FROM Invoice__c];
        System.assertEquals(mockClass.invoice_amount, invoices.size(), 'Old records have been replaced by new ones');
        for (Invoice__c invoice :invoices) {
            System.assertEquals(initialInvoiceAmount, invoice.Invoice_Amount__c, 'Invoice Amount should NOT be updated for Checked invoice');
            System.assertNotEquals(initialDueDate, invoice.Due_Date__c, 'Due Date should be updated even for Checked invoice');
        }
    }
}