src/objects/CreditNote__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Revised Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Credit Notes</relationshipLabel>
        <relationshipName>CreditNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>XeroAmount__c</fullName>
        <label>Xero Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreditNoteHandler.cls
public class CreditNoteHandler implements ITrigger {
    public CreditNoteHandler() {}
    
    public void bulkBefore() {}

    public void bulkAfter() {}

    public void beforeInsert(List<SObject> so) {
        List<CreditNote__c> creditNotes = (List<CreditNote__c>)so;
        Map<Id, List<CreditNote__c>> paymentCreditNotes = new Map<Id, List<CreditNote__c>>();
        for (CreditNote__c creditNote : creditNotes) {
            if (!paymentCreditNotes.containsKey(creditNote.Payment__c)) {
                paymentCreditNotes.put(creditNote.Payment__c, new List<CreditNote__c> {creditNote});
            } else {
                paymentCreditNotes.get(creditNote.Payment__c).add(creditNote);
            }
        }
        
        for (Sub_Project__c payment : [SELECT Id, CurrencyIsoCode, Invoice_Amount__c FROM Sub_Project__c WHERE Id IN :paymentCreditNotes.keySet()]) {
            for (CreditNote__c creditNote :paymentCreditNotes.get(payment.Id)) {
                creditNote.XeroAmount__c = payment.Invoice_Amount__c - creditNote.Amount__c;
                creditNote.CurrencyIsoCode = payment.CurrencyIsoCode;
            }
        }
    }

    public void beforeUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) { 
        Map<Id, CreditNote__c> newMap = (Map<Id, CreditNote__c>)so;
        for (CreditNote__c creditNote :newMap.values()) {
            if (creditNote.XeroAmount__c == NULL && creditNote.Payment__r.Invoice_Amount__c != NULL) {
                creditNote.XeroAmount__c = creditNote.Payment__r.Invoice_Amount__c - creditNote.Amount__c;
            }
        }
    }
    
    public void beforeDelete(List<SObject> so) {}

    public void afterInsert(List<SObject> so) {}
    
    public void afterUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {}
        
    public void afterDelete(List<SObject> so) {}

    public void andFinally() {} 
    
}