src/objects/CreditNote__c.object
<CustomObject>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Credit Notes</relationshipLabel>
        <relationshipName>CreditNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreditNoteEditCtrl.cls
public with sharing class CreditNoteEditCtrl {
    
    private ApexPages.StandardController stdController;
    
    public CreditNote__c creditNote {get; set;}
    public Boolean isSuccess {get; set;}
    
    public CreditNoteEditCtrl(ApexPages.StandardController stdController) {
        this.stdController = stdController;  
        this.creditNote = (CreditNote__c)stdController.getRecord();  
        
        if (String.isNotBlank(creditNote.Id)) {
        	creditNote = CreditNoteRepository.getCreditNoteById(creditNote.Id);                
        }
        if (ApexPages.currentPage().getParameters().containsKey('paymentId')) {
            creditNote.Payment__c = ApexPages.currentPage().getParameters().get('paymentId');            
        }
        isSuccess = true;
    }
    
    public void saveCreditNote() {
    	Savepoint sp = Database.setSavepoint();
        isSuccess = true;
        
        try {
        	upsert creditNote;
        } catch (Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getDmlMessage(1)));
            Database.rollback(sp);
            isSuccess = false;
        }
    }
    
    public void sendCreditNote() {
        List<XeroSync.InvoiceWrapper> responses = XeroSync.sendCreditNotes(new List<Id>{creditNote.Id});
            
        for (XeroSync.InvoiceWrapper response :responses) {
            if (response.status.equals(XeroSync.STATUS_SUCCESS)) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, response.message));
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, response.message));
            }
        }
        creditNote = CreditNoteRepository.getCreditNoteById(creditNote.Id);       
    }
}