src/objects/CreditNote__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Revised Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Credit Notes</relationshipLabel>
        <relationshipName>CreditNotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Authorised</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>XeroEntity__c</fullName>
        <formula>IF(ISBLANK(Payment__r.Project__r.Xero_Entity__c), Payment__r.Account__r.Xero_Entity__c, Payment__r.Project__r.Xero_Entity__c)</formula>
        <label>Xero Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XeroId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Xero Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>XeroNumber__c</fullName>
        <label>Xero Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Credit Note</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Credit Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <referenceTo>Sub_Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XeroEntity__c.object
<CustomObject>
    <fields>
        <fullName>XeroId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Xero Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>XeroSettings__c</fullName>
        <label>Xero Settings</label>
        <referenceTo>XeroSettings__c</referenceTo>
        <relationshipLabel>Xero Entities</relationshipLabel>
        <relationshipName>XeroEntities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Xero Entity</label>
    <nameField>
        <displayFormat>XE-{0000}</displayFormat>
        <label>Xero Entity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Entities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/XeroSettings__c.object
<CustomObject>
    <fields>
        <fullName>ConsumerKey__c</fullName>
        <label>ConsumerKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerSecret__c</fullName>
        <label>ConsumerSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrivateKey__c</fullName>
        <label>PrivateKey</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Xero Settings</label>
    <nameField>
        <label>XeroSettings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Xero Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreditNote.cls
global class CreditNote {
    
    public static String STATUS_SUBMITTED = 'Submitted';
    public static String STATUS_AUTHORISED = 'Authorised';
    public static String STATUS_PAID = 'Paid';

    // DEPRECATED
    /*public static Map<Id, XeroWrappers.XeroCreditNoteAllocationResponse> allocateCreditNotes(Set<Id> creditNoteIds) {
        Map<Id, CreditNote__c> creditNotes = new Map<Id, CreditNote__c>(CreditNoteRepository.getCreditNotesById(creditNoteIds));
        Map<Id, List<CreditNote__c>> creditNotesForXeroEntity = new Map<Id, List<CreditNote__c>>();

        for (CreditNote__c creditNote :creditNotes.values()) {
            if (!creditNotesForXeroEntity.containsKey(creditNote.XeroEntity__c)) {
                creditNotesForXeroEntity.put(creditNote.XeroEntity__c, new List<CreditNote__c> { creditNote });                    
            } else {
               creditNotesForXeroEntity.get(creditNote.XeroEntity__c).add(creditNote);                 
            }
        }
        
        Map<Id, XeroSettings__c> xeroEntities = new Map<Id, XeroSettings__c> ([
            SELECT ConsumerKey__c, ConsumerSecret__c, PrivateKey__c, Name
            FROM XeroSettings__c
            WHERE Id IN :creditNotesForXeroEntity.keySet()
        ]);

        Map<Id, XeroWrappers.XeroCreditNoteAllocationResponse> allocationResults = new Map<Id, XeroWrappers.XeroCreditNoteAllocationResponse>();
        for (Id xeroEntityId : xeroEntities.keySet()) {
            allocationResults.putAll(allocateCreditNotes(creditNotesForXeroEntity.get(xeroEntityId), xeroEntities.get(xeroEntityId)));
        }

        List<CreditNote__c> creditNotesToUpdate = new List<CreditNote__c>();
        List<Sub_Project__c> paymentsToUpdate = new List<Sub_Project__c>();
        for (Id creditNoteId :allocationResults.keySet()) {
            XeroWrappers.XeroCreditNoteAllocationResponse response = allocationResults.get(creditNoteId);
            
            if (response.xeroCreditNoteAllocations[0].ValidationErrors.isEmpty()) {
                CreditNote__c creditNote = creditNotes.get(creditNoteId);
                CreditNote__c creditNoteToUpdate = creditNote;
                creditNoteToUpdate.Status__c = 'Approved';
                creditNotesToUpdate.add(creditNoteToUpdate);  
                
                Sub_Project__c paymentToUpdate = new Sub_Project__c(Id = creditNote.Payment__c);
                paymentToUpdate.Invoice_Amount__c = creditNote.Payment__r.Invoice_Amount__c - creditNote.Amount__c;
                paymentsToUpdate.add(paymentToUpdate);
            }
        }
        update creditNotesToUpdate;
        update paymentsToUpdate;
        return allocationResults;
    }

    private static Map<Id, XeroWrappers.XeroCreditNoteAllocationResponse> allocateCreditNotes(List<CreditNote__c> creditNotes, XeroSettings__c xeroEntity) {
         Map<Id, XeroWrappers.XeroCreditNoteAllocationResponse> retVal = new Map<Id, XeroWrappers.XeroCreditNoteAllocationResponse>();
         for (CreditNote__c creditNote :creditNotes) {
            XeroWrappers.XeroCreditNoteAllocation creditNoteAlloc = new XeroWrappers.XeroCreditNoteAllocation(creditNote);
            XeroWrappers.XeroCreditNoteAllocationResponse response = XeroAPI.putCreditNoteAllocation(creditNoteAlloc, xeroEntity, creditNote);
            retVal.put(creditNote.Id, response);
         }
         return retVal;
    }
    */
    
    public static Map<Id, XeroWrappers.XeroCreditNote> sendCreditNotes(Set<Id> creditNoteIds) {
         Map<Id, CreditNote__c> creditNotes = new Map<Id, CreditNote__c> (CreditNoteRepository.getCreditNotesById(creditNoteIds));    
         Map<Id, XeroWrappers.XeroCreditNote> creditNoteResponse = sendCreditNotes(creditNotes.values());
         List<CreditNote__c> creditNotesToUpdate = new List<CreditNote__c>();        
         
        for (Id creditNoteId :creditNoteResponse.keySet()) {
            CreditNote__c creditNote = creditNotes.get(creditNoteId);
            if (creditNoteResponse.get(creditNoteId).ValidationErrors.isEmpty()) {
                creditNote.XeroId__c = creditNoteResponse.get(creditNoteId).CreditNoteId;
                creditNote.XeroNumber__c = creditNoteResponse.get(creditNoteId).CreditNoteNumber; 
                creditNote.Status__c = STATUS_SUBMITTED;                
                creditNotesToUpdate.add(creditNote);
            }
        }
        update creditNotesToUpdate;
        return creditNoteResponse;
    }           
    
    private static Map<Id, XeroWrappers.XeroCreditNote> sendCreditNotes(List<CreditNote__c> creditNotes) {
        Map<String, List<XeroWrappers.XeroCreditNote>> xeroCreditNotesForXeroEntity = new Map<String, List<XeroWrappers.XeroCreditNote>>();
        for (CreditNote__c creditNote : creditNotes) {
            XeroWrappers.XeroCreditNote xeroCreditNote = new XeroWrappers.XeroCreditNote(creditNote);
            if (!xeroCreditNotesForXeroEntity.containsKey(creditNote.XeroEntity__c)) {
                xeroCreditNotesForXeroEntity.put(creditNote.XeroEntity__c, new List<XeroWrappers.XeroCreditNote> { xeroCreditNote });                      
            } else {
               xeroCreditNotesForXeroEntity.get(creditNote.XeroEntity__c).add(xeroCreditNote);                 
            }
        }
        
        Map<Id, XeroSettings__c> xeroEntities = new Map<Id, XeroSettings__c> ([
            SELECT ConsumerKey__c, ConsumerSecret__c, PrivateKey__c, Name
            FROM XeroSettings__c
            WHERE Id IN :xeroCreditNotesForXeroEntity.keySet()
        ]);

        Map<Id, XeroWrappers.XeroCreditNote> retVal = new Map<Id, XeroWrappers.XeroCreditNote>();
        for (String xeroEntityId : xeroCreditNotesForXeroEntity.keySet()) {
            XeroWrappers.XeroCreditNoteResponse cnResponse = XeroAPI.postCreditNotes(xeroCreditNotesForXeroEntity.get(xeroEntityId), xeroEntities.get(xeroEntityId));
            if (cnResponse.StatusCode == 200 || cnResponse.StatusCode == 201) {
                for (XeroWrappers.XeroCreditNote xcn :cnResponse.xeroCreditNotes) {
                    retVal.put(creditNotes[0].Id, xcn);
                }
            }  
        }
        return retVal;        
    }
}