src/objects/CurrencyHistory__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Currency History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Currency History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Currency History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CurrencyHistoryTest.cls
@isTest
private class CurrencyHistoryTest {

    static testMethod void willCreateCurrencyHistoryRecord(){
        
        TestHelper.createAppSettings();
        Date dt = System.today();
        
        System.assert([SELECT Id FROM CurrencyHistory__c].isEmpty());
   	    
        test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new CurrencyLayerMockUpResponse());
    	CurrencyHistory.updateCurrencyRates(dt);
        
        test.stopTest();
        
        System.assertEquals(1, [SELECT Id FROM CurrencyHistory__c WHERE Date__c = :dt].size());
    }
}