src/objects/dlrs__LookupRollupCalculateJob__c.object
<CustomObject>
    <fields>
        <fullName>overdue__c</fullName>
        <formula>true</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>overdue</label>
        <type>Checkbox</type>
    </fields>
    <label>Lookup Rollup Calculate Job</label>
    <nameField>
        <displayFormat>LRCJ-{00000000}</displayFormat>
        <label>Lookup Rollup Calculate Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lookup Rollup Calculate Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/dlrs__LookupRollupSummaryScheduleItems__c.object
<CustomObject>
    <fields>
        <fullName>overdue__c</fullName>
        <formula>CreatedDate &lt; NOW() - 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>overdue</label>
        <type>Checkbox</type>
    </fields>
    <label>Lookup Rollup Summary Schedule Item</label>
    <nameField>
        <label>Lookup Rollup Summary Schedule Item Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lookup Rollup Summary Schedule Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EventLog__c.object
<CustomObject>
    <description>Record errors, events</description>
    <fields>
        <fullName>overdue__c</fullName>
        <formula>IF(ISPICKVAL(Status__c,&apos;Info&apos;), CreatedDate &lt; NOW() - 1, 
CreatedDate &lt; NOW() - 5)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>overdue</label>
        <type>Checkbox</type>
    </fields>
    <label>Event Log</label>
    <nameField>
        <displayFormat>EventLog-{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataCleaner.cls
global class DataCleaner implements Database.Batchable<sObject>, Schedulable  {

    public static final string DELETE_EVENT_LOG     = 'EventLog__c';
    public static final string DELETE_DLRS_JOB      = 'dlrs__LookupRollupCalculateJob__c';
    public static final string DELETE_DLRS_ITEMS    = 'dlrs__LookupRollupSummaryScheduleItems__c';

    public static final List<string> steps = new List<string>{
        DELETE_EVENT_LOG, DELETE_DLRS_JOB, DELETE_DLRS_ITEMS
    };

    global string currentStep;
    private string query;

    
   global void execute(SchedulableContext SC) {
		Database.executeBatch(new DataCleaner(),2000);
   }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global DataCleaner() {
        this(steps[0]);
    }

    global DataCleaner(string step) {
        currentStep=step;
        query = 'SELECT Id FROM ' + currentStep + ' WHERE overdue__c=true';
        query += ' LIMIT 40000';
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope) {
        delete scope;
    }

    global void finish(Database.BatchableContext BC) {
        Iterator<String> iter = steps.iterator();
        while (iter.hasNext()) {
            String step = iter.next();
            if (step == currentStep && iter.hasNext()) {
                String nextStep = iter.next();
                Database.executeBatch(new DataCleaner(nextStep), 2000);
            }
        }

    }
}