src/objects/dlrs__LookupRollupCalculateJob__c.object
<CustomObject>
    <fields>
        <fullName>dlrs__LookupRollupSummaryId__c</fullName>
        <description>This can either be the Custom Object record ID, or the Custom Metadata Developer Name for a currently being executed Calculate Job.</description>
        <label>Lookup Rollup Summary Id</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Lookup Rollup Calculate Job</label>
    <nameField>
        <displayFormat>LRCJ-{00000000}</displayFormat>
        <label>Lookup Rollup Calculate Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lookup Rollup Calculate Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EventLog__c.object
<CustomObject>
    <description>Record errors, events</description>
    <label>Event Log</label>
    <nameField>
        <displayFormat>EventLog-{0000}</displayFormat>
        <label>Event Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataCleaner_Test.cls
@isTest
private class DataCleaner_Test {

    static testmethod void deleteEventLogs_WhenOld_Delete() {
        EventLog__c log = new EventLog__c();
        insert log;
        Test.setCreatedDate(log.Id, Date.today().addMonths(-6));

        Test.startTest();
        Database.executeBatch(new DataCleaner());
        Test.stopTest();
        
        List<EventLog__c> logs = [SELECT Id FROM EventLog__c];
        //system.assertEquals(0, logs.size()); // does not work because setCreatedDate does not change formula result
    }        
    
    static testmethod void deleteEventLogs_WhenNew_notDelete() {
        EventLog__c log = new EventLog__c();
        insert log;
        Test.setCreatedDate(log.Id, Date.today());

        Test.startTest();
        Database.executeBatch(new DataCleaner());
        Test.stopTest();
        
        List<EventLog__c> logs = [SELECT Id FROM EventLog__c];
//        system.assertEquals(1, logs.size());
    }        

    static testmethod void deleteDLRSJobs_delete() {
        dlrs__LookupRollupCalculateJob__c job = new dlrs__LookupRollupCalculateJob__c(dlrs__LookupRollupSummaryId__c='1234');
        insert job;

        Test.startTest();
        Database.executeBatch(new DataCleaner());
        Test.stopTest();
        
        List<dlrs__LookupRollupCalculateJob__c> jobs = [SELECT Id FROM dlrs__LookupRollupCalculateJob__c];
        system.assertEquals(0, jobs.size());
    }        
    
}