src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Profile__c</fullName>
        <label>Billing Profile</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Strike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Billing Profile</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strike</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign_Status__c</fullName>
        <formula>IF(
AND( Start_Date__c &lt;= TODAY(),TODAY() &lt;= End_Date__c) ,&quot;In Progress&quot;,
IF(TODAY() &gt; End_Date__c,&quot;Finished&quot;,
&quot;Planned&quot;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Spend_Defined_on_IO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Spend Defined on IO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_running__c</fullName>
        <formula>End_Date__c - Start_Date__c +1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days running</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Terms__c</fullName>
        <formula>BillingCondition__r.Discount_Terms__c != 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount Terms</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpectedRebate__c</fullName>
        <formula>BillingCondition__r.Rebate_Rate__c * (
	IF (CONTAINS(BillingCondition__r.Name, &apos;Instant Rebate&apos;),
		(Client_Spend__c - Media_Order__c) ,
    		IF (ISPICKVAL(Margin_Type__c, &apos;% of Media&apos;), Media_Order__c, Client_Spend__c)  
	)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Rebate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <summarizedField>Sub_Project__c.Expected_Gross_Profit__c</summarizedField>
        <summaryForeignKey>Sub_Project__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Final_Margin__c</fullName>
        <formula>IF(AND(Client_Spend__c != 0, Invoices_for_Processing__c = 0), 
ActualGrossProfit__c / Client_Spend__c, 
NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <formula>Client_Spend__c - Media_Order__c - ExpectedRebate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Gross Profit OLD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Margin_Type__c</fullName>
        <label>Margin Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Budget</fullName>
                    <default>true</default>
                    <label>% of Budget</label>
                </value>
                <value>
                    <fullName>% of Media</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <formula>IF(ISPICKVAL(Margin_Type__c,&apos;% of Media&apos;),
Client_Spend__c / (1+Margin__c),
Client_Spend__c * (1-Margin__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Billing Profile</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Maker</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Strike</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Sub_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdWordsSpend__c</fullName>
        <label>Media Spend</label>
        <summarizedField>Payment__c.AdWordsSpend__c</summarizedField>
        <summaryForeignKey>Payment__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AdWords_Spend_report__c</fullName>
        <formula>IF(TODAY() &gt;= End_Date__c+3, AdWordsSpend__c, Media_Order__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Spend (report)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ad_Serving_Costs__c</fullName>
        <label>Ad Serving Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Conditions__c</fullName>
        <formula>Project__r.BillingCondition__r.Name</formula>
        <label>Billing Conditions</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Profile__c</fullName>
        <formula>TEXT(Account_Type__c)</formula>
        <label>Billing Profile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Status__c</fullName>
        <formula>IF( 
AND( Start_Date__c &lt;= TODAY(),TODAY() &lt;= End_Date__c) ,&quot;In Progress&quot;, 
IF(TODAY() &gt; End_Date__c,&quot;Finished&quot;, 
&quot;Planned&quot;) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Spend_Defined_on_IO__c</fullName>
        <formula>Project__r.Client_Spend_Defined_on_IO__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Spend Defined on IO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_running__c</fullName>
        <formula>End_Date__c - Start_Date__c +1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days running</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Terms__c</fullName>
        <label>Discount Terms</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Violation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Discount Violation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExpectedRebate__c</fullName>
        <formula>Rebate__c * (
  IF (CONTAINS(Billing_Condition__c, &apos;Instant Rebate&apos;),
    (Client_Spend__c - Media_Order__c),
    IF (TEXT(Margin_Type__c) = &apos;% of Media&apos;, Media_Order__c, Client_Spend__c)
  )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Rebate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expected_Gross_Profit__c</fullName>
        <label>Expected Gross Profit</label>
        <summarizedField>Payment__c.Expected_Gross_Profit_New__c</summarizedField>
        <summaryForeignKey>Payment__c.Payment__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Final_Margin__c</fullName>
        <formula>if(and(Client_Spend__c &lt;&gt; 0, 
       or(Checked__c, Synced_with_Xero__c, !ispickval(XeroStatus__c,&quot;&quot;)
          )
        ), 
Gross_Profit_Report__c / Client_Spend__c, 
null)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Final Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_Profit_Report__c</fullName>
        <formula>IF(Synced_with_Xero__c || Checked__c,
   Actual_Gross_Profit_Social_Rollup__c + Actual_Gross_Profit_YT_Rollup__c,
Expected_Gross_Profit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <formula>Client_Spend__c - Media_Order__c - ExpectedRebate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Gross Profit OLD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Margin_Type__c</fullName>
        <label>Margin Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>% of Budget</fullName>
                    <default>true</default>
                    <label>% of Budget</label>
                </value>
                <value>
                    <fullName>% of Media</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Margin__c</fullName>
        <label>Margin</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Media_Order__c</fullName>
        <formula>IF(ISPICKVAL(Margin_Type__c,&apos;% of Media&apos;),
   Client_Spend__c / (1+Margin__c),
   Client_Spend__c * (1-Margin__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Media Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentCtrl.cls
public with sharing class PaymentCtrl {

    public Sub_Project__c payment { get;set; }
    private ApexPages.StandardController stdController;

    public List<Utility.FieldSetDefinition> fsList {get;set;}
    public Boolean showEditPopUpMessage { get;set; }
    public Boolean saveAndNew { get;set; }

    public Boolean savedSuccessfully { get;set; }

    private Decimal baseClientSpend;

    public PaymentCtrl(ApexPages.StandardController stdController) {
        this.payment = (Sub_Project__c) stdController.getRecord();
        this.stdController = stdController;
    }

    public void onEditReady() {
        this.payment = [SELECT Account__c, Account_Type__c, AdWordsSpend__c, AdWords_Spend_report__c, Ad_Serving_Costs__c,
                Billing_Conditions__c, Billing_Profile__c, Campaign_Status__c, Checked__c, Client_Spend__c,
                Client_Spend_Defined_on_IO__c, CreatedById, CreatedDate, CurrencyIsoCode, Days_running__c,
                Discount_Violation__c, Discount_Terms__c, End_Date__c, ExpectedRebate__c, Final_Margin__c, IsDeleted,
                Expected_Gross_Profit__c ,Gross_Profit__c, Gross_Profit_report__c, Id, Invoice__c, Invoice_Amount__c,
                LastActivityDate, LastModifiedById, LastModifiedDate, LastReferencedDate, LastViewedDate,
                Margin__c, Margin_Type__c, Media_Order__c, Name, Opportunity__c, Paid__c,
                Payment_Date__c, PaymentType__c, Project__c, ProjectID__c, RecordTypeId, RecordType.Name,
                Start_Date__c, Synced_with_Xero__c, SystemModstamp, Total_Revenue__c, Total_Revenue_report__c,
                Suggested_Client_Spend__c, Xero_ID__c, Xero_Invoice__c ,  XeroStatus__c,
                (SELECT CreatedById, CreatedDate, Field, Id, IsDeleted, NewValue, OldValue, ParentId FROM Histories ORDER BY CreatedDate DESC LIMIT 10)
            FROM Sub_Project__c
            WHERE Id =: this.payment.Id
        ];

        String paymentType = this.payment.RecordType.Name;
        Map<String,Schema.FieldSet> fsMap = Utility.getObjectFieldSetsMap('Sub_Project__c');
        fsList = new List<Utility.FieldSetDefinition>();
        for (Schema.FieldSet fs :fsMap.values()) {
            if (!fs.getName().contains('Editfields')) {
                continue;
            }
            fsList.add(new Utility.FieldSetDefinition(fs));
        }

        showEditPopUpMessage = false;
        saveAndNew = false;
        baseClientSpend = this.payment.Client_Spend__c;
    }

    public PageReference submitClientSpend() {
        showEditPopUpMessage = false;
        savedSuccessfully = true;

        try {
            update this.payment;
        } catch (DmlException e) {
            ApexPages.Message msg = new apexPages.Message(Apexpages.Severity.ERROR, e.getDmlMessage(0));
            ApexPages.addMessage(msg);
            savedSuccessfully = false;
            return null;
        }

        if (saveAndNew) {
            ApexPages.currentPage().setRedirect(true);
            return new PageReference('/' + stdController.getRecord().getSObjectType().getDescribe().getKeyPrefix() + '/e');
        }
        return new PageReference('/' + this.payment.Id);
    }

    public PageReference save() {
        if (payment.Client_Spend_Defined_on_IO__c == true && payment.Client_Spend__c != baseClientSpend) {
            showEditPopUpMessage = true;
            return null;
        }

        savedSuccessfully = true;
        try {
            update payment;
        } catch (DmlException e) {
            ApexPages.Message msg = new apexPages.Message(Apexpages.Severity.ERROR, e.getDmlMessage(0));
            ApexPages.addMessage(msg);
            savedSuccessfully = false;
            return null;
        }

        if (saveAndNew) {
            ApexPages.currentPage().setRedirect(true);
            return new PageReference('/' + stdController.getRecord().getSObjectType().getDescribe().getKeyPrefix() + '/e');
        }
        return new PageReference('/' + this.payment.Id);
    }


    public PageReference cancelUpdate() {
        showEditPopUpMessage = false;
        return new PageReference('/' + this.payment.Id);
    }
}