src/objects/MakeGood__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Goods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Make Good</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Make Good</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MakeGoodHandlerTest.cls
@isTest
public class MakeGoodHandlerTest {

    private static MakeGood__c makeGood;
    private static Date today = System.today();
    private static Project__c contract;

    @isTest
    public static void testSetNames ()
    {
        Account acc = TestHelper.createAccount();
        contract = TestHelper.createContract(acc.Id);
        createGood();
    }
    
    private static void createGood() {
        
        makeGood = new MakeGood__c();
        makeGood.Contract__c = contract.Id;
        makeGood.StartDate__c = today.addDays(-1);
        makeGood.EndDate__c = today.addDays(1);
        insert makeGood;
    }
}