src/objects/MakeGood__c.object
<CustomObject>
    <fields>
        <fullName>NameFormula__c</fullName>
        <formula>&apos;MG&apos; + Contract__r.Project_Number__c</formula>
        <label>Name Formula</label>
        <type>Text</type>
    </fields>
    <label>Make Good</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Make Good</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MakeGoodHandler.cls
public class MakeGoodHandler implements ITrigger {
    public MakeGoodHandler() {}

    public void bulkBefore() {}

    public void bulkAfter() {}

    public void beforeInsert(List<SObject> so) {
        List<MakeGood__c> makeGoods = (List<MakeGood__c>)so;
        setNames(makeGoods);
    }

    public void beforeUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {
        Map<Id, MakeGood__c> newMap = (Map<Id, MakeGood__c>)so;
        setNames(newMap.values());
    }

    public void beforeDelete(List<SObject> so) {}

    public void afterInsert(List<SObject> so) {}

    public void afterUpdate(Map<Id, SObject> oldSo, Map<Id, SObject> so) {}

    public void afterDelete(List<SObject> so) {}

    public void andFinally() {}

    private void setNames(List<MakeGood__c> makeGoods) {
        for (MakeGood__c makeGood : makeGoods) {
            makeGood.Name = makeGood.NameFormula__c;
        }
    }
}