src/objects/MM_Spendings__c.object
<CustomObject>
    <label>Media Manager Spendings</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Media Manager Spendings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Manager Spendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>ClientServicesRep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Services Rep</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select user with Client Services profile.</errorMessage>
            <filterItems>
                <field>User.Client_Services_Rep__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ClientServiceContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gaps_Exist_Between_Projects__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Gaps Exist Between Projects</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceNotificationCtrlTest.cls
@isTest
private class InvoiceNotificationCtrlTest {

    static testMethod void testDisplayInvoices() {
        Account acc = TestHelper.createAccount();
        User usr = TestHelper.createUser();

        Opportunity opp1 = TestHelper.createOpportunity(usr, acc);
        Opportunity opp2 = TestHelper.createOpportunity(usr, acc);
        insert new List<Opportunity> {opp1, opp2};

        Project__c contract1 = TestHelper.createContractNoInsert(acc.Id, 'contract1', opp1.Id);
        contract1.Gaps_Exist_Between_Projects__c = true;

        Project__c contract2 = TestHelper.createContractNoInsert(acc.Id, 'contract2', opp2.Id);
        contract2.Gaps_Exist_Between_Projects__c = true;
        contract2.ClientServicesRep__c = TestHelper.createClientServiceUser().Id;
        insert new List<Project__c> {contract1, contract2};

        Test.startTest();
            delete [SELECT Id FROM Sub_Project__c];

            Sub_Project__c payment1 = TestHelper.createPaymentNoInsert(contract1);
            Sub_Project__c payment2 = TestHelper.createPaymentNoInsert(contract2);
            insert new List<Sub_Project__c> {payment1, payment2};

            MM_Spendings__c mmSpending1 = TestHelper.createMediaSpendings(contract1.Id, contract1.End_Date__c);
            MM_Spendings__c mmSpending2 = TestHelper.createMediaSpendings(contract2.Id, contract2.End_Date__c);
            insert new List<MM_Spendings__c>{mmSpending1, mmSpending2};

            InvoiceNotificationCtrl ctrl = new InvoiceNotificationCtrl();
            ctrl.ClientService = contract2.ClientServicesRep__c;
        Test.stopTest();

        System.assertEquals(1, ctrl.getPayments().size());
    }
}