src/objects/MM_Spendings__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivered__c</fullName>
        <label>Delivered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Media Manager Spendings</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Media Manager Spendings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Manager Spendings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <formula>IF(ISBLANK(OpportunityPlatform__c), Payment__r.Project__r.Project_ID__c, OpportunityPlatform__r.Platform__r.Prefix__c + Payment__r.Project__r.Project_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Media_Spend__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Media Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivered__c</fullName>
        <label>Delivered</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MMSpending__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Media Manager Spendings</label>
        <referenceTo>MM_Spendings__c</referenceTo>
        <relationshipLabel>Contract Media Spend</relationshipLabel>
        <relationshipName>ContractMediaSpend</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Contract Media Spend</relationshipLabel>
        <relationshipName>ContractMediaSpends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Contract Media Spend</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Media Spend</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SCH_BATCH_MediaSpendSummarizer_Test.cls
@isTest
public class SCH_BATCH_MediaSpendSummarizer_Test {

    testmethod static void summarizeMMSpends() {
        MM_Spendings__c mediaSpending1;
        MM_Spendings__c mediaSpending2;
        Set<String> strikeIds;
        Map<Id, MM_Spendings__c> mediaSpendings;
        Map<Id, Project_Media_Spend__c> contractSpendingForMediaManagerSpending;   
        strikeIds = new Set<String>();
        mediaSpendings = new Map<Id, MM_Spendings__c>();
        contractSpendingForMediaManagerSpending= new Map<Id, Project_Media_Spend__c>(); 
        
        TestHelper.setupEnv();
		Project__c contract = TestHelper.contract; 
                
        mediaSpending1 = TestHelper.createMediaSpendings(TestHelper.contract.Id, TestHelper.contract.End_Date__c);          
        mediaSpending2 = TestHelper.createMediaSpendings(TestHelper.contract.Id, TestHelper.contract.End_Date__c.addDays(-1));  
              
        insert new List<MM_Spendings__c> {mediaSpending1, mediaSpending2};


        List<MM_Spendings__c> originalMMSpends =  [select ID FROM MM_Spendings__c];
        system.assertEquals(2,originalMMSpends.size());
        
        Test.startTest();
        Database.executeBatch(new SCH_BATCH_MediaSpendSummarizer());
        Test.stopTest();
        
        List<MM_Spendings__c> summarizedMMSpends =  [select ID FROM MM_Spendings__c];
        system.assertEquals(1,summarizedMMSpends.size());
             
    }
    
    testmethod static void summarizePMS() {
        MM_Spendings__c mediaSpending1;
        MM_Spendings__c mediaSpending2;
        Set<String> strikeIds;
        Map<Id, MM_Spendings__c> mediaSpendings;
        Map<Id, Project_Media_Spend__c> contractSpendingForMediaManagerSpending;   
        strikeIds = new Set<String>();
        mediaSpendings = new Map<Id, MM_Spendings__c>();
        contractSpendingForMediaManagerSpending= new Map<Id, Project_Media_Spend__c>(); 
        
        TestHelper.setupEnv();
		Project__c contract = TestHelper.contract; 
                
        mediaSpending1 = TestHelper.createMediaSpendings(TestHelper.contract.Id, TestHelper.contract.End_Date__c);          
        mediaSpending2 = TestHelper.createMediaSpendings(TestHelper.contract.Id, TestHelper.contract.End_Date__c.addDays(-1));  
              
        insert new List<MM_Spendings__c> {mediaSpending1, mediaSpending2};
            
        List<Project_Media_Spend__c> originalPMS =  [SELECT Delivered__c, Amount__c, Project__r.ProjectID__c, Date__c, MMSpending__c 
                                                          FROM Project_Media_Spend__c];
        system.assertEquals(2,originalPMS.size());
        
        Test.startTest();
        Database.executeBatch(new SCH_BATCH_MediaSpendSummarizer());
        Test.stopTest();
        
        List<Project_Media_Spend__c> summarizedPMS =  [SELECT Delivered__c, Amount__c, Project__r.ProjectID__c, Date__c, MMSpending__c 
                                                          FROM Project_Media_Spend__c];
        system.assertEquals(1,summarizedPMS.size());
           
    }    
    
    testmethod static void setLookupsOnSummarizedRecords() {
        MM_Spendings__c mediaSpending1;
        MM_Spendings__c mediaSpending2;
        Set<String> strikeIds;
        Map<Id, MM_Spendings__c> mediaSpendings;
        Map<Id, Project_Media_Spend__c> contractSpendingForMediaManagerSpending;   
        strikeIds = new Set<String>();
        mediaSpendings = new Map<Id, MM_Spendings__c>();
        contractSpendingForMediaManagerSpending= new Map<Id, Project_Media_Spend__c>(); 
        
        TestHelper.setupEnv();
		Project__c contract = TestHelper.contract; 
                
        mediaSpending1 = TestHelper.createMediaSpendings(TestHelper.contract.Id, TestHelper.contract.End_Date__c);          
        mediaSpending2 = TestHelper.createMediaSpendings(TestHelper.contract.Id, TestHelper.contract.End_Date__c.addDays(-1));  
              
        insert new List<MM_Spendings__c> {mediaSpending1, mediaSpending2};
            
        Test.startTest();
        Database.executeBatch(new SCH_BATCH_MediaSpendSummarizer());
        Test.stopTest();
        
        List<MM_Spendings__c> summarizedMMSpends =  [select ID FROM MM_Spendings__c];
        List<Project_Media_Spend__c> summarizedPMS =  [SELECT Delivered__c, Amount__c, Project__r.ProjectID__c, Date__c, MMSpending__c 
                                                          FROM Project_Media_Spend__c];
        
        system.assertEquals(summarizedMMSpends[0].Id, summarizedPMS[0].MMSpending__c);        
    }        
}