src/objects/NotificatorSetting__c.object
<CustomObject>
    <fields>
        <fullName>recipient__c</fullName>
        <label>Error Notification Recipient Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Notificator Setting</label>
    <nameField>
        <label>NotificatorSetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NotificatorStorage__c.object
<CustomObject>
    <fields>
        <fullName>InfoPercentageThreshold__c</fullName>
        <defaultValue>75</defaultValue>
        <inlineHelpText>First notification will be sent if current percent usage will be above this threshold.</inlineHelpText>
        <label>Percent Info Threshold</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Setting__c</fullName>
        <label>Notificator Setting</label>
        <referenceTo>NotificatorSetting__c</referenceTo>
        <relationshipLabel>Notificator Storages</relationshipLabel>
        <relationshipName>NotificatorStorages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WarningPercentageThreshold__c</fullName>
        <defaultValue>95</defaultValue>
        <inlineHelpText>Final notification will be sent if current percent usage will be above this threshold.</inlineHelpText>
        <label>Percent Warning Threshold</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Notificator Storage</label>
    <nameField>
        <label>Notificator Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Storages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NotificatorTestUtils.cls
@isTest
public class NotificatorTestUtils {

    public static final string StoragesPageRawData = '<th scope="row" class=" dataCell  ">File Storage</th><td class=" dataCell  numericalColumn">250.0&nbsp;MB</td><td class=" dataCell  numericalColumn">146.0&nbsp;MB</td><td class=" dataCell  numericalColumn">58%</td>'
            + '<th scope="row" class=" dataCell  ">Data Storage</th><td class=" dataCell  numericalColumn">250.0&nbsp;MB</td><td class=" dataCell  numericalColumn">112.0&nbsp;MB</td><td class=" dataCell  numericalColumn">45%</td>';

    public static NotificatorSetting__c prepareTestNotificator() {        
        NotificatorSetting__c notificator = new NotificatorSetting__c(recipient__c = 'test@notificator.com');
        insert notificator;

        List<NotificatorStorage__c> ns = new List<NotificatorStorage__c>{
            new NotificatorStorage__c(Name = 'File Storage', Setting__c = notificator.Id),
            new NotificatorStorage__c(Name = 'Data Storage', Setting__c = notificator.Id)
        };                    
        insert ns;

        return notificator;
    }

    public static StorageOCR prepareTestStorageOCR(Integer info, Integer warning) {
        return new StorageOCR(new NotificatorStorage__c(Name = 'File Storage', WarningPercentageThreshold__c = warning, InfoPercentageThreshold__c = info, Status__c = 'OK'));
    }

}