src/objects/NotificatorSetting__c.object
<CustomObject>
    <fields>
        <fullName>recipient__c</fullName>
        <label>Error Notification Recipient Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Notificator Setting</label>
    <nameField>
        <label>NotificatorSetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NotificatorStorage__c.object
<CustomObject>
    <fields>
        <fullName>InfoPercentageThreshold__c</fullName>
        <defaultValue>75</defaultValue>
        <inlineHelpText>First notification will be sent if current percent usage will be above this threshold.</inlineHelpText>
        <label>Percent Info Threshold</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Setting__c</fullName>
        <label>Notificator Setting</label>
        <referenceTo>NotificatorSetting__c</referenceTo>
        <relationshipLabel>Notificator Storages</relationshipLabel>
        <relationshipName>NotificatorStorages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WarningPercentageThreshold__c</fullName>
        <defaultValue>95</defaultValue>
        <inlineHelpText>Final notification will be sent if current percent usage will be above this threshold.</inlineHelpText>
        <label>Percent Warning Threshold</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Notificator Storage</label>
    <nameField>
        <label>Notificator Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Storages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NotificatorSingleton.cls
public class NotificatorSingleton {
    
    private static NotificatorSetting__c notificator;
    public static NotificatorSetting__c getNotificator() {
            if (notificator == null) init();
            return notificator;
    }
    
    private static List<StorageOCR> storages;
    public static List<StorageOCR> getStorages() {
            if (storages == null) init();
            return storages;
    }
    
    private static void init() {
        try {
            loadNotificator();
        } catch (System.QueryException ex) {
            initNewNotificator();
        }
    }

    private static void loadNotificator() {
        notificator = [
                SELECT recipient__c, (
                        SELECT ID, Name, InfoPercentageThreshold__c, WarningPercentageThreshold__c, Status__c, Setting__c
                        FROM NotificatorStorages__r LIMIT 100
                )
                FROM NotificatorSetting__c LIMIT 1
        ];

        storages = new List<StorageOCR>();
        for (NotificatorStorage__c nt: notificator.NotificatorStorages__r) {
            storages.add(new StorageOCR(nt));
        }
    }

    public static void initNewNotificator() {
        notificator = new NotificatorSetting__c();
        initStorageList();
    }

    
    private static void initStorageList() {
        List<String> storageNames = new List<String> {
            StorageDictionary.DataByLanguage.get(UserInfo.getLanguage()),
            StorageDictionary.FileByLanguage.get(UserInfo.getLanguage())                
        };
        storages = new List<StorageOCR>();

        for (String name: storageNames) {
            NotificatorStorage__c ns = new NotificatorStorage__c(Name = name);
            StorageOCR ocr = new StorageOCR(ns);
            if(ocr.isValid) storages.add(ocr);              
        }
    }

}