src/objects/NotificatorSetting__c.object
<CustomObject>
    <label>Notificator Setting</label>
    <nameField>
        <label>NotificatorSetting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NotificatorStorage__c.object
<CustomObject>
    <fields>
        <fullName>InfoPercentageThreshold__c</fullName>
        <defaultValue>75</defaultValue>
        <inlineHelpText>First notification will be sent if current percent usage will be above this threshold.</inlineHelpText>
        <label>Percent Info Threshold</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Notificator Storage</label>
    <nameField>
        <label>Notificator Storage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notificator Storages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NotificatorJob_Test.cls
@isTest 
private class  NotificatorJob_Test {
    
    static testMethod void StorageLicenseCheck_UpdateAlertStatus() {
       NotificatorSetting__c notificator = NotificatorTestUtils.prepareTestNotificator();
        
       NotificatorStorage__c storageToUpdate = [SELECT Id, Name, Status__c FROM NotificatorStorage__c WHERE Name='File Storage'];
        
       storageToUpdate.InfoPercentageThreshold__c=10;
       update storageToUpdate;

       Test.startTest();
       NotificatorJob.notify();
       Test.stopTest();
        
       storageToUpdate = [SELECT Id, Name, Status__c FROM NotificatorStorage__c WHERE Name='File Storage'];
       system.assertEquals('Info',storageToUpdate.Status__c); 
    }

}