src/objects/OpportunityAdPlacement__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>ContractAdPlacements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityPlatform__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Opportunity Platform</label>
        <referenceTo>OpportunityPlatform__c</referenceTo>
        <relationshipLabel>Opportunity Ad Placements</relationshipLabel>
        <relationshipName>OpportunityAdPlacements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Ad Placement</label>
    <nameField>
        <displayFormat>OAP-{0000}</displayFormat>
        <label>Opportunity Ad Placement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Ad Placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>ContractPlatforms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InvoicingType__c</fullName>
        <formula>TEXT(Opportunity__r.InvoicingType__c)</formula>
        <label>Invoicing Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Opportunity__r.Strike_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_Spend__c</fullName>
        <label>Client Spend</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <formula>HYPERLINK( &apos;https://strike.my.salesforce.com/&apos;&amp;Project__r.Id , Project__r.Name  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/VideoUrl__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Creative</label>
    <nameField>
        <label>Creative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Contract.cls
public class Contract {
    public static String BILLING_CONDITION_EXTECH = 'Extech';
    public static String BILLING_CONDITION_NORMAL = 'Normal';
    public static String INVOICING_TYPE_ONE = 'One Invoice';
    public static String PAYMENT_TYPE_NET_30 = 'Net 30';
    public static String PAYMENT_TYPE_NET_45 = 'Net 45';

    public static void updateContractFromOpportunity(Map<Id, Project__c> opportunityContract) {
        Map<Id, List<VideoUrl__c>> opportunityVideos = VideoUrlRepository.getVideosForOpportunities(opportunityContract.keySet());
        Map<Id, List<OpportunityAdPlacement__c>> opportunityAdPlacements = PlatformRepository.getOpportunityAdPlacementsForOpportunities(opportunityContract.keySet());
        Map<Id, List<OpportunityPlatform__c>> opportunityPlatforms = PlatformRepository.getPlatformsForOpportunities(opportunityContract.keySet());
        
        List<OpportunityPlatform__c> opportunityPlatformsToUpdate = new List<OpportunityPlatform__c>();
        List<OpportunityAdPlacement__c> opportunityAdPlacementsToUpdate = new List<OpportunityAdPlacement__c>();
        List<VideoUrl__c> videosToUpdate = new List<VideoUrl__c>();
        
        for (Id oppId : opportunityVideos.keySet()) {
            Id contractId = opportunityContract.get(oppId).Id;
            for (VideoUrl__c video : opportunityVideos.get(oppId)) {
                video.Contract__c = contractId;  
                videosToUpdate.add(video);
            }
        }
        
        for (Id oppId : opportunityAdPlacements.keySet()) {
            Id contractId = opportunityContract.get(oppId).Id;
            for (OpportunityAdPlacement__c opportunityAdPlacement : opportunityAdPlacements.get(oppId)) {
                opportunityAdPlacement.Contract__c = contractId;  
                opportunityAdPlacementsToUpdate.add(opportunityAdPlacement);
            }
        }
        
        for (Id oppId : opportunityPlatforms.keySet()) {
            Id contractId = opportunityContract.get(oppId).Id;
            for (OpportunityPlatform__c opportunityPlatform : opportunityPlatforms.get(oppId)) {
                opportunityPlatform.Contract__c = contractId;
                opportunityPlatformsToUpdate.add(opportunityPlatform);
            }
        }

        update videosToUpdate;
        update opportunityPlatformsToUpdate;
        update opportunityAdPlacementsToUpdate;
    }
    
    public static void createNewPayments(List<Project__c> contracts) {
        List<Sub_Project__c> subProjToInsert = new List<Sub_Project__c>();

        Integer monthsBetween;
        Sub_Project__c subProject;
        Date myDate;
        Decimal daysInMonth, totalClientSpend, totalDays;
        String startD, endD;

        for (Project__c pr : contracts) {
            totalDays = pr.Start_Date__c.daysBetween(pr.End_Date__c) + 1;
            monthsBetween = pr.Start_Date__c.monthsBetween(pr.End_Date__c) + 1;
            totalClientSpend = 0;

            if (monthsBetween == null || monthsBetween == 0 || pr.InvoicingType__c == Contract.INVOICING_TYPE_ONE) {
                monthsBetween = 1;
            }

            for (Integer i = 0; i < monthsBetween; i++) {
                subProject = Utility.copyContractDataToPayment(pr);
                myDate = pr.Start_Date__c.addMonths(i);
                if (i == 0) {
                    subProject.Start_Date__c = myDate;
                } else {
                    subProject.Start_Date__c = Date.newInstance(myDate.year(), myDate.month(), 1);
                }
                subProject.End_Date__c  = Date.newInstance(myDate.year(), myDate.month(), Date.daysInMonth(myDate.year(), myDate.month()));
                if (subProject.End_Date__c > pr.End_Date__c || (i == (monthsBetween - 1) )) {
                    subProject.End_Date__c = pr.End_Date__c;
                }
                daysInMonth  = subProject.Start_Date__c.daysBetween(subProject.End_Date__c) + 1;
                subProject.Client_Spend__c = (daysInMonth / totalDays * pr.Client_Spend__c).setscale(2) ;
                subProject.Client_Spend__c = (subProject.Client_Spend__c).round(System.RoundingMode.DOWN);
                totalClientSpend += subProject.Client_Spend__c;
                startD = String.valueOf(subProject.Start_Date__c).replaceAll('-', '.');
                endD = String.valueOf(subProject.End_Date__c).replaceAll('-', '.');
                subProject.Name = '[' + pr.Project_ID__c + ' - ' + startD + ' - ' + endD + ']';
                subProjToInsert.add(subProject);
            }
            
            if (pr.Client_Spend__c > totalClientSpend){
                subProject.Client_Spend__c += (pr.Client_Spend__c - totalClientSpend);
            }
        }

        if (!subProjToInsert.isEmpty()) {
            insert subProjToInsert;
        }
    }
}