src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Flight_End__c</fullName>
        <inlineHelpText>The date that the campaign will finish.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Start__c</fullName>
        <inlineHelpText>The date that the campaign will start.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adwords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Reddit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                    <isActive>false</isActive>
                    <label>Instagram</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityPlatform__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>ContractPlatforms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <referenceTo>Platform__c</referenceTo>
        <relationshipLabel>Opportunity Platforms</relationshipLabel>
        <relationshipName>OpportunityPlatforms</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Opportunity Platform</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Opportunity Platform</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Platforms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Platform__c.object
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LastModifiedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LastModifiedBy</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PerformMMSync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Given contract should be synchronized to MM.</description>
        <label>Perform MM Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VideoUrl__c.object
<CustomObject>
    <fields>
        <fullName>ClickThroughURL__c</fullName>
        <label>Click Through URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Video</fullName>
                    <default>true</default>
                    <label>Video</label>
                </value>
                <value>
                    <fullName>Carousel</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Page Post</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsPlaceholder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Placeholder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AdWords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Display Network</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rotation__c</fullName>
        <label>Rotation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Creative</label>
    <nameField>
        <label>Creative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VideoUrlsComponentCtrl.cls
public class VideoUrlsComponentCtrl
{
    public String contract {get; set;}
    public String opportunity {get; set;}
    public List<VideoUrl__c> urls {get; set;}
    public Integer videoUrlRow {get; set;}
    public Blob csvFileBody{get;set;}
    public string csvAsString{get;set;}
    
    public VideoUrlsComponentCtrl()
    {
        urls = new List<VideoUrl__c>();
    }
    
    public List<SelectOption> getAvailablePlatforms() {
        
        Set<SelectOption> platforms;
        String projectId = contract;
        List<SelectOption> retVal = new List<SelectOption>();
        
        if (!string.isBlank(projectId) && platforms == NULL)
        {
            platforms = new Set<SelectOption>();
            Map<Id, List<OpportunityPlatform__c>> contractPlatforms = PlatformRepository.getPlatformsForContracts(new Set<Id> {projectId});
            
            if (contractPlatforms.containsKey(projectId))
            {
                for(OpportunityPlatform__c contractPlatform : contractPlatforms.get(projectId)) 
                {
                    platforms.add(new SelectOption(contractPlatform.Platform__r.Name, contractPlatform.Platform__r.Name));
                }
                
                for(VideoUrl__c url: urls) {
                    if(url.Platform__c!=null && url.Platform__c!='')
                        platforms.add(new SelectOption(url.Platform__c, url.Platform__c));
                }
            }
        }
        
        if (!string.isBlank(opportunity) && platforms == NULL)
        {
            platforms = new Set<SelectOption>();
            Opportunity opp = OpportunityRepository.getOpportunityById(opportunity);
            
            for(OpportunityPlatform__c oppPlatform : opp.OpportunityPlatforms__r) 
            {
                platforms.add(new SelectOption(oppPlatform.Platform__r.Name, oppPlatform.Platform__r.Name));
            }
            
            for(VideoUrl__c url: urls) {
                if(url.Platform__c!=null && url.Platform__c!='')
                    platforms.add(new SelectOption(url.Platform__c, url.Platform__c));
            }            
            
        }        
        
        if(platforms.size()>1) {
            retVal.add(new SelectOption('', ''));
        }
        retVal.addAll(platforms);        
        return retVal;
    }
    
    public PageReference importCSVFile(){ 
        try{
            try
            {
                csvAsString= csvFileBody.toString();
            }
            catch (NullPointerException e)
            {
                ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'No file selected!');
                ApexPages.addMessage(errorMessage);
                return null;                    
            }
            
            String[] csvFileLines = csvAsString.split('\n'); 
            List<VideoUrl__c> newUrls = new List<VideoUrl__c>();
            for(Integer i=1;i<csvFileLines.size();i++){
                VideoUrl__c newUrl = new VideoUrl__c();
                if (!string.isBlank(contract))
                {
                    newUrl.Contract__c = contract;
                }
                else if (!string.isBlank(opportunity))
                {
                    newUrl.Opportunity__c = opportunity;
                }               
                csvFileLines[i] = csvFileLines[i].replaceAll (',,', ', ,');
                if (csvFileLines[i].endsWith (',')) csvFileLines[i] += ' ';
                String [] csvRecordData = csvFileLines[i].split(',');
                newUrl.name = csvRecordData[0];
                
                newUrl.Platform__c=csvRecordData[1];
                
                newUrl.Format__c=csvRecordData[2];
                newUrl.Url__c=csvRecordData[3];
                if (csvRecordData [4] != ' '){
                    newUrl.IsPlaceholder__c=Boolean.valueOf(csvRecordData[4]);
                }
                newUrl.ClickThroughURL__c=csvRecordData[5];
                newUrl.Text__c=csvRecordData[6]; 
                try
                {
                    if (csvRecordData [7] != ' ')
                    {
                        String [] startDateFields = csvRecordData[7].split ('/');
                        for (String dateField : startDateFields)
                        {
                            if (dateField.startsWith ('0'))
                            {
                                dateField = dateField.removeStart('0');
                            }
                        }
                        newUrl.StartDate__c=Date.newInstance (Integer.valueOf (startDateFields [2]), Integer.valueOf (startDateFields [0]),
                                                              Integer.valueOf (startDateFields [1]));
                    }   
                    
                    if (csvRecordData [8] != ' ')
                    {
                        String [] endDateFields = csvRecordData[8].split ('/');
                        for (String dateField : endDatefields)
                        {
                            if (dateField.startsWith ('0'))
                            {
                                dateField = dateField.removeStart('0');
                            }
                        }
                        newUrl.EndDate__c =Date.newInstance (Integer.valueOf (endDateFields [2]), Integer.valueOf (endDateFields [0]),
                                                             Integer.valueOf (endDateFields [1]));
                    }
                }
                catch (ListException e)
                {
                    String mes = e.getMessage();
                    
                    ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'Date should be in DD/MM/YYYY or D/M/YYYY format.');
                    ApexPages.addMessage(errorMessage);
                    return null;
                }
                
                try
                {
                    if (!String.isBlank(csvRecordData [9])){
                        String before = csvRecordData[9];
                        String after = csvRecordData[9].remove ('\n');
                        after = after.remove('\r');
                        newUrl.Rotation__c= Decimal.valueOf(after);
                    }
                }
                catch (TypeException e)
                {
                    String mes = e.getMessage();
                    ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'Rotation field should be a number!');
                    ApexPages.addMessage(errorMessage);
                    return null;
                }
                
                newUrls.add(newUrl);   
            }
            insert newUrls;
        }
        catch (DmlException e)
        {
            String mes = e.getMessage();
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while importin data. Please make sure input csv file is correct' +
                                                                   '\n' + mes);
            ApexPages.addMessage(errorMessage);
            return null;
        }    
        
        PageReference pr = ApexPages.currentPage();
        pr.setRedirect(true);
        return pr;
    }
    
    public List<VideoUrl__c> getVideoUrls()
    {
        if (urls.isEmpty())
        {
            if (!string.isBlank(contract))
            {
                urls = VideoUrlRepository.getVideosForContract(contract);
            }
            else if (!string.isBlank(opportunity))
            {
                urls = VideoUrlRepository.getVideosForOpportunity(opportunity);
            }
        }
        
        return urls;
    }
    
    public void addNewVideoUrl()
    {
        VideoUrl__c videoUrl = new VideoUrl__c();
        
        if (!string.isBlank(contract))
        {
            List<Project__c> contracts = [SELECT Id, Start_Date__c, End_Date__c FROM Project__c
                                          WHERE Id =: contract];
            videoUrl.Contract__c = contract;
            videoUrl.StartDate__c=contracts[0].Start_Date__c;
            videoUrl.EndDate__c=contracts[0].End_Date__c;
        }
        else if (!string.isBlank(opportunity))
        {
            Opportunity opp = OpportunityRepository.getOpportunityById(opportunity);
            videoUrl.Opportunity__c = opportunity;
            videoUrl.StartDate__c = opp.Flight_Start__c;
            videoUrl.EndDate__c=opp.Flight_End__c;
        }
        List<SelectOption> platforms = getAvailablePlatforms();
        if(platforms.size()==1 && 
           (platforms[0].getLabel() =='Adwords CPM' || platforms[0].getLabel() =='TrueView'))
            videoUrl.format__c='Video';
        
        urls.add(videoUrl);     
    }
    
    public void cancelNewVideoUrl()
    {
        if (urls.size() > videoUrlRow) {
            urls.remove(videoUrlRow);
        }
    }
    
    public void saveVideoUrls()
    {
        Boolean isSuccess = true;
        
        try
        {
            upsert urls;
            List<Project__c> contracts = [SELECT Id FROM Project__c WHERE Id=:contract];
            if(contracts.size()>0) {
                contracts[0].PerformMMSync__c = true;
                contracts[0].LastModifiedBy__c = UserInfo.getUserId();
            }
            update contracts;
            
        }
        catch (DMLException ex)
        {
            ApexPages.addMessage(new ApexPages.Message(Apexpages.Severity.ERROR, ex.getDMLMessage(0)));
            isSuccess = false;
        }
        
        if (isSuccess)
        {
            ApexPages.addMessage(new ApexPages.Message(Apexpages.Severity.INFO, 'Saved successfully.'));
        }
    }
    
    public PageReference getCSVTemplate_Redirect ()
    {
        PageReference pr = Page.CreativesUploadCSVDownloader;
        pr.setRedirect(true);
        return pr;
    }
}