src/objects/Platform__c.object
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VideoUrl__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Video</fullName>
                    <default>true</default>
                    <label>Video</label>
                </value>
                <value>
                    <fullName>Carousel</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Page Post</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AdWords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Display Network</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rotation__c</fullName>
        <label>Rotation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Salesforce_ID__c</fullName>
        <label>Salesforce_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Creative</label>
    <nameField>
        <label>Creative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/projectInfoJSONTest.cls
@isTest
private class projectInfoJSONTest {

    @isTest static void testContructor() {
        TestHelper.setupEnv();
        Project__c contract = TestHelper.contracts[0];

        VideoUrl__c url1 = TestHelper.createVideoUrl();
        url1.Contract__c = contract.Id;
        url1.Name += '1';
        url1.Platform__c = 'TrueView';
        url1.Format__c = 'Video';
        url1.Url__c += '1';
        url1.StartDate__c = contract.Start_date__c;
        url1.EndDate__c = contract.End_Date__c;
        url1.Rotation__c = 1;
		url1.Salesforce_ID__c = 'a0A5B0000015XdKUAU';

        VideoUrl__c url2 = TestHelper.createVideoUrl();
        url2.Contract__c = contract.Id;
        url2.Name += '2';
        url2.Platform__c = 'TrueView';
        url2.Format__c = 'Video';
        url2.Url__c += '2';
        url2.StartDate__c = contract.Start_date__c;
        url2.EndDate__c = contract.End_Date__c;
        url2.Rotation__c = 1;
        url2.Salesforce_ID__c = 'a0A5B0000015XdKUAT';

        insert new List<VideoUrl__c> { url1, url2};

        Test.startTest();
            projectInfoJSON str = new projectInfoJSON(ContractRepository.getContractForMMSync(contract.Id));
        Test.stopTest();

        System.assertNotEquals('', str.strike_project_id);
        System.assertNotEquals('missing in SF', str.name);
        System.assertEquals(2, str.youtube_urls.size());

        ProjectInfoJSON.VideoUrl video1 = (ProjectInfoJSON.VideoUrl)str.youtube_urls[0];
        ProjectInfoJSON.VideoUrl video2 = (ProjectInfoJSON.VideoUrl)str.youtube_urls[1];

        System.assertEquals(url1.Salesforce_ID__c, video1.salesforce_id);
        System.assertEquals(url2.Salesforce_ID__c, video2.salesforce_id);
    }

    @isTest static void videoUrl_assignId_OnExternalIdNull() {
        TestHelper.setupEnv();
        Project__c contract = TestHelper.contracts[0];

        VideoUrl__c url1 = TestHelper.createVideoUrl();
        url1.Contract__c = contract.Id;
        url1.Name += '1';
        url1.Platform__c = 'TrueView';
        url1.Format__c = 'Video';
        url1.Url__c += '1';
        url1.StartDate__c = contract.Start_date__c;
        url1.EndDate__c = contract.End_Date__c;
        url1.Rotation__c = 1;

        VideoUrl__c url2 = TestHelper.createVideoUrl();
        url2.Contract__c = contract.Id;
        url2.Name += '2';
        url2.Platform__c = 'TrueView';
        url2.Format__c = 'Video';
        url2.Url__c += '2';
        url2.StartDate__c = contract.Start_date__c;
        url2.EndDate__c = contract.End_Date__c;
        url2.Rotation__c = 1;

        insert new List<VideoUrl__c> { url1, url2};

        Test.startTest();
            projectInfoJSON str = new projectInfoJSON(ContractRepository.getContractForMMSync(contract.Id));
        Test.stopTest();

        System.assertNotEquals('', str.strike_project_id);
        System.assertNotEquals('missing in SF', str.name);
        System.assertEquals(2, str.youtube_urls.size());

        ProjectInfoJSON.VideoUrl video1 = (ProjectInfoJSON.VideoUrl)str.youtube_urls[0];
        ProjectInfoJSON.VideoUrl video2 = (ProjectInfoJSON.VideoUrl)str.youtube_urls[1];

        System.assertEquals(url1.id, video1.salesforce_id);
        System.assertEquals(url2.id, video2.salesforce_id);
    }

	@isTest static void contract_AssignId_OnExternalIdNull() {
        TestHelper.setupEnv();
        Project__c contract = TestHelper.contracts[0];

        Test.startTest();
            projectInfoJSON str = new projectInfoJSON(ContractRepository.getContractForMMSync(contract.Id));
        Test.stopTest();

        System.assertEquals(contract.Id, str.salesforce_id);
    }    

    @isTest static void contract_AssignId_OnExternalIdNotNull() {
        TestHelper.setupEnv();
        Project__c contract = TestHelper.contracts[0];

        Test.startTest();
            projectInfoJSON str = new projectInfoJSON(ContractRepository.getContractForMMSync(contract.Id));
        Test.stopTest();

        System.assertEquals(contract.Id, str.salesforce_id);
    }

	@isTest static void testJSONFormat() {
        TestHelper.setupEnv();
        Project__c contract = TestHelper.contracts[0];

        projectInfoJSON str = new projectInfoJSON(ContractRepository.getContractForMMSync(contract.Id));

        Test.startTest();
            String result = str.getJSONFormat();
        Test.stopTest();
    }
}