src/objects/Platform__c.object
<CustomObject>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VideoUrl__c.object
<CustomObject>
    <fields>
        <fullName>Archive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ClickThroughURL__c</fullName>
        <label>Click Through URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Video</fullName>
                    <default>true</default>
                    <label>Video</label>
                </value>
                <value>
                    <fullName>Carousel</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Banner</fullName>
                </value>
                <value>
                    <fullName>Page Post</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsPlaceholder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Placeholder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Cascade</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>YouTubeURLs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AdWords CPM</fullName>
                </value>
                <value>
                    <fullName>DBM RTB</fullName>
                </value>
                <value>
                    <fullName>DBM TrueView</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Google Display Network</fullName>
                </value>
                <value>
                    <fullName>Google Search</fullName>
                </value>
                <value>
                    <fullName>Instagram</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Pinterest</fullName>
                </value>
                <value>
                    <fullName>Snapchat</fullName>
                </value>
                <value>
                    <fullName>TrueView</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rotation__c</fullName>
        <label>Rotation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Creative</label>
    <nameField>
        <label>Creative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Creatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VideoUrlRepository.cls
public class VideoUrlRepository {

    public static List<VideoUrl__c> getVideosForOpportunity(Id opportunityId) {
        Map<Id, List<VideoUrl__c>> opportunityVideos = getVideosForOpportunities(new Set<Id>{opportunityId});

        List<VideoUrl__c> creatives = new List<VideoUrl__c>();
        if (opportunityVideos.containsKey(opportunityId)) {
            creatives = opportunityVideos.get(opportunityId);
        }
        return creatives;
    }
    
    public static Map<Id, List<VideoUrl__c>> getVideosForOpportunities(Set<Id> opportunityIds) {
        List<VideoUrl__c> creatives = getCreativesByOppIds(opportunityIds);

        Map<Id, List<VideoUrl__c>> creativesMap = new Map<Id, List<VideoUrl__c>>();
        for (VideoUrl__c videoUrl :creatives) {
            if (!creativesMap.containsKey(videoUrl.Opportunity__c)) {
                creativesMap.put(videoUrl.Opportunity__c, new List<VideoUrl__c>());
            }
            creativesMap.get(videoUrl.Opportunity__c).add(videoUrl);

        }
        return creativesMap;
    }

    private static List<VideoUrl__c> getCreativesByOppIds(Set<Id> opportunityIds) {
        return [
            SELECT Name, Archive__c, ClickThroughURL__c, Contract__c, EndDate__c, Format__c, Opportunity__c, Platform__c, IsPlaceholder__c, Rotation__c,
                StartDate__c, Text__c, Url__c
            FROM VideoUrl__c
            WHERE Opportunity__c IN :opportunityIds
            ORDER BY Name ASC
        ];
    }
    
    public static List<VideoUrl__c> getVideosForContract(String contractId) {
        return [
            SELECT Name, Archive__c, ClickThroughURL__c, Contract__c, EndDate__c, Format__c, Opportunity__c, Platform__c, IsPlaceholder__c, Rotation__c,
                StartDate__c, Text__c, Url__c
            FROM VideoUrl__c
            WHERE Contract__c = :contractId
            ORDER BY StartDate__c ASC
        ];
    }
}