src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Ended__c</fullName>
        <formula>Today()&gt;=End_Date__c + 3</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract End Date+3</label>
        <type>Checkbox</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Ended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract End Date+3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubProjectEndingBatch_Test.cls
@isTest
private class SubProjectEndingBatch_Test {

    testmethod static void synchronizeContractEnd() {
        TestHelper.setupEnv();
        Sub_Project__c sp = [SELECT Id, Project__c FROM Sub_Project__c LIMIT 1];
        sp.Contract_Ended__c=false;
        update sp;
        
        Test.startTest();
        Database.executeBatch(new SubProjectEndingBatch(), 200);
        Test.stopTest();
        
        system.assertEquals(0, [SELECT count() FROM Sub_Project__c WHERE Contract_Ended__c=false
                               AND Id=:sp.Id]);
        
    }
}