src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Client_IO__c</fullName>
        <label>IO #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Xero_Campaign_Name__c</fullName>
        <label>Custom Xero Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <label>PO#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sub_Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectID__c</fullName>
        <formula>Project__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Strike ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Contract</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Sub_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/XeroUtils.cls
public class XeroUtils {
    public Static String LINE_ITEM_DESCRIPTION_CAMPAIGN_ID = 'Campaign ID: ';
    public Static String LINE_ITEM_DESCRIPTION_CAMPAIGN_NAME = 'Campaign Name: ';
    public Static String LINE_ITEM_DESCRIPTION_PO = 'PO: ';
    public Static String LINE_ITEM_DESCRIPTION_IO = 'IO: ';
    public Static String LINE_ITEM_DESCRIPTION_INVOICING_PERIOD = 'Invoicing Period: ';


    public static string prepareLineItemDescription(Sub_Project__c payment) {
        String customName = (payment.Project__r.Custom_Xero_Campaign_Name__c != null) ? payment.Project__r.Custom_Xero_Campaign_Name__c : payment.Project__r.Name;

        String retVal = LINE_ITEM_DESCRIPTION_CAMPAIGN_ID + payment.ProjectId__c + '\n'
                      + LINE_ITEM_DESCRIPTION_CAMPAIGN_NAME + customName + '\n';

        if (String.isNotBlank(payment.Project__r.PO__c)) {
            retVal +=  LINE_ITEM_DESCRIPTION_PO + payment.Project__r.PO__c + '\n';
        }

        retVal += LINE_ITEM_DESCRIPTION_IO + (String.IsBlank(payment.Project__r.Client_IO__c) == false ? String.valueOf(payment.Project__r.Client_IO__c) : '')+ '\n'
               + LINE_ITEM_DESCRIPTION_INVOICING_PERIOD + payment.Start_Date__c.format() + ' to ' + payment.End_Date__c.format();

        return retVal;
    }
}