src/objects/Spend_Threshold__c.object
<CustomObject>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Spend Thresholds</relationshipLabel>
        <relationshipName>Spend_Thresholds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spend_From__c</fullName>
        <label>Spend From</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Spend_To__c</fullName>
        <label>Spend To</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Spend Threshold</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spend Thresholds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SpendThresholdRepository.cls
public class SpendThresholdRepository {
    public static List<Spend_Threshold__c> getSpendThresholdsForOpportunity(Id opportunityId)
    {
        List<Spend_Threshold__c> retVal = new List<Spend_Threshold__c>();
        
        Map<Id, List<Spend_Threshold__c>> opportunitySpendThresholds = getSpendThresholdsForOpportunities(new Set<Id> {opportunityId}); 
        
        if (opportunitySpendThresholds.containsKey(opportunityId))
        {
            retVal = opportunitySpendThresholds.get(opportunityId);                
        }
        
        return retVal;
    }
    
    public static Map<Id, List<Spend_Threshold__c>> getSpendThresholdsForOpportunities(Set<Id> opportunityIds)
    {
        Map<Id, List<Spend_Threshold__c>> retVal = new Map<Id, List<Spend_Threshold__c>>();
        
        for (Spend_Threshold__c spendThreshold : [SELECT Name, Fee__c, Opportunity__c, Spend_From__c, Spend_To__c
                                                  FROM Spend_Threshold__c
                                                  WHERE Opportunity__c IN :opportunityIds
                                                  ORDER BY Spend_From__c ASC])
        {
            if (!retVal.containsKey(spendThreshold.Opportunity__c))
            {
                retVal.put(spendThreshold.Opportunity__c, new List<Spend_Threshold__c> { spendThreshold });                   
            }                
            else
            {
                retVal.get(spendThreshold.Opportunity__c).add(spendThreshold);                
            }
        }
        return retVal;
    }
}